import codes from "./home-country-codes.json";

/*
 * The codes a profile edit may name. The backend decides which those are
 * (argus.domain.home_country); home-country-codes.json is its projection,
 * regenerated by scripts/generate_home_country_codes.py. Names come from the
 * browser's own locale data, in the reader's language.
 */
export const COUNTRY_CODES: readonly string[] = codes.countries;
export const CURRENCY_CODES: readonly string[] = codes.currencies;

const displayNames = new Map<string, Intl.DisplayNames>();

function namer(language: string, type: "region" | "currency"): Intl.DisplayNames {
  const key = `${language}:${type}`;
  let names = displayNames.get(key);
  if (!names) {
    names = new Intl.DisplayNames([language], { type });
    displayNames.set(key, names);
  }
  return names;
}

export function countryName(code: string, language: string): string {
  return namer(language, "region").of(code) ?? code;
}

export function currencyName(code: string, language: string): string {
  return namer(language, "currency").of(code) ?? code;
}

/**
 * The country a browser language tag names outright, such as `es-MX`. A tag
 * without one names none: `es` is not a guess at Spain. Only a suggestion;
 * nothing saves until the user picks.
 */
export function browserRegion(languageTags: readonly string[]): string | null {
  for (const tag of languageTags) {
    let region: string | undefined;
    try {
      region = new Intl.Locale(tag).region;
    } catch {
      continue;
    }
    if (region && COUNTRY_CODES.includes(region)) return region;
  }
  return null;
}
