"""Generate the Cuadrao device book's currency table from the server's tender set.

The set is `argus.domain.home_country.currency_codes()` and the exponent is
`argus.domain.recording.currency.currency_exponent`, so the device book accepts
exactly the currencies the server accepts and reads the same minor-unit digits.
Run from the repository root with the backend environment:

    .venv/bin/python ios/scripts/generate_book_currencies.py          # write
    .venv/bin/python ios/scripts/generate_book_currencies.py --check  # drift check

`tests/test_cuadrao_book_conformance.py` runs the check, so a CLDR or babel
upgrade that moves the set fails a test instead of drifting silently.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "ios/Packages/CuadraoBook"
SWIFT = PACKAGE / "Sources/CuadraoBook/CurrencyTable.swift"
VECTORS = PACKAGE / "Vectors/currencies.json"


def server_table() -> dict[str, int]:
    sys.path.insert(0, str(ROOT / "src"))
    from argus.domain.home_country import currency_codes
    from argus.domain.recording.currency import currency_exponent

    return {code: currency_exponent(code) for code in sorted(currency_codes())}


def render_swift(table: dict[str, int]) -> str:
    rows = ",\n".join(f'    ("{code}", {digits})' for code, digits in table.items())
    return f"""// Generated by ios/scripts/generate_book_currencies.py from the server's tender set. Do not edit.

/// Every currency the server accepts, with its CLDR minor-unit digits.
let generatedCurrencyRows: [(code: String, digits: Int)] = [
{rows}
]
"""


def render_json(table: dict[str, int]) -> str:
    return json.dumps(table, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    table = server_table()
    outputs = {SWIFT: render_swift(table), VECTORS: render_json(table)}
    if args.check:
        stale = [str(path) for path, text in outputs.items() if not path.exists() or path.read_text() != text]
        if stale:
            print("Stale generated currency files:", *stale, sep="\n  ")
            return 1
        return 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"Wrote {len(table)} currencies.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
