import type { BusinessLocale } from "@/lib/business-site";

export const businessContactEmail = "hola@cuadrao.ai";

const es = {
  title: ["Cada cuenta.", "En su sitio."],
  description:
    "Estamos construyendo Cuadrao para reunir ingresos, gastos, clientes y documentos. Para que sepas qué falta por cobrar, qué debes pagar y qué necesita atención.",
  audience: "Para pequeños y medianos negocios en República Dominicana.",
  explore: "Ver cómo funciona",
  cta: "Hablemos de tu negocio",
  overviewLabel: "DINERO, CLIENTES Y DOCUMENTOS",
  overviewTitle: "Tu negocio, con las cuentas conectadas.",
  overviewBody: "Una venta mueve más que dinero. Hay un cliente, un compromiso de pago y documentos que explican lo que pasó. Queremos reunir esas piezas.",
  overviewDomains: ["Dinero", "Clientes", "Cobros", "Documentos"],
  overviewInsights: [
    "Una entrada de dinero vinculada a la venta que la explica.",
    "La cuenta del cliente reúne la venta, el abono y lo que queda por cobrar.",
    "El saldo pendiente ayuda a saber qué conversación toca tener.",
    "El documento acompaña a la cuenta para poder revisar de dónde sale cada monto.",
  ],
  overviewCaption: "Esta cuenta, después del abono",
  accountLabel: "Cuenta del cliente",
  saleLabel: "Venta a crédito",
  transferLabel: "Abono por transferencia",
  recordLabel: "Registro relacionado",
  documentLabel: "Documento de la venta",
  attentionLabel: "Lo que necesita atención",
  attentionBody: "Confirmar con el cliente cuándo llega el próximo abono.",
  accountScope: "Saldo de esta factura",
  followAccount: "Sigue esta cuenta",
  connectedNote: "El mismo cliente. La misma factura. Cada movimiento en su lugar.",
  practicalTitle: "Así pasa en un negocio de aquí.",
  practicalBody: "Vendes mercancía a crédito. El cliente abona una parte por transferencia y el comprobante queda en otro lugar. Saber qué falta por cobrar no debería exigir reconstruir la venta cada vez.",
  practicalNote: "Ese es el tipo de trabajo que queremos simplificar, junto a los negocios que lo hacen a diario.",
  replayLabel: "CÓMO SE CONECTA ESTA CUENTA",
  replayBody: "Volvamos al inicio de la misma venta. Recorre la factura, el abono y el saldo para ver cómo encajan.",
  faqTitle: "Antes de conversar.",
  faqBody: "Dónde estamos hoy y qué puedes esperar de Cuadrao.",
  faq: [
    { question: "¿Ya puedo usar Cuadrao para mi negocio?", answer: "Estamos preparando el producto con posibles primeros clientes. Los ejemplos de esta página muestran funciones previstas con datos ficticios. Antes de un piloto, acordaremos contigo qué puedes probar, el acceso y el acompañamiento." },
    { question: "¿Para quién es y en qué ayudará?", answer: "Para pequeños y medianos negocios en República Dominicana. Queremos ayudarte a entender tus cuentas, planear pagos y metas, separar el dinero personal y seguir clientes y cobros. También prevemos cotizaciones, borradores no fiscales y reportes por período. Cada cobro tendrá su comisión separada del dinero recibido. Los estados de cobro, venta y emisión fiscal seguirán siendo distintos." },
    { question: "¿Cuánto va a costar?", answer: "Aún no hemos definido los precios. Cualquier alcance y costo se acordará contigo antes de empezar." },
    { question: "¿Qué límites debo conocer?", answer: "Cuadrao no reemplaza a tu contador. La emisión fiscal requiere un proveedor certificado y no está disponible. Tampoco anunciamos conexión bancaria automática, pagos desde Cuadrao, nómina, inventario ni declaraciones de impuestos. Transferencias, devoluciones, correcciones y conciliación están previstas; el alcance del piloto aún está por definir." },
    { question: "¿Qué pasa cuando hablamos?", answer: `Hablas conmigo, Lucas, fundador de Cuadrao. Me cuentas cómo trabajas, revisamos lo que estoy preparando y decidimos si tiene sentido explorar un piloto. No necesitas compartir documentos ni información financiera privada. Puedes escribirme a ${businessContactEmail}.` },
  ],
  faqLink: "Preguntas frecuentes",
  footerExplore: "CONOCE EL PRODUCTO",
  footerTalk: "CONVERSEMOS",
  storyTitle: "Cada venta, hasta el último abono.",
  storyBody:
    "Lo que se vendió, lo que se pagó y lo que falta. Así queremos ayudarte a verlo, todo junto.",
  storySteps: [
    {
      title: "La factura",
      body: "Empieza por lo que vendiste. El documento y su monto, en el mismo lugar.",
    },
    {
      title: "El abono",
      body: "Cada abono, junto a su factura.",
    },
    {
      title: "Lo pendiente",
      body: "Mira cuánto queda por cobrar, sin perder de vista el documento y el pago.",
    },
  ],
  note: "Vista ilustrativa · datos de ejemplo",
  invoice: "Factura",
  customer: "Cliente ficticio",
  total: "Total de la factura",
  payment: "Abono registrado",
  pending: "Pendiente por cobrar",
  received: "Abonado",
  source: "Documento de origen",
  document: "Ver documento",
  closeDocument: "Cerrar documento",
  sampleDocument: "Documento ilustrativo, sin validez fiscal",
  item: "Venta de mercancía",
  detail: "Detalle",
  amount: "Monto",
  next: "Siguiente paso",
  nextActions: ["Ver el abono", "Ver lo pendiente", "Volver al inicio"],
  noPayment: "Sin abonos en este ejemplo",
  receipt: "Comprobante de abono",
  linkedTo: "Relacionado con",
  calculation: "Total menos abono",
  replay: "Volver al inicio",
  status: ["Por revisar", "Pago relacionado", "Saldo calculado"],
  explanation: [
    "Primero, el documento que da origen a la cuenta.",
    "El abono pertenece a esta factura. No es otra venta.",
    "El total menos el abono. Lo pendiente queda a la vista.",
  ],
  approachTitle: "Primero, tu forma de trabajar.",
  approachBody:
    "Cuéntanos qué necesitas resolver. Elegimos juntos un trabajo concreto para un primer piloto.",
  steps: [
    {
      title: "Nos cuentas",
      body: "Cómo revisas tu dinero, qué decisiones vienen y qué trabajo se te queda pendiente.",
    },
    {
      title: "Lo vemos juntos",
      body: "Revisamos tu proceso, te mostramos lo que estamos preparando y elegimos un trabajo concreto para probar.",
    },
    {
      title: "Acordamos qué sigue",
      body: "Acordamos qué probar, el acceso, el acompañamiento y el costo antes de empezar.",
    },
  ],
  founderLabel: "DETRÁS DE CUADRAO",
  founderTitle: "Soy Lucas.\nFundador de Cuadrao.",
  founderParagraphs: [
    "Estoy construyendo Cuadrao para ayudarte a entender tu dinero y planificar lo que sigue. Quiero que tengas más tiempo para el trabajo que te llevó a empezar tu negocio.",
    "Mi experiencia está en tecnología, aprendizaje automático y ciencia de datos. Quiero usar lo que sé para resolver problemas que encuentras cada día. Eso empieza por escuchar cómo trabajas y qué te cuesta mantener al día.",
    "Mi compromiso es construir con cuidado, probar lo que sirve y aprender de ti. Cada función debe ayudarte a terminar una tarea o tomar una decisión, con tu dinero, clientes y documentos en un mismo lugar.",
    "La conversación es conmigo. Me gustaría saber qué funciona en tu negocio y qué quisieras cambiar. Gracias por compartir tu experiencia y ayudarme a dar forma a Cuadrao.",
  ],
  founderNote: "En esta etapa, la conversación es conmigo.",
  founderRole: "Lucas · Fundador de Cuadrao",
  closingTitle: "Cuéntanos cómo llevas\ntu negocio.",
  closingBody:
    "Cuéntanos qué te cuesta llevar al día. Te mostraremos lo que estamos preparando.",
  stage: "Cuadrao para negocios está en desarrollo.",
  footerTag: "Las cuentas claras.\nEl negocio, adelante.",
  footerLocal: "Pensado para los negocios de aquí.",
  contact: "Contacto",
  emailInvitation: "También puedes escribirnos directamente.",
  emailHelp: "Se abre tu aplicación de correo. Tú revisas y envías el mensaje.",
  top: "Volver arriba",
  business: "Para negocios",
  personal: "Personal",
  idea: "La idea",
  about: "Nosotros",
  contactLead: "Empecemos por\ntu negocio.",
  contactBody:
    "No necesitas tener todo organizado para conversar. Cuéntanos qué te cuesta mantener al día.",
  contactNote:
    "No incluyas documentos, números de cuenta ni información financiera privada.",
};
const en: typeof es = {
  title: ["Every record.", "In its place."],
  description:
    "We’re building Cuadrao to bring income, expenses, customers and documents together. So you know what’s still to collect, what you need to pay and what needs attention.",
  audience: "For small and medium businesses in the Dominican Republic.",
  explore: "See how it works",
  cta: "Let’s talk about your business",
  overviewLabel: "MONEY, CUSTOMERS AND DOCUMENTS",
  overviewTitle: "Your business, with the records connected.",
  overviewBody: "A sale involves more than money. There is a customer, a payment commitment and documents that explain what happened. We want to bring those pieces together.",
  overviewDomains: ["Money", "Customers", "Collections", "Documents"],
  overviewInsights: [
    "Money received, linked to the sale that explains it.",
    "The customer account brings together the sale, payment and outstanding balance.",
    "The outstanding balance helps you see which conversation needs to happen next.",
    "The document stays with the account so you can check where each amount comes from.",
  ],
  overviewCaption: "This account, after the payment",
  accountLabel: "Customer account",
  saleLabel: "Sale on credit",
  transferLabel: "Payment by bank transfer",
  recordLabel: "Linked record",
  documentLabel: "Sales document",
  attentionLabel: "What needs attention",
  attentionBody: "Confirm when the customer plans to make the next payment.",
  accountScope: "Balance on this invoice",
  followAccount: "Follow this account",
  connectedNote: "The same customer. The same invoice. Every movement accounted for.",
  practicalTitle: "A familiar day in business.",
  practicalBody: "You sell goods on credit. The customer makes a partial payment by bank transfer, and the receipt ends up somewhere else. Knowing what remains to collect should not mean piecing the sale back together every time.",
  practicalNote: "This is the work we want to simplify, alongside the businesses doing it every day.",
  replayLabel: "HOW THIS ACCOUNT CONNECTS",
  replayBody: "Go back to the start of the same sale. Explore the invoice, payment and balance to see how they fit together.",
  faqTitle: "Before we talk.",
  faqBody: "Where we are today and what to expect from Cuadrao.",
  faq: [
    { question: "Can I use Cuadrao for my business yet?", answer: "We are preparing the product with potential first customers. The examples on this page show planned features with fictional data. Before a pilot, we will agree with you on what you can try, access and support." },
    { question: "Who is it for, and how will it help?", answer: "Small and medium businesses in the Dominican Republic. We want to help you understand your accounts, plan payments and goals, separate personal money and follow customers and collections. Quotes, non-tax drafts and period reports are also planned. Fees will stay separate from money received. Payment, sales and tax issuance statuses will remain distinct." },
    { question: "How much will it cost?", answer: "We have not set prices yet. We will agree on scope and cost with you before starting." },
    { question: "What limits should I know about?", answer: "Cuadrao does not replace your accountant. Tax invoice issuance requires a certified provider and is not available. We are not announcing automatic bank connections, payments from Cuadrao, payroll, inventory or tax filing. Transfers, refunds, corrections and reconciliation are planned; the pilot scope is still being defined." },
    { question: "What happens when we talk?", answer: `You speak with me, Lucas, Cuadrao's founder. Tell me how you work, see what I am preparing and decide whether exploring a pilot makes sense. You do not need to share documents or private financial information. You can email me at ${businessContactEmail}.` },
  ],
  faqLink: "Common questions",
  footerExplore: "EXPLORE THE PRODUCT",
  footerTalk: "LET’S TALK",
  storyTitle: "Follow each sale through to payment.",
  storyBody:
    "What was sold, what was paid and what remains. This is how we want to help you see it all together.",
  storySteps: [
    {
      title: "The invoice",
      body: "Start with what you sold. The document and its amount, in the same place.",
    },
    {
      title: "The payment",
      body: "Each payment, alongside its invoice.",
    },
    {
      title: "What’s outstanding",
      body: "See what remains to collect, with the original document and payment in view.",
    },
  ],
  note: "Illustrative view · sample data",
  invoice: "Invoice",
  customer: "Fictional customer",
  total: "Invoice total",
  payment: "Recorded payment",
  pending: "Outstanding balance",
  received: "Paid",
  source: "Source document",
  document: "View document",
  closeDocument: "Close document",
  sampleDocument: "Illustrative document, not a tax invoice",
  item: "Sale of goods",
  detail: "Description",
  amount: "Amount",
  next: "Next step",
  nextActions: ["See the payment", "See what remains", "Start again"],
  noPayment: "No payments in this example",
  receipt: "Payment receipt",
  linkedTo: "Linked to",
  calculation: "Total minus payment",
  replay: "Start again",
  status: ["To review", "Payment linked", "Balance calculated"],
  explanation: [
    "First, the document that creates the record.",
    "The payment belongs to this invoice. It is not another sale.",
    "The total minus the payment. What remains is clear.",
  ],
  approachTitle: "Your way of working comes first.",
  approachBody:
    "Tell us what you need to solve. Together, we choose a specific job for a first pilot.",
  steps: [
    {
      title: "Tell us",
      body: "How you review your money, which decisions are coming and what work falls behind.",
    },
    {
      title: "Explore Cuadrao together",
      body: "We review your process, show you what we are preparing and choose a specific job to test.",
    },
    {
      title: "Decide what’s next",
      body: "Before starting, we agree on what to test, access, support and cost.",
    },
  ],
  founderLabel: "BEHIND CUADRAO",
  founderTitle: "I’m Lucas.\nFounder of Cuadrao.",
  founderParagraphs: [
    "I am building Cuadrao to help you understand your money and plan what comes next. I want you to have more time for the work that made you start your business.",
    "My background is in technology, machine learning and data science. I want to use what I know to solve problems you face each day. That starts with listening to how you work and what is hard to keep up with.",
    "My commitment is to build with care, test what works and learn from you. Each feature must help you finish a task or make a decision, with your money, customers and documents in one place.",
    "You will speak directly with me. I would like to hear what works in your business and what you want to change. Thank you for sharing your experience and helping me shape Cuadrao.",
  ],
  founderNote: "At this stage, you’ll be talking with me.",
  founderRole: "Lucas · Founder of Cuadrao",
  closingTitle: "Tell us how you run\nyour business.",
  closingBody:
    "Tell us what’s hard to keep up with. We’ll show you what we’re preparing.",
  stage: "Cuadrao for business is in development.",
  footerTag: "Clear records.\nBusiness moves forward.",
  footerLocal: "Built with local businesses in mind.",
  contact: "Contact",
  emailInvitation: "You can also email us directly.",
  emailHelp: "Opens your email app. You review and send the message.",
  top: "Back to top",
  business: "Business",
  personal: "Personal",
  idea: "The idea",
  about: "About",
  contactLead: "Let’s start with\nyour business.",
  contactBody:
    "You don’t need to have everything organized to talk. Tell us what’s hard to keep up with.",
  contactNote:
    "Do not include documents, account numbers or private financial information.",
};
export const siteCopy: Record<BusinessLocale, typeof es> = { es, en };
