#!/bin/bash
# Shared Argus environment contract for local mode scripts and Render drift tests.

ARGUS_PRIVATE_LAUNCH_APP_URL="https://argus-app-suz5.onrender.com"
ARGUS_PRIVATE_LAUNCH_API_URL="https://argus-ohr5.onrender.com"
ARGUS_PRIVATE_LAUNCH_API_BASE_URL="${ARGUS_PRIVATE_LAUNCH_API_URL}/api/v1"
ARGUS_PRIVATE_LAUNCH_CORS_ORIGINS="$ARGUS_PRIVATE_LAUNCH_APP_URL"
ARGUS_PRIVATE_LAUNCH_API_SERVICE_ID="srv-d78tanmuk2gs73e17nn0"
ARGUS_PRIVATE_LAUNCH_WEB_SERVICE_ID="srv-d7ap6bmslomc73eqp8m0"
ARGUS_RENDER_BACKTESTS_WORKFLOW_ID="wfl-d8hpsmuq1p3s73duv3q0"
ARGUS_BACKTEST_WORKFLOW_TASK_DEFAULT="argus-backtests/workflow_proof"
ARGUS_BACKTEST_REAL_WORKFLOW_TASK_DEFAULT="argus-backtests/run_backtest_job"
ARGUS_RENDER_POETRY_VERSION="2.1.3"
ARGUS_RENDER_API_BUILD_COMMAND="poetry config virtualenvs.create false && poetry install --only main --no-interaction"
ARGUS_RENDER_API_START_COMMAND="poetry run uvicorn argus.api.main:app --host 0.0.0.0 --port \$PORT"
ARGUS_RENDER_WORKFLOW_BUILD_COMMAND="poetry config virtualenvs.create false && poetry install --only main,workflows --no-interaction"
ARGUS_RENDER_WORKFLOW_START_COMMAND="poetry run python workflows/main.py"

ARGUS_QA_REQUIRED_ENV=(
  SUPABASE_PROJECT_URL
  SUPABASE_ANON_PUBLIC_KEY
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_JWT_SECRET
  SUPABASE_POSTGRES_SESSION_POOLER_URL
  ALPACA_API_KEY
  ALPACA_SECRET_KEY
  OPENROUTER_API_KEY
  ARGUS_UTILITY_MODEL
  ARGUS_UTILITY_FALLBACK_MODEL
  ARGUS_CHAT_MODEL
  ARGUS_CHAT_FALLBACK_MODEL
  ARGUS_STRUCTURED_MODEL
  ARGUS_STRUCTURED_FALLBACK_MODEL
  ARGUS_CONTEXT_MODEL
  ARGUS_CONTEXT_FALLBACK_MODEL
)

ARGUS_RENDER_API_ENV=(
  APP_ENV
  POETRY_VERSION
  ARGUS_PERSISTENCE_MODE
  ARGUS_DEV_MEMORY_FALLBACK
  ARGUS_MARKET_DATA_PROVIDER_MODE
  MARKET_DATA_CACHE_TTL
  ARGUS_RUNTIME_EVENT_TIMEOUT_SECONDS
  ARGUS_RUNTIME_EVENT_KEEPALIVE_SECONDS
  ARGUS_CHECKPOINTER_MODE
  ARGUS_MOCK_AUTH
  ARGUS_CORS_ALLOW_ORIGINS
  ARGUS_STRATEGIES_ENABLED
  ARGUS_BACKTEST_JOBS_SHADOW_ENABLED
  ARGUS_BACKTEST_JOBS_DISPATCH_ENABLED
  ARGUS_BACKTEST_WORKFLOW_EXECUTION_ENABLED
  ARGUS_BACKTEST_WORKFLOW_TASK
  ARGUS_BACKTEST_REAL_WORKFLOW_TASK
  ARGUS_BACKTEST_JOBS_USER_RUNNING_LIMIT
  ARGUS_BACKTEST_JOBS_USER_QUEUED_LIMIT
  ARGUS_BACKTEST_JOBS_GLOBAL_RUNNING_LIMIT
  ARGUS_BACKTEST_JOBS_GLOBAL_QUEUED_LIMIT
  ARGUS_CONTEXT_PACKETS_ENABLED
  ARGUS_CONTEXT_PACKET_BUDGET_SECONDS
  ARGUS_TITLE_AUTOGEN_ENABLED
  ARGUS_TITLE_AUTOGEN_TIMEOUT_MS
  ARGUS_READINESS_ASSET_TIMEOUT_SECONDS
  ARGUS_OPS_TOKEN
  DATABASE_URL
  SUPABASE_URL
  SUPABASE_ANON_KEY
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_JWT_SECRET
  RENDER_API_KEY
  OPENROUTER_API_KEY
  ARGUS_UTILITY_MODEL
  ARGUS_UTILITY_FALLBACK_MODEL
  ARGUS_CHAT_MODEL
  ARGUS_CHAT_FALLBACK_MODEL
  ARGUS_OPENROUTER_RESULT_SUMMARY_TIMEOUT_SECONDS
  ARGUS_STRUCTURED_MODEL
  ARGUS_STRUCTURED_FALLBACK_MODEL
  ARGUS_CONTEXT_MODEL
  ARGUS_CONTEXT_FALLBACK_MODEL
  ALPACA_API_KEY
  ALPACA_SECRET_KEY
  ALPACA_PAPER_TRADING
)

ARGUS_RENDER_WEB_ENV=(
  NEXT_PUBLIC_APP_ENV
  NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY
  NEXT_PUBLIC_POSTHOG_KEY
  NEXT_PUBLIC_MOCK_AUTH
  NEXT_PUBLIC_ENABLE_SPANISH
  NEXT_PUBLIC_ARGUS_API_URL
  NEXT_PUBLIC_STRATEGIES_ENABLED
  NEXT_PUBLIC_COLLECTIONS_ENABLED
  NEXT_PUBLIC_OMNISEARCH_ENABLED
  NEXT_PUBLIC_PRIVATE_ALPHA_ONBOARDING_ENABLED
  NEXT_PUBLIC_CHAT_EXPLORATORY_SUGGESTIONS_ENABLED
)

ARGUS_RENDER_WORKFLOW_PROOF_ENV=(
  ARGUS_WORKFLOW_DATABASE_URL
  ARGUS_RENDER_WORKFLOW_PROOF_TASK
  ARGUS_WORKFLOW_PROOF_PLAN
  POETRY_VERSION
  ARGUS_BACKTEST_WORKFLOW_TIMEOUT_SECONDS
  ARGUS_MARKET_DATA_PROVIDER_MODE
  ENABLE_MARKET_DATA_CACHE
  ALPACA_API_KEY
  ALPACA_SECRET_KEY
  ALPACA_PAPER_TRADING
  OPENROUTER_API_KEY
  ARGUS_UTILITY_MODEL
  ARGUS_UTILITY_FALLBACK_MODEL
  ARGUS_CHAT_MODEL
  ARGUS_CHAT_FALLBACK_MODEL
  ARGUS_OPENROUTER_RESULT_SUMMARY_TIMEOUT_SECONDS
  ARGUS_STRUCTURED_MODEL
  ARGUS_STRUCTURED_FALLBACK_MODEL
  ARGUS_CONTEXT_MODEL
  ARGUS_CONTEXT_FALLBACK_MODEL
)

ARGUS_RENDER_WORKFLOW_RELEASE_ENV=(
  ARGUS_RENDER_WORKFLOW_RELEASE_COMMIT
  ARGUS_RENDER_WORKFLOW_RELEASE_VERSION_ID
)

ARGUS_FORBIDDEN_LEGACY_ENV=(
  NEXT_PUBLIC_API_URL
  NEXT_PUBLIC_MOCK_API
  AGENT_MODEL
  AGENT_FALLBACK_MODEL
)

argus_load_root_env() {
  if [ -f .env ]; then
    set -a
    set +u
    # shellcheck disable=SC1091
    source .env
    set -u
    set +a
    return 0
  fi
  return 1
}

argus_require_env() {
  local name="$1"
  local value
  local had_nounset=0

  case "$-" in
    *u*)
      had_nounset=1
      set +u
      ;;
  esac
  value="${!name}"
  if [ "$had_nounset" -eq 1 ]; then
    set -u
  fi

  if [ -z "$value" ] || [[ "$value" == YOUR_* ]] || [[ "$value" == your_* ]]; then
    echo "❌ $name is required."
    exit 1
  fi
}

argus_require_qa_env() {
  local name
  for name in "${ARGUS_QA_REQUIRED_ENV[@]}"; do
    argus_require_env "$name"
  done
}

argus_export_dev_mode() {
  export ARGUS_PERSISTENCE_MODE=memory
  export ARGUS_DEV_MEMORY_FALLBACK=true
  export ARGUS_MARKET_DATA_PROVIDER_MODE=synthetic_unit_fixture
  export ARGUS_CHECKPOINTER_MODE=memory
  export ARGUS_MOCK_AUTH=true
  # Skip the onboarding gate in dev so memory-mode restarts don't re-prompt for it.
  export ARGUS_PRIVATE_ALPHA_ONBOARDING_ENABLED=false
  export ENABLE_MARKET_DATA_CACHE=false
  export ARGUS_BACKTEST_JOBS_SHADOW_ENABLED=false
  export ARGUS_BACKTEST_JOBS_DISPATCH_ENABLED=false
  export ARGUS_BACKTEST_WORKFLOW_EXECUTION_ENABLED=false
  export ARGUS_BACKTEST_WORKFLOW_TASK="$ARGUS_BACKTEST_WORKFLOW_TASK_DEFAULT"
  export ARGUS_BACKTEST_REAL_WORKFLOW_TASK="$ARGUS_BACKTEST_REAL_WORKFLOW_TASK_DEFAULT"
  export ARGUS_BACKTEST_JOBS_USER_RUNNING_LIMIT=1
  export ARGUS_BACKTEST_JOBS_USER_QUEUED_LIMIT=2
  export ARGUS_BACKTEST_JOBS_GLOBAL_RUNNING_LIMIT=5
  export ARGUS_BACKTEST_JOBS_GLOBAL_QUEUED_LIMIT=10
  export ARGUS_CONTEXT_PACKETS_ENABLED=false
  unset DATABASE_URL
}

argus_export_qa_mode() {
  export ARGUS_PERSISTENCE_MODE=supabase
  export ARGUS_DEV_MEMORY_FALLBACK=false
  export ARGUS_MARKET_DATA_PROVIDER_MODE=live_provider
  export ARGUS_CHECKPOINTER_MODE=postgres
  export ARGUS_MOCK_AUTH=false
  export ARGUS_BACKTEST_JOBS_SHADOW_ENABLED="${ARGUS_BACKTEST_JOBS_SHADOW_ENABLED:-false}"
  export ARGUS_BACKTEST_JOBS_DISPATCH_ENABLED="${ARGUS_BACKTEST_JOBS_DISPATCH_ENABLED:-false}"
  export ARGUS_BACKTEST_WORKFLOW_EXECUTION_ENABLED="${ARGUS_BACKTEST_WORKFLOW_EXECUTION_ENABLED:-false}"
  export ARGUS_BACKTEST_WORKFLOW_TASK="${ARGUS_BACKTEST_WORKFLOW_TASK:-$ARGUS_BACKTEST_WORKFLOW_TASK_DEFAULT}"
  export ARGUS_BACKTEST_REAL_WORKFLOW_TASK="${ARGUS_BACKTEST_REAL_WORKFLOW_TASK:-$ARGUS_BACKTEST_REAL_WORKFLOW_TASK_DEFAULT}"
  export ARGUS_BACKTEST_JOBS_USER_RUNNING_LIMIT="${ARGUS_BACKTEST_JOBS_USER_RUNNING_LIMIT:-1}"
  export ARGUS_BACKTEST_JOBS_USER_QUEUED_LIMIT="${ARGUS_BACKTEST_JOBS_USER_QUEUED_LIMIT:-2}"
  export ARGUS_BACKTEST_JOBS_GLOBAL_RUNNING_LIMIT="${ARGUS_BACKTEST_JOBS_GLOBAL_RUNNING_LIMIT:-5}"
  export ARGUS_BACKTEST_JOBS_GLOBAL_QUEUED_LIMIT="${ARGUS_BACKTEST_JOBS_GLOBAL_QUEUED_LIMIT:-10}"
  export ARGUS_CONTEXT_PACKETS_ENABLED="${ARGUS_CONTEXT_PACKETS_ENABLED:-true}"
  export DATABASE_URL="$SUPABASE_POSTGRES_SESSION_POOLER_URL"
}
