import { describe, expect, test } from "bun:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { I18nextProvider } from "react-i18next";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import ToolResultCard from "../components/chat/ToolResultCard";
import { shownToolInputs, toolCardStartsCollapsed, toolFactSourceText, type ToolResultCard as Card } from "../lib/tool-result-card";
import { translate } from "./support/i18n-instance";

/** Cards generated by scripts/dump_calculation_fixtures.py from the real declarations. */
const fixture = JSON.parse(
  readFileSync(join(import.meta.dir, "fixtures/calculation-cards.json"), "utf-8"),
) as { cards: Record<string, { card: Card }> };

describe("a computed answer's card under the prose", () => {
  for (const language of ["en", "es-419"] as const) {
    test(`starts collapsed with the answer and a toggle in ${language}`, async () => {
      const instance = await translate(language);
      const { card } = fixture.cards.time_value;
      expect(toolCardStartsCollapsed(card)).toBe(true);
      const html = renderToStaticMarkup(
        <I18nextProvider i18n={instance}><ToolResultCard card={card} onRecompute={async () => undefined} /></I18nextProvider>,
      );
      expect(html).toContain("data-tool-card-toggle");
      expect(html).toContain('aria-expanded="false"');
      expect(html).toContain(language === "en" ? "Show the numbers" : "Ver los números");
      expect(html).toContain("data-tool-answer");
      expect(html).not.toContain("data-tool-inputs");
      expect(html).not.toContain("—");
    });

    test(`opened, it shows only the inputs that drive the result and never a blank in ${language}`, async () => {
      const instance = await translate(language);
      const { card } = fixture.cards.time_value;
      const html = renderToStaticMarkup(
        <I18nextProvider i18n={instance}><ToolResultCard card={card} onRecompute={async () => undefined} defaultOpen /></I18nextProvider>,
      );
      const shown = shownToolInputs(card.presentation).map((input) => input.name);
      expect(shown.length).toBeGreaterThanOrEqual(3);
      expect(shown.length).toBeLessThanOrEqual(5);
      for (const name of shown) expect(html).toContain(`data-tool-input="${name}"`);
      expect(html).not.toContain('data-tool-input="payment"');
      expect(html).not.toContain(instance.t("tools.card.unknown"));
      expect(html).toContain(language === "en" ? "Hide the numbers" : "Ocultar los números");
    });

    test(`market data and an assumption name their true source in ${language}`, async () => {
      const instance = await translate(language);
      const t = instance.t.bind(instance);
      const price = { name: "price", label: { locale_key: "tools.calc.fields.price", interpolation_args: {} }, value: 150, unit: null };
      expect(toolFactSourceText({ ...price, source: { kind: "market_data", date: "2026-09-11" } }, t, language))
        .toContain(language === "en" ? "Argus market data" : "Datos de mercado de Argus");
      expect(toolFactSourceText({ ...price, source: { kind: "assumption" } }, t, language))
        .toBe(language === "en" ? "Assumed in the answer" : "Supuesto en la respuesta");
    });
  }

  test("a card that did not solve stays open so its fix is visible", () => {
    expect(toolCardStartsCollapsed(fixture.cards.time_value_payment_below_interest.card)).toBe(false);
  });
});
