import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import ReceiptBody from "../components/receipt/ReceiptBody";
import type { CalculationReceiptTurn, PublicReceiptDocument } from "../lib/public-receipt-turns";
import { receiptDocumentKind, receiptDocumentSupported } from "../lib/public-receipt-turns";
import { receiptCopy } from "../lib/receipt-copy";
import { receiptPresentations } from "../lib/receipt-presentation";
import { receiptPreviewFacts } from "../lib/receipt-preview-facts";
import { receiptRefusalText } from "../lib/receipt-selection";

// The turn is the backend projector's output, generated by
// scripts/dump_calculation_fixtures.py; never hand-written.
const fixture = JSON.parse(
  readFileSync(join(import.meta.dir, "fixtures/calculation-cards.json"), "utf-8"),
) as { receipt_turn: CalculationReceiptTurn };
const turn = fixture.receipt_turn;
const documentOf = (...turns: CalculationReceiptTurn[]): PublicReceiptDocument => ({ schema_version: 2, kind: "turns", turns });

describe.each(["en", "es-419"] as const)("a calculation receipt in %s", (language) => {
  const copy = receiptCopy(language);

  test("is a supported typed receipt kind", () => {
    expect(receiptDocumentSupported(documentOf(turn))).toBe(true);
    expect(receiptDocumentKind(documentOf(turn))).toBe("calculation");
  });

  test("presents the frozen answer, what Argus used with its page, and the notes", () => {
    const [entry] = receiptPresentations(documentOf(turn), null, language);
    expect(entry.title).toBe(turn.question);
    expect(entry.headline).toContain("24");
    expect(entry.neutralHeadline).toBe(true);
    expect(entry.plan?.heading).toBe(copy.calculation.used);
    expect(entry.plan?.rows).toHaveLength(turn.inputs.length);
    expect(entry.plan?.rows[0].exact).toContain("Apple quote");
    expect(entry.plan?.assumptions).toHaveLength(turn.notes.length);
    expect(entry.framing).toBe(copy.calculation.framing);
  });

  test("renders read-only with one public action and no recompute control", () => {
    const markup = renderToStaticMarkup(
      <ReceiptBody payload={documentOf(turn)} createdAt="2026-09-11T12:00:00Z" language={language} copy={copy} />,
    );
    expect(markup).toContain(turn.question);
    expect(markup).toContain(copy.calculation.used);
    expect(markup).toContain("Apple quote");
    expect(markup).toContain(copy.calculation.headline);
    expect(markup).not.toContain("<input");
    expect(markup).not.toContain("6.25");
    expect(markup.match(/href="\/"/g)).toHaveLength(1);
    expect(markup).not.toContain("—");
  });

  test("the preview card and the refusal reason read the calculation copy", () => {
    const facts = receiptPreviewFacts(documentOf(turn), language);
    expect(facts.title).toBe(turn.question);
    expect(facts.framing).toBe(copy.calculation.short);
    expect(facts.description).toContain(copy.calculation.short);
    expect(receiptRefusalText({ reason: "private_inputs" }, copy)).toBe(copy.selection.reasons.private_inputs);
  });
});
