import { useEffect, useRef, useState } from 'react';
import type { PlatformPageProps, Page } from '../../platform/types';
import { APIError, request, requestResponse } from '../../platform/client';
import { destinations } from '../../platform/navigation';
import { Modal, EvidenceLine, Money, Field } from '../../platform/ui';
import { actionsSchema, conversationSchema, detailSchema, historySchema, insightsSchema, noticeResultSchema, resultSchema, type Action, type Answer, type Check, type Conversation, type ConversationState, type Fact, type PageWindow } from './contracts';
import { copy, label } from './catalog';
import './assistant.css';

export type AssistantDrawerProps = Pick<PlatformPageProps,'locale'|'currency'|'onNavigate'|'onChanged'> & {page:Page;onClose:()=>void;revision?:number;initialConversationId?:string};

export function AssistantDrawer({locale,currency,page,onNavigate,onClose,onChanged,revision=0,initialConversationId}:AssistantDrawerProps) {
 const text=copy(locale);
 const destination=destinations.find(item=>item.id===page);
 const contextLabel=destination?(locale==='en'?destination.en:destination.es):page;
 const [actions,setActions]=useState<Action[]>([]);
 const [configured,setConfigured]=useState(false);
 const [history,setHistory]=useState<Conversation[]>([]);
 const [historyOffset,setHistoryOffset]=useState(0);
 const [historyPage,setHistoryPage]=useState<PageWindow>({total:0,limit:20,offset:0});
 const [answerPage,setAnswerPage]=useState<PageWindow>({total:0,limit:20,offset:0});
 const [state,setState]=useState<ConversationState>('active');
 const [conversation,setConversation]=useState<Conversation|null>(null);
 const [answers,setAnswers]=useState<Answer[]>([]);
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));
 const [message,setMessage]=useState('');
 const [title,setTitle]=useState('');
 const [rename,setRename]=useState(false);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [historyLoading,setHistoryLoading]=useState(true);
 const [notices,setNotices]=useState<Check[]>([]);
 const [reviewed,setReviewed]=useState(false);
 const [checks,setChecks]=useState<Check[]>([]);
 const epoch=useRef(0);
 useEffect(()=>{const controller=new AbortController();setHistoryLoading(true);Promise.all([request('/assistant/actions',actionsSchema,{signal:controller.signal}),request(`/assistant/conversations?state=${state}&offset=${historyOffset}`,historySchema,{signal:controller.signal})]).then(([catalog,list])=>{setActions(catalog.items);setConfigured(catalog.free_text_configured);setHistory(list.items);setHistoryPage(list);setError('');}).catch(error=>{if(error.name!=='AbortError')setError(text.error);}).finally(()=>{if(!controller.signal.aborted)setHistoryLoading(false);});return()=>controller.abort();},[state,historyOffset,revision,text.error]);
 useEffect(()=>{setReviewed(false);setNotices([]);setChecks([]);},[currency,month]);
 useEffect(()=>()=>{epoch.current++;},[]);
 useEffect(()=>{if(!initialConversationId)return;const controller=new AbortController();setBusy(true);request(`/assistant/conversations/${initialConversationId}`,detailSchema,{signal:controller.signal}).then(data=>{setConversation(data.conversation);setAnswers(data.answers);setAnswerPage(data);}).catch(error=>{if(error.name!=='AbortError')setError(text.error);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[initialConversationId,text.error]);
 const refresh=async()=>{const data=await request(`/assistant/conversations?state=${state}&offset=${historyOffset}`,historySchema);setHistory(data.items);setHistoryPage(data);};
 const run=async(action?:Action)=>{
  if(!action&&!message.trim()){setError(text.emptyQuestion);return;}
  const current=++epoch.current;setBusy(true);setError('');
  try{const result=await request('/assistant/ask',resultSchema,{method:'POST',body:JSON.stringify({...(action?{action}:{message:message.trim()}),parameters:{currency,month},page,locale,conversation_id:conversation?.id??null})});if(current!==epoch.current)return;
   if(result.status!=='answered'||!result.answer){setError(result.status==='unsupported'?text.unsupported:text.unavailable);return;}
   const detail=await request(`/assistant/conversations/${result.conversation_id}`,detailSchema);if(current!==epoch.current)return;setConversation(detail.conversation);setAnswers(detail.answers);setAnswerPage(detail);setMessage('');await refresh();onChanged();
  }catch(error){if(current===epoch.current)setError(error instanceof APIError&&['assistant_answer_too_large','assistant_fact_limit_exceeded','assistant_context_too_large'].includes(error.code)?text.answerTooLarge:text.error);}finally{if(current===epoch.current)setBusy(false);}
 };
 const open=async(id:string,offset=0,limit=10)=>{const current=++epoch.current;setBusy(true);setError('');try{const data=await request(`/assistant/conversations/${id}?limit=${limit}&offset=${offset}`,detailSchema);if(current===epoch.current){setConversation(data.conversation);setAnswers(data.answers);setAnswerPage(data);setRename(false);}}catch(error){setError(error instanceof APIError&&error.code==='assistant_window_too_large'?text.windowTooLarge:text.error);if(error instanceof APIError&&error.code==='assistant_window_too_large'&&limit>1){await open(id,offset,1);}}finally{if(current===epoch.current)setBusy(false);}};
 const update=async(change:{title?:string;state?:ConversationState;saved?:boolean})=>{if(!conversation)return;setBusy(true);setError('');try{const result=await request(`/assistant/conversations/${conversation.id}`,conversationSchema,{method:'PATCH',body:JSON.stringify(change)});setConversation(result);setRename(false);await refresh();onChanged();}catch{setError(text.error);}finally{setBusy(false);}};
 const exportSnapshot=async()=>{if(!conversation)return;setBusy(true);setError('');try{const result=await requestResponse(`/assistant/conversations/${conversation.id}/export`);const blob=await result.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='clara-conversation.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}catch(error){setError(error instanceof APIError&&error.code==='assistant_export_too_large'?text.exportTooLarge:text.error);}finally{setBusy(false);}};
 const navigate=(fact:Fact)=>{onNavigate(fact.target.page,fact.target.query);onClose();};
 const loadReview=async()=>{setBusy(true);setError('');try{const data=await request(`/insights?currency=${currency}&month=${month}`,insightsSchema);setNotices(data.notices);setChecks(data.checks);setReviewed(true);}catch{setError(text.error);}finally{setBusy(false);}};
 const noticeState=async(notice:Check,next:'read'|'dismissed')=>{setBusy(true);try{await request(`/insights/${notice.id}?currency=${currency}&month=${month}`,noticeResultSchema,{method:'PATCH',body:JSON.stringify({state:next})});setNotices(previous=>previous.map(item=>item.id===notice.id?{...item,state:next}:item));onChanged();}catch{setError(text.error);}finally{setBusy(false);}};
 const factView=(fact:Fact,index:number)=><div className="ca-fact" key={`${fact.key}-${index}`}><div><span>{fact.record_name&&<strong>{fact.record_name} · </strong>}{label(text.facts,fact.key)}</span>{fact.unit==='money'&&fact.currency?<Money amount={fact.value} currency={fact.currency} locale={locale}/>:<strong>{fact.value}{fact.unit==='percent'?'%':''}</strong>}</div>{fact.notes.includes('partial_unpriced_holdings')&&<p>{text.partial}</p>}<EvidenceLine evidence={fact.source} locale={locale}/><button type="button" className="p-text-button" onClick={()=>navigate(fact)}>{text.source}</button></div>;
 return <Modal title={text.title} onClose={onClose}><div className="ca-drawer" data-context-page={page}>
  <p className="p-muted">{text.intro}</p><p className="p-muted">{text.shared}</p><p className="p-muted">{text.context}: {contextLabel}</p>
  <div className="ca-toolbar"><Field label={text.month}><input type="month" value={month} onChange={event=>setMonth(event.target.value)} required disabled={busy}/></Field><span>{text.currency}: <strong>{currency}</strong></span><button className="p-button-secondary" type="button" disabled={busy} onClick={()=>{epoch.current++;setConversation(null);setAnswers([]);setRename(false);setError('');}}>{text.newChat}</button></div>
  <details className="ca-history"><summary>{text.history}</summary><label>{text.history}<select value={state} onChange={event=>{setState(event.target.value as ConversationState);setHistoryOffset(0);}}>{(['active','archived','trashed'] as const).map(value=><option key={value} value={value}>{text[value]}</option>)}</select></label>{historyLoading?<p role="status">{text.loading}</p>:history.length===0?<p>{text.empty}</p>:<ul>{history.map(item=><li key={item.id}><button className="p-button-secondary" type="button" disabled={busy} onClick={()=>open(item.id)}>{label(text.actions,item.title)} {item.saved?`· ${text.saved}`:''}</button></li>)}</ul>}<div className="ca-toolbar"><button className="p-button-secondary" disabled={busy||historyLoading||historyPage.offset===0} onClick={()=>setHistoryOffset(Math.max(0,historyPage.offset-historyPage.limit))}>{text.previous}</button><span>{text.total}: {historyPage.total}</span><button className="p-button-secondary" disabled={busy||historyLoading||historyPage.offset+historyPage.limit>=historyPage.total} onClick={()=>setHistoryOffset(historyPage.offset+historyPage.limit)}>{text.next}</button></div></details>
  {conversation&&<section className="ca-conversation"><h3>{label(text.actions,conversation.title)}</h3><button className="p-button-secondary" type="button" disabled={busy} onClick={exportSnapshot}>{locale==='en'?'Download local snapshot (JSON)':'Descargar copia local (JSON)'}</button><div className="ca-toolbar"><button className="p-button-secondary" type="button" disabled={busy} onClick={()=>update({saved:!conversation.saved})}>{conversation.saved?text.unsave:text.save}</button><button className="p-button-secondary" type="button" disabled={busy} onClick={()=>{setTitle(conversation.title);setRename(!rename);}}>{text.rename}</button>{conversation.state==='active'?<button className="p-button-secondary" type="button" disabled={busy} onClick={()=>update({state:'archived'})}>{text.archive}</button>:<button className="p-button-secondary" type="button" disabled={busy} onClick={()=>update({state:'active'})}>{text.restore}</button>}{conversation.state!=='trashed'&&<button className="p-button-secondary" type="button" disabled={busy} onClick={()=>update({state:'trashed'})}>{text.trash}</button>}</div>{rename&&<form onSubmit={event=>{event.preventDefault();if(title.trim())void update({title:title.trim()});}}><Field label={text.titleLabel}><input value={title} onChange={event=>setTitle(event.target.value)} maxLength={120} required/></Field><button className="p-button-secondary" disabled={busy||!title.trim()}>{text.apply}</button></form>}</section>}
  <section className="ca-answers" aria-live="polite">{conversation&&<div className="ca-toolbar"><button className="p-button-secondary" disabled={busy||answerPage.offset===0} onClick={()=>open(conversation.id,Math.max(0,answerPage.offset-answerPage.limit),answerPage.limit)}>{text.newer}</button><span>{text.window}: {Math.min(answerPage.total,answerPage.offset+1)}–{Math.min(answerPage.total,answerPage.offset+answerPage.limit)} / {answerPage.total}</span><button className="p-button-secondary" disabled={busy||answerPage.offset+answerPage.limit>=answerPage.total} onClick={()=>open(conversation.id,answerPage.offset+answerPage.limit,answerPage.limit)}>{text.older}</button></div>}{answers.map(answer=><article className="ca-answer" key={answer.id}><h3>{text.actions[answer.action]}</h3><p className="p-muted">{text.snapshot} · {new Date(answer.created_at).toLocaleString(locale)}</p><p className="p-muted">{text.snapshotHelp}</p>{answer.facts.length?answer.facts.map(factView):<p>{text.noFacts}</p>}</article>)}</section>
  {(!conversation||conversation.state==='active')&&<><h3>{text.prepared}</h3><div className="ca-actions">{actions.map(action=><button className="p-button-secondary" type="button" key={action} disabled={busy||!month} onClick={()=>run(action)}>{text.actions[action]}</button>)}</div>{!configured&&<p className="p-muted">{text.unavailable}</p>}<form className="ca-question" onSubmit={event=>{event.preventDefault();void run();}}><Field label={text.prompt}><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder={text.placeholder} maxLength={4000} rows={3} disabled={busy}/></Field><button type="submit" className="p-button" disabled={busy||!month||!message.trim()}>{busy?text.loading:text.ask}</button></form></>}
  {error&&<p role="alert" className="p-error">{error}</p>}
  <section className="ca-review"><h3>{text.review}</h3><details><summary>{text.rubric}</summary><p>{text.rubricText}</p></details><button className="p-button-secondary" type="button" onClick={loadReview} disabled={busy||!month}>{text.review}</button>{reviewed&&<>{checks.length===0?<p>{text.noChecks}</p>:<ul className="ca-checks">{checks.map(check=><li key={check.id}>{label(text.notices,check.code)}: {check.triggered?text.triggered:text.passed}</li>)}</ul>}{notices.filter(notice=>notice.state!=='dismissed').length===0&&<p>{text.noNotices}</p>}{notices.filter(notice=>notice.state!=='dismissed').map(notice=><article key={notice.id}><h4>{label(text.notices,notice.code)}</h4>{factView(notice.fact,0)}<div className="ca-toolbar">{notice.state==='read'?<span>{text.readState}</span>:<button className="p-button-secondary" disabled={busy} onClick={()=>noticeState(notice,'read')}>{text.read}</button>}<button className="p-button-secondary" disabled={busy} onClick={()=>noticeState(notice,'dismissed')}>{text.dismiss}</button></div></article>)}</>}</section>
 </div></Modal>;
}
