const es = {
 previous:'Anterior',next:'Siguiente',older:'Respuestas anteriores',newer:'Respuestas recientes',total:'Total',window:'Ventana de respuestas',exportTooLarge:'Esta exportación supera el límite. Descarga una conversación más pequeña o revisa las respuestas por páginas.',windowTooLarge:'Esta ventana es demasiado grande. Abre una respuesta a la vez.',answerTooLarge:'Esta consulta contiene demasiados registros. Reduce el período o la moneda antes de volver a intentarlo.',
 title:'Clara, tus registros en contexto', intro:'Revisa las cifras de tus registros y abre su fuente. Las respuestas guardadas conservan lo que viste en ese momento.',
 shared:'Estas conversaciones se comparten con tu hogar. Los datos de ejemplo son simulados.', partial:'Total parcial: faltan precios para algunos activos.', context:'Página actual', newChat:'Nueva conversación', history:'Historial', empty:'Todavía no hay conversaciones.', noFacts:'No hay registros para esta moneda y período.', month:'Mes', currency:'Moneda', ask:'Consultar', placeholder:'Escribe una pregunta sobre tus registros', prompt:'Tu pregunta', prepared:'Consultas preparadas', unavailable:'La interpretación de texto no está disponible. Puedes usar las consultas preparadas.', unsupported:'Esta consulta no corresponde a las acciones disponibles. Elige una consulta preparada.', error:'No se pudo completar la consulta. Inténtalo de nuevo.', loading:'Cargando…', saved:'Guardada', save:'Guardar', unsave:'Quitar de guardadas', rename:'Renombrar', titleLabel:'Título', apply:'Aplicar', archive:'Archivar', trash:'Mover a papelera', restore:'Restaurar', active:'Activas', archived:'Archivadas', trashed:'Papelera', source:'Abrir registros', snapshot:'Respuesta guardada', snapshotHelp:'Estas cifras pertenecen a la fecha de esta respuesta. Una nueva consulta usa los registros actuales.', review:'Revisión de registros', rubric:'Cómo se revisa', rubricText:'Se compara gasto con ingreso, gasto real con el límite de cada presupuesto y dinero asignado con la meta. Cada señal muestra el valor y su fuente. No se calcula una puntuación financiera.', noNotices:'No hay señales pendientes para estos registros. Esto no evalúa toda tu situación financiera.', read:'Marcar leída', dismiss:'Descartar', readState:'Leída', allClear:'Las comprobaciones disponibles no activaron señales.', triggered:'Señal activa', passed:'Sin señal', noChecks:'No hay registros suficientes para estas comprobaciones.', emptyQuestion:'Escribe una pregunta o elige una consulta preparada.', semantic:'Interpretación de texto', recordExplanation:'Consulta calculada desde tus registros',
 actions:{spending:'¿Cómo fue mi gasto?',budget_review:'Revisar mis presupuestos',net_worth:'Ver mi patrimonio',goal_progress:'Revisar mis metas',portfolio_review:'Revisar mis inversiones',credit_review:'Revisar mi crédito'},
 facts:{credit_score:'Puntuación de crédito',utilization_pct:'Uso del crédito',income:'Ingreso registrado',spending:'Gasto registrado',net:'Ingreso menos gasto',assets:'Activos',liabilities:'Deudas',net_worth:'Patrimonio',limit:'Límite del presupuesto',actual:'Gasto real',remaining:'Restante',target_amount:'Meta',allocated:'Asignado',linked_accounts:'Cuentas vinculadas',priced_alternatives:'Activos alternativos con precio',portfolio_value:'Valor del portafolio',balance:'Saldo',credit_limit:'Límite de crédito',minimum_payment:'Pago mínimo'},
 notices:{spending_exceeds_income:'El gasto registrado supera al ingreso',budget_exceeded:'El gasto supera el presupuesto guardado',goal_fully_allocated:'La meta tiene su importe asignado'},
};
const en: typeof es = {
 previous:'Previous',next:'Next',older:'Older answers',newer:'Newer answers',total:'Total',window:'Answer window',exportTooLarge:'This export exceeds the limit. Download a smaller conversation or review answers by page.',windowTooLarge:'This window is too large. Open one answer at a time.',answerTooLarge:'This question includes too many records. Narrow the period or currency before trying again.',
 title:'Clara, your records in context', intro:'Review the figures in your records and open their sources. Saved answers preserve what you saw at that time.',
 shared:'These conversations are shared with your household. Example data is simulated.', partial:'Partial total: some assets have no price.', context:'Current page',newChat:'New conversation',history:'History',empty:'No conversations yet.',noFacts:'No records for this currency and period.',month:'Month',currency:'Currency',ask:'Ask',placeholder:'Ask a question about your records',prompt:'Your question',prepared:'Prepared questions',unavailable:'Text interpretation is unavailable. You can use the prepared questions.',unsupported:'This question does not match the available actions. Choose a prepared question.',error:'The request could not be completed. Please try again.',loading:'Loading…',saved:'Saved',save:'Save',unsave:'Remove from saved',rename:'Rename',titleLabel:'Title',apply:'Apply',archive:'Archive',trash:'Move to trash',restore:'Restore',active:'Active',archived:'Archived',trashed:'Trash',source:'Open records',snapshot:'Saved answer',snapshotHelp:'These figures belong to the date of this answer. A new question uses current records.',review:'Record review',rubric:'How this review works',rubricText:'Recorded spending is compared with income, actual spending with each saved budget limit, and allocated money with each goal. Every signal shows its value and source. No financial score is calculated.',noNotices:'No pending signals for these records. This does not assess your entire financial situation.',read:'Mark read',dismiss:'Dismiss',readState:'Read',allClear:'The available checks did not trigger signals.',triggered:'Active signal',passed:'No signal',noChecks:'There are not enough records for these checks.',emptyQuestion:'Write a question or choose a prepared question.',semantic:'Text interpretation',recordExplanation:'Computed query from your records',
 actions:{spending:'How much did I spend?',budget_review:'Review my budgets',net_worth:'See my net worth',goal_progress:'Review my goals',portfolio_review:'Review my investments',credit_review:'Review my credit'},
 facts:{credit_score:'Credit score',utilization_pct:'Credit utilization',income:'Recorded income',spending:'Recorded spending',net:'Income less spending',assets:'Assets',liabilities:'Liabilities',net_worth:'Net worth',limit:'Budget limit',actual:'Actual spending',remaining:'Remaining',target_amount:'Target',allocated:'Allocated',linked_accounts:'Linked accounts',priced_alternatives:'Priced alternative assets',portfolio_value:'Portfolio value',balance:'Balance',credit_limit:'Credit limit',minimum_payment:'Minimum payment'},
 notices:{spending_exceeds_income:'Recorded spending exceeds income',budget_exceeded:'Spending exceeds the saved budget',goal_fully_allocated:'The goal amount is allocated'},
};
export const copy = (locale: string) => locale === 'en' ? en : es;
export function label(map: Record<string,string>, key: string): string {return map[key] ?? key;}
