import { z } from 'zod';
import { evidenceSchema } from '../../platform/types';
export const actionSchema = z.enum(['spending','budget_review','net_worth','goal_progress','portfolio_review','credit_review']);
export type Action = z.infer<typeof actionSchema>;
export const stateSchema = z.enum(['active','archived','trashed']);
export type ConversationState = z.infer<typeof stateSchema>;
export const targetSchema = z.object({page:z.enum(['spending','budgets','accounts','goals','investments','credit','transactions']),query:z.record(z.string(),z.string()),record_ids:z.array(z.string())});
export const factSchema = z.object({key:z.string(),value:z.string(),unit:z.enum(['money','percent','count']),currency:z.string().nullable(),record_name:z.string().nullable(),notes:z.array(z.enum(['partial_unpriced_holdings'])),source:evidenceSchema,target:targetSchema});
export const answerSchema = z.object({id:z.string(),conversation_id:z.string(),action:actionSchema,parameters:z.object({currency:z.string(),month:z.string()}),created_at:z.string(),code:z.enum(['grounded_records','no_records']),interpretation:z.enum(['prepared','semantic']),facts:z.array(factSchema)});
export type Answer = z.infer<typeof answerSchema>;
export type Fact = z.infer<typeof factSchema>;
export const conversationSchema = z.object({id:z.string(),household_id:z.string(),user_id:z.string(),title:z.string(),state:stateSchema,saved:z.boolean(),created_at:z.string(),updated_at:z.string()});
export type Conversation = z.infer<typeof conversationSchema>;
export const pageSchema = z.object({total:z.number().int().nonnegative(),limit:z.number().int().positive(),offset:z.number().int().nonnegative()});
export type PageWindow = z.infer<typeof pageSchema>;
export const historySchema = pageSchema.extend({items:z.array(conversationSchema)});
export const detailSchema = pageSchema.extend({conversation:conversationSchema,messages:z.array(z.object({id:z.string(),role:z.string(),text:z.string().nullable().optional(),action:actionSchema.optional(),answer_id:z.string().optional(),created_at:z.string()})),answers:z.array(answerSchema)});
export const resultSchema = z.object({status:z.enum(['answered','model_unavailable','unsupported']),answer:answerSchema.nullable(),conversation_id:z.string().nullable()});
export const actionsSchema = z.object({items:z.array(actionSchema),free_text_configured:z.boolean()});
export const checkSchema = z.object({id:z.string(),code:z.string(),triggered:z.boolean(),state:z.enum(['unread','read','dismissed']),fact:factSchema});
export type Check = z.infer<typeof checkSchema>;
export const insightsSchema = z.object({as_of:z.string(),rubric:z.array(z.string()),checks:z.array(checkSchema),notices:z.array(checkSchema)});
export const noticeResultSchema = z.object({id:z.string(),state:z.enum(['unread','read','dismissed'])});
