import type { Locale } from '../../platform/types';
import type { ScenarioTemplateId } from './contracts';

const catalog = {
  'es-419': {
    common: {
      add: 'Agregar',
      archive: 'Archivar',
      cancel: 'Cancelar',
      close: 'Cerrar',
      edit: 'Editar',
      loading: 'Cargando registros…',
      retry: 'Reintentar',
      save: 'Guardar',
      saving: 'Guardando…',
      source: 'Fuente',
    },
    budgets: {
      title: 'Presupuestos',
      description: 'Compara el gasto registrado con el límite de cada categoría.',
      month: 'Mes',
      add: 'Crear presupuesto',
      empty: 'No hay presupuestos para este mes',
      emptyDescription: 'Crea un límite por categoría para comparar el gasto ya registrado.',
      category: 'Categoría',
      currency: 'Moneda',
      limit: 'Límite',
      actual: 'Gastado',
      remaining: 'Restante',
      exceeded: 'Superado',
      actions: 'Acciones',
      createTitle: 'Crear presupuesto',
      editTitle: 'Editar presupuesto',
      limitHelp: 'Cambiar el límite no modifica los movimientos registrados.',
    },
    bills: {
      title: 'Pagos recurrentes',
      description: 'Planifica vencimientos y registra pagos locales sin mover dinero real.',
      add: 'Agregar pago recurrente',
      empty: 'No hay pagos recurrentes',
      emptyDescription: 'Agrega un calendario para ver su próximo vencimiento.',
      name: 'Nombre',
      account: 'Cuenta',
      amount: 'Monto',
      cadence: 'Frecuencia',
      nextDue: 'Próximo vencimiento',
      status: 'Estado',
      actions: 'Acciones',
      createTitle: 'Agregar pago recurrente',
      editTitle: 'Editar pago recurrente',
      anchorDate: 'Fecha inicial',
      pause: 'Pausar',
      resume: 'Reanudar',
      skip: 'Omitir esta fecha',
      pay: 'Registrar como pagado',
      archive: 'Archivar calendario',
      localOnly: 'Registrar como pagado crea un movimiento local una sola vez.',
      missingAccounts: 'Primero agrega una cuenta demo para asociar el pago.',
    },
    goals: {
      title: 'Metas',
      description: 'Define un objetivo y reserva partes de saldos registrados sin transferir dinero.',
      add: 'Crear meta',
      empty: 'No hay metas guardadas',
      emptyDescription: 'Crea una meta con monto, fecha y aporte mensual.',
      target: 'Objetivo',
      date: 'Fecha objetivo',
      monthly: 'Aporte mensual',
      progress: 'Progreso reservado',
      allocated: 'Reservado',
      remaining: 'Pendiente',
      actions: 'Acciones',
      createTitle: 'Crear meta',
      editTitle: 'Editar meta',
      name: 'Nombre',
      currency: 'Moneda',
      allocation: 'Asignar cuentas',
      allocationTitle: 'Asignación de cuentas',
      allocationHelp: 'Una asignación es un plan. No mueve dinero y no puede reservar el mismo saldo dos veces.',
      allocationCount: '{count} cuentas asignadas',
      currentBalance: 'Saldo actual',
      accountUnavailable: 'Cuenta archivada o no disponible',
      noEligibleAccounts: 'No hay cuentas activas en la moneda de esta meta.',
      underfunded: 'La asignación supera el saldo actual de una cuenta.',
      archiveTitle: 'Archivar meta',
      archiveBody: 'La meta dejará de aparecer entre las metas activas. Los saldos de las cuentas no cambian.',
      confirmArchive: 'Archivar meta',
    },
    scenarios: {
      title: 'Escenarios',
      description: 'Cambia supuestos visibles, calcula el flujo y guarda recibos que nunca se modifican.',
      template: 'Tipo de escenario',
      assumptions: 'Supuestos editables',
      name: 'Nombre del escenario',
      namePlaceholder: 'Ej. Retiro base',
      currency: 'Moneda',
      initialBalance: 'Saldo inicial',
      contribution: 'Aporte mensual',
      withdrawal: 'Retiro mensual',
      horizon: 'Horizonte en años',
      returnRate: 'Rendimiento anual supuesto (%)',
      inflation: 'Inflación anual supuesta (%)',
      fee: 'Costo anual supuesto (%)',
      contributionStart: 'Inicio de aportes, mes',
      contributionEnd: 'Fin de aportes, mes',
      withdrawalStart: 'Inicio de retiros, mes',
      withdrawalEnd: 'Fin de retiros, mes',
      optionalEnd: 'Déjalo vacío para usar el final del horizonte.',
      timing: 'Momento del flujo mensual',
      timingBegin: 'Al inicio del mes',
      timingEnd: 'Al final del mes',
      calculate: 'Calcular',
      calculating: 'Calculando…',
      save: 'Guardar recibo',
      savedSuccess: 'Recibo guardado. Sus supuestos y resultado ya no cambian.',
      result: 'Resultado calculado',
      endingBalance: 'Saldo final',
      realEndingBalance: 'Saldo final ajustado por inflación',
      contributions: 'Aportes totales',
      withdrawals: 'Retiros cubiertos',
      fees: 'Costos totales',
      shortfall: 'Retiros no cubiertos',
      depletion: 'Mes de agotamiento',
      noDepletion: 'No se agota en este escenario',
      yearly: 'Resultado por año',
      year: 'Año',
      nominal: 'Saldo nominal',
      real: 'Saldo real',
      method: 'Método de cálculo',
      illustrative: 'Resultado ilustrativo basado en los supuestos visibles. No es una promesa ni una recomendación.',
      saved: 'Escenarios guardados',
      empty: 'No hay escenarios guardados',
      emptyDescription: 'Calcula un escenario y guárdalo para conservar sus supuestos y resultado.',
      compare: 'Comparar recibos',
      before: 'Antes',
      after: 'Después',
      runCompare: 'Comparar',
      change: 'Cambio en saldo final',
      chooseTwo: 'Elige dos recibos guardados en la misma moneda.',
      immutable: 'Este recibo conserva los supuestos y el resultado originales.',
      newVersion: 'Crear variante',
      previousPage: 'Anterior',
      nextPage: 'Siguiente',
      pageCount: 'Mostrando {start} a {end} de {total}',
    },
    errors: {
      generic: 'No se pudo completar la acción. Inténtalo de nuevo.',
      invalidResponse: 'La respuesta no coincide con el contrato esperado.',
      network: 'No se pudo conectar con el servicio local.',
      required: 'Completa este campo.',
      invalidNumber: 'Escribe un número válido.',
      positive: 'Usa un valor mayor que cero.',
      accountRequired: 'Elige una cuenta.',
      nameRequired: 'Escribe un nombre.',
      currencyRequired: 'Escribe un código de moneda.',
      permission: 'Tu rol puede consultar estos datos, pero no modificarlos.',
      overbooked: 'La asignación supera el saldo disponible o ya reservado.',
      currencyMismatch: 'Las monedas deben coincidir para completar esta acción.',
    },
  },
  en: {
    common: {
      add: 'Add',
      archive: 'Archive',
      cancel: 'Cancel',
      close: 'Close',
      edit: 'Edit',
      loading: 'Loading records…',
      retry: 'Retry',
      save: 'Save',
      saving: 'Saving…',
      source: 'Source',
    },
    budgets: {
      title: 'Budgets',
      description: 'Compare recorded spending with each category limit.',
      month: 'Month',
      add: 'Create budget',
      empty: 'No budgets for this month',
      emptyDescription: 'Create a category limit to compare against recorded spending.',
      category: 'Category',
      currency: 'Currency',
      limit: 'Limit',
      actual: 'Spent',
      remaining: 'Remaining',
      exceeded: 'Over limit',
      actions: 'Actions',
      createTitle: 'Create budget',
      editTitle: 'Edit budget',
      limitHelp: 'Changing the limit does not modify recorded transactions.',
    },
    bills: {
      title: 'Recurring bills',
      description: 'Plan due dates and record local payments without moving real money.',
      add: 'Add recurring bill',
      empty: 'No recurring bills',
      emptyDescription: 'Add a schedule to see its next due date.',
      name: 'Name',
      account: 'Account',
      amount: 'Amount',
      cadence: 'Cadence',
      nextDue: 'Next due',
      status: 'Status',
      actions: 'Actions',
      createTitle: 'Add recurring bill',
      editTitle: 'Edit recurring bill',
      anchorDate: 'Start date',
      pause: 'Pause',
      resume: 'Resume',
      skip: 'Skip this date',
      pay: 'Record as paid',
      archive: 'Archive schedule',
      localOnly: 'Recording a payment creates one local transaction.',
      missingAccounts: 'Add a demo account before linking a recurring bill.',
    },
    goals: {
      title: 'Goals',
      description: 'Set a target and reserve parts of recorded balances without transferring money.',
      add: 'Create goal',
      empty: 'No saved goals',
      emptyDescription: 'Create a goal with an amount, date, and monthly contribution.',
      target: 'Target',
      date: 'Target date',
      monthly: 'Monthly contribution',
      progress: 'Reserved progress',
      allocated: 'Allocated',
      remaining: 'Remaining',
      actions: 'Actions',
      createTitle: 'Create goal',
      editTitle: 'Edit goal',
      name: 'Name',
      currency: 'Currency',
      allocation: 'Allocate accounts',
      allocationTitle: 'Account allocation',
      allocationHelp: 'An allocation is a plan. It does not move money and cannot reserve the same balance twice.',
      allocationCount: '{count} allocated accounts',
      currentBalance: 'Current balance',
      accountUnavailable: 'Archived or unavailable account',
      noEligibleAccounts: 'There are no active accounts in this goal currency.',
      underfunded: 'An allocation is higher than an account’s current balance.',
      archiveTitle: 'Archive goal',
      archiveBody: 'The goal will leave the active list. Account balances will not change.',
      confirmArchive: 'Archive goal',
    },
    scenarios: {
      title: 'Scenarios',
      description: 'Change visible assumptions, calculate cash flow, and save receipts that never change.',
      template: 'Scenario type',
      assumptions: 'Editable assumptions',
      name: 'Scenario name',
      namePlaceholder: 'Example: Retirement baseline',
      currency: 'Currency',
      initialBalance: 'Initial balance',
      contribution: 'Monthly contribution',
      withdrawal: 'Monthly withdrawal',
      horizon: 'Horizon in years',
      returnRate: 'Assumed annual return (%)',
      inflation: 'Assumed annual inflation (%)',
      fee: 'Assumed annual fee (%)',
      contributionStart: 'Contribution start month',
      contributionEnd: 'Contribution end month',
      withdrawalStart: 'Withdrawal start month',
      withdrawalEnd: 'Withdrawal end month',
      optionalEnd: 'Leave blank to use the end of the horizon.',
      timing: 'Monthly cash flow timing',
      timingBegin: 'Beginning of month',
      timingEnd: 'End of month',
      calculate: 'Calculate',
      calculating: 'Calculating…',
      save: 'Save receipt',
      savedSuccess: 'Receipt saved. Its assumptions and result will not change.',
      result: 'Calculated result',
      endingBalance: 'Ending balance',
      realEndingBalance: 'Inflation-adjusted ending balance',
      contributions: 'Total contributions',
      withdrawals: 'Funded withdrawals',
      fees: 'Total fees',
      shortfall: 'Unfunded withdrawals',
      depletion: 'Depletion month',
      noDepletion: 'Does not deplete in this scenario',
      yearly: 'Yearly result',
      year: 'Year',
      nominal: 'Nominal balance',
      real: 'Real balance',
      method: 'Calculation method',
      illustrative: 'Illustrative result based on the visible assumptions. It is not a promise or recommendation.',
      saved: 'Saved scenarios',
      empty: 'No saved scenarios',
      emptyDescription: 'Calculate and save a scenario to preserve its assumptions and result.',
      compare: 'Compare receipts',
      before: 'Before',
      after: 'After',
      runCompare: 'Compare',
      change: 'Ending balance change',
      chooseTwo: 'Choose two saved receipts in the same currency.',
      immutable: 'This receipt keeps its original assumptions and result.',
      newVersion: 'Create variation',
      previousPage: 'Previous',
      nextPage: 'Next',
      pageCount: 'Showing {start} to {end} of {total}',
    },
    errors: {
      generic: 'The action could not be completed. Try again.',
      invalidResponse: 'The response does not match the expected contract.',
      network: 'The local service could not be reached.',
      required: 'Complete this field.',
      invalidNumber: 'Enter a valid number.',
      positive: 'Use a value greater than zero.',
      accountRequired: 'Choose an account.',
      nameRequired: 'Enter a name.',
      currencyRequired: 'Enter a currency code.',
      permission: 'Your role can view this data but cannot change it.',
      overbooked: 'The allocation exceeds the available or already reserved balance.',
      currencyMismatch: 'Currencies must match to complete this action.',
    },
  },
} as const;

export function planningCopy(locale: Locale): (typeof catalog)['en'] {
  return catalog[locale] as (typeof catalog)['en'];
}

const categories: Record<string, { 'es-419': string; en: string }> = {
  groceries: { 'es-419': 'Supermercado', en: 'Groceries' },
  dining: { 'es-419': 'Restaurantes', en: 'Dining' },
  housing: { 'es-419': 'Vivienda', en: 'Housing' },
  transport: { 'es-419': 'Transporte', en: 'Transport' },
  utilities: { 'es-419': 'Servicios', en: 'Utilities' },
  health: { 'es-419': 'Salud', en: 'Health' },
  shopping: { 'es-419': 'Compras', en: 'Shopping' },
  entertainment: { 'es-419': 'Entretenimiento', en: 'Entertainment' },
  travel: { 'es-419': 'Viajes', en: 'Travel' },
  education: { 'es-419': 'Educación', en: 'Education' },
  insurance: { 'es-419': 'Seguros', en: 'Insurance' },
  other: { 'es-419': 'Otros', en: 'Other' },
  income: { 'es-419': 'Ingresos', en: 'Income' },
  transfer: { 'es-419': 'Transferencias', en: 'Transfers' },
};

export function categoryLabel(category: string, locale: Locale): string {
  return categories[category]?.[locale] ?? category.replaceAll('_', ' ');
}

const scenarioTemplates: Record<ScenarioTemplateId, { 'es-419': string; en: string }> = {
  home: { 'es-419': 'Vivienda', en: 'Home' },
  kids: { 'es-419': 'Hijos', en: 'Kids' },
  job: { 'es-419': 'Cambio de trabajo', en: 'Job change' },
  move: { 'es-419': 'Mudanza', en: 'Move' },
  marriage: { 'es-419': 'Matrimonio', en: 'Marriage' },
  retirement: { 'es-419': 'Retiro', en: 'Retirement' },
  sabbatical: { 'es-419': 'Año sabático', en: 'Sabbatical' },
};

export function scenarioTemplateLabel(template: ScenarioTemplateId, locale: Locale): string {
  return scenarioTemplates[template][locale];
}

const cadence: Record<string, { 'es-419': string; en: string }> = {
  weekly: { 'es-419': 'Semanal', en: 'Weekly' },
  monthly: { 'es-419': 'Mensual', en: 'Monthly' },
  quarterly: { 'es-419': 'Trimestral', en: 'Quarterly' },
  yearly: { 'es-419': 'Anual', en: 'Yearly' },
};

export function cadenceLabel(value: string, locale: Locale): string {
  return cadence[value]?.[locale] ?? value;
}

const status: Record<string, { 'es-419': string; en: string }> = {
  active: { 'es-419': 'Activo', en: 'Active' },
  paused: { 'es-419': 'Pausado', en: 'Paused' },
  archived: { 'es-419': 'Archivado', en: 'Archived' },
};

export function statusLabel(value: string, locale: Locale): string {
  return status[value]?.[locale] ?? value;
}
