#!/usr/bin/env python3
"""Rebuild or verify Clara's pinned, side-effect-free Argus calculation core."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections.abc import Callable
from pathlib import Path

SOURCE_REVISION = "5430d98d61d815e6c4a2bed60213b411a2bb875e"
REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "money-view" / "server" / "argus_core"
GENERATED_HEADER = (
    "# Generated by scripts/sync_argus_core.py.\n"
    f"# Source revision: {SOURCE_REVISION}; do not edit by hand.\n"
)
LOCAL_PYTHON_FILES = frozenset({"__init__.py", "research_contracts.py"})

# A changed canonical file requires an explicit revision/hash review before it can
# enter the local app. The generated output then proves the reviewed adapters were
# applied to exactly that source.
SOURCE_HASHES = {
    "src/argus/domain/tool_declaration.py": "815494d3fd5b3e66649f0e2e599b32fea7a1c2d9a0256d7f0c4328234e904388",
    "src/argus/domain/tool_contracts.py": "2de8af20aa10d5daf93cab875a4d80cc3c68a1f93ad034da5d97ce0536fab9ae",
    "src/argus/domain/calculations/__init__.py": "299b8c07e2ea3bbed6fbed3bb78174e31486480cf04774320efbb4dcbeca4041",
    "src/argus/domain/calculations/_shared.py": "419c601b7f172da220e4f319379da473a69eaf9dfd63b743220be888201a327d",
    "src/argus/domain/calculations/answer_request.py": "5da4918a39ada214632046cbf8d3b5ca50c0bc205e0b4114f3e4414479e9fc9f",
    "src/argus/domain/calculations/bond_value.py": "c32d8cfc8f4cf8da13e38beb69680512089935cbfcde3befacd053c23b0e25a0",
    "src/argus/domain/calculations/debt_to_income.py": "61a33da81ed751d78b1fb915a03804a5fe34afff63ca79555d732ec7d41c0d35",
    "src/argus/domain/calculations/discounted_cash_flow.py": "5374797a066a0c964a0dbf0b5c12e1d8a0160d19bbf1b7c17d3ece07a08a9bba",
    "src/argus/domain/calculations/effective_rate.py": "aef5746f45395b5d8b6d4c42240042b41a09949954228c76b56375fdb4ac4716",
    "src/argus/domain/calculations/expense_ratio.py": "5c596b7fa5bf893eba14e2eafc75d32be56c8d35eeb73f130e1b79221d5313ca",
    "src/argus/domain/calculations/growth_projection.py": "c5fd869f0857e4a508fc45480a499b7b1746d0510d2f5e6ed19e3de5a3072b28",
    "src/argus/domain/calculations/income_yield.py": "c7908de39db2349c679031090e09ed9faa8140a473b1d969afe6a9d8c6563204",
    "src/argus/domain/calculations/price_multiple.py": "5ce5ac076813b028070316f455d9369c2e56974c1c6ea383efeec5bb036e6599",
    "src/argus/domain/calculations/ranked_comparison.py": "fc32095d2790d6913fe4a33aaf7d46edfae9f1f96847ce17193cabb24d3a6f71",
    "src/argus/domain/calculations/time_value.py": "da769e7c6a0c099332be90308d14ab77489c525b43c8f9c4c89f603154952987",
    "src/argus/domain/calculations/valuation_scenarios.py": "12c10ddd77c0e13dd348ba7e9fd07a2a81774656c26b1739565f8f0303b16e14",
    "src/argus/domain/finance/__init__.py": "b82c4d51b37afd4ab89dfbfce756d48b37cd951bf7a5b011b30affa4013a20c2",
    "src/argus/domain/finance/_roots.py": "fae5451f531f1b904e6f74f1865899633e00d120598a1a0fd1dc9732945fa3e3",
    "src/argus/domain/finance/bonds.py": "9277ac56d39eb3129d389bfa553867b7672e93c17e2d47f88b5d21e2886abd51",
    "src/argus/domain/finance/comparison.py": "ff5353308908989af58dcccd781b61e2674d0fa1c2ef5f473617937d70083ab5",
    "src/argus/domain/finance/dcf.py": "13732030468f5e0486f9b02ff449ebe349764cc0ba44b41de199d214a20b4be2",
    "src/argus/domain/finance/growth.py": "579998ffb56144b14b62ff8095b4f8109b716e8422fbd726a1c36e1120045cf4",
    "src/argus/domain/finance/money.py": "629ac09bf8bccc453257bd2eb734f839eacdf089fb3dc77ca82c4958ae2c5007",
    "src/argus/domain/finance/outcomes.py": "4d3f9a5473e7c92bb1268a1671163929b229420f730b40db3153139c93418264",
    "src/argus/domain/finance/ratios.py": "e555d55d3f68d066cce544161dc6e30794283278d35c3f4ac13440bc95f41f4e",
    "src/argus/domain/finance/tvm.py": "c06bce6bbd145fdf17e318ea2c49e03fd27b9e7f0b87592a5486874227047e17",
    "src/argus/domain/finance/valuation.py": "a6eeb5cc20c0e9630793af6b4e7dcbc76890568a5527943f8cabab4910d80292",
}


class VendorError(RuntimeError):
    """The pinned input or deterministic generated output no longer matches."""


def _digest(content: bytes | str) -> str:
    encoded = content.encode("utf-8") if isinstance(content, str) else content
    return hashlib.sha256(encoded).hexdigest()


def _replace_once(content: str, old: str, new: str, *, adapter: str) -> str:
    count = content.count(old)
    if count != 1:
        raise VendorError(f"{adapter}: expected one source seam, found {count}")
    return content.replace(old, new, 1)


def _adapt_tool_declaration(content: str) -> str:
    content = _replace_once(
        content,
        "from loguru import logger\n",
        "",
        adapter="stdlib logging import",
    )
    content = _replace_once(
        content,
        "import json\nimport re\n",
        "import json\nimport logging\nimport re\n",
        adapter="stdlib logging placement",
    )
    content = _replace_once(
        content,
        ")\n\n\nclass ToolInvocationError",
        ")\n\nlogger = logging.getLogger(__name__)\n\n\nclass ToolInvocationError",
        adapter="stdlib logger",
    )
    return _replace_once(
        content,
        'logger.warning("Tool execution failed its declared contract", tool_name=self.name)',
        'logger.warning("Tool execution failed its declared contract: %s", self.name)',
        adapter="stdlib warning",
    )


def _adapt_tool_contracts(content: str) -> str:
    content = _replace_once(
        content,
        "from server.argus_core.research.contracts import ResearchSource\n",
        "from server.argus_core.research_contracts import ResearchSource\n",
        adapter="reduced research contract",
    )
    content = _replace_once(
        content,
        'ToolFactSourceKind = Literal[\n    "user", "page", "market_data", "assumption", "computed", "not_found"\n]',
        'ToolFactSourceKind = Literal[\n    "user",\n    "page",\n    "market_data",\n    "account",\n    "record",\n    "assumption",\n    "computed",\n    "not_found",\n]',
        adapter="local provenance kinds",
    )
    old = '''class ToolFactSource(ToolContract):
    """Where a fact came from. A page names its title and date, market data names
    the date of its bar, and nothing else carries a citation."""

    kind: ToolFactSourceKind
    title: str | None = Field(default=None, max_length=300)
    url: str | None = Field(default=None, max_length=2048)
    date: str | None = Field(default=None, pattern=r"^\\d{4}-\\d{2}-\\d{2}$")

    @model_validator(mode="after")
    def only_a_page_is_cited(self) -> ToolFactSource:
        if self.kind == "page":
            return self
        if self.title or self.url:
            raise ValueError("Only a page source carries a title or url")
        if self.date and self.kind != "market_data":
            raise ValueError("Only a page or market data source carries a date")
        return self
'''
    new = '''class ToolFactSource(ToolContract):
    """Where a fact came from. A page names its title and date, market data names
    the date of its bar, and local account/record facts name their dated owner."""

    kind: ToolFactSourceKind
    title: str | None = Field(default=None, max_length=300)
    url: str | None = Field(default=None, max_length=2048)
    date: str | None = Field(default=None, pattern=r"^\\d{4}-\\d{2}-\\d{2}$")
    ref: str | None = Field(default=None, min_length=1, max_length=160)
    currency: str | None = Field(default=None, pattern=r"^[A-Z]{3}$")

    @model_validator(mode="after")
    def only_a_page_is_cited(self) -> ToolFactSource:
        if self.kind == "page":
            if self.ref or self.currency:
                raise ValueError("A page source does not carry a local record reference")
            return self
        if self.title or self.url:
            raise ValueError("Only a page source carries a title or url")
        if self.kind in {"account", "record"}:
            if not self.date or not self.ref or not self.currency:
                raise ValueError(
                    "An account or record source requires date, ref and currency"
                )
            return self
        if self.ref or self.currency:
            raise ValueError("Only an account or record source carries ref or currency")
        if self.date and self.kind != "market_data":
            raise ValueError(
                "Only a page, market data, account or record source carries a date"
            )
        return self
'''
    return _replace_once(content, old, new, adapter="local provenance fields")


def _adapt_shared(content: str) -> str:
    content = _replace_once(
        content,
        "from datetime import date, timedelta\n",
        "from datetime import date, timedelta\nfrom decimal import ROUND_HALF_UP, Decimal\n",
        adapter="decimal money rounding imports",
    )
    content = _replace_once(
        content,
        "from pydantic import AfterValidator, BaseModel, ConfigDict, Field\n",
        "from pydantic import AfterValidator, BaseModel, ConfigDict, Field, model_validator\n",
        adapter="currency validator import",
    )
    content = _replace_once(
        content,
        "from server.argus_core.home_country import currency_codes\n",
        "",
        adapter="remove Babel currency catalog",
    )
    content = _replace_once(
        content,
        "from server.argus_core.tool_declaration import ToolInvocationError, ToolPolicy\n",
        "from server.argus_core.tool_declaration import ToolInvocationError, ToolPolicy\n"
        "from server.platform.common import CURRENCY_DIGITS\n",
        adapter="Clara currency catalog",
    )
    content = _replace_once(
        content,
        '    if code not in currency_codes():\n        raise ValueError("currency must be an ISO 4217 code in use")',
        '    if code not in CURRENCY_DIGITS:\n        raise ValueError("currency must be supported by Clara")',
        adapter="Clara currency validation",
    )
    content = _replace_once(
        content,
        "    sources: dict[str, ToolFactSource] = Field(default_factory=dict)\n\n\nclass CalculationResult",
        """    sources: dict[str, ToolFactSource] = Field(default_factory=dict)

    @model_validator(mode="after")
    def one_currency(self) -> CalculationArguments:
        if any(
            source.currency is not None and source.currency != self.currency
            for source in self.sources.values()
        ):
            raise ValueError("calculation inputs must use one currency")
        return self


class CalculationResult""",
        adapter="single-currency provenance",
    )
    content = _replace_once(
        content,
        "        value=round(amount, MONEY_DECIMALS),",
        "        value=money_round(amount, currency),",
        adapter="money fact precision",
    )
    content = _replace_once(
        content,
        "    repair_label: str | None = None,\n) -> ToolInvocationError:",
        "    repair_label: str | None = None,\n    currency: str | None = None,\n) -> ToolInvocationError:",
        adapter="repair currency",
    )
    content = _replace_once(
        content,
        """            changes={
                name: round(value, MONEY_DECIMALS)
                for name, value in outcome.repair.items()
            },""",
        """            changes={
                name: (
                    money_round(value, currency)
                    if currency is not None
                    else round(value, MONEY_DECIMALS)
                )
                for name, value in outcome.repair.items()
            },""",
        adapter="repair money precision",
    )
    return _replace_once(
        content,
        "def dump(model: BaseModel) -> dict[str, Any]:",
        '''def money_round(value: float, currency: str) -> float:
    """Round a reader-facing amount with Clara's canonical currency rule."""
    digits = CURRENCY_DIGITS[currency]
    quantum = Decimal(1).scaleb(-digits)
    return float(Decimal(str(value)).quantize(quantum, rounding=ROUND_HALF_UP))


def dump(model: BaseModel) -> dict[str, Any]:''',
        adapter="half-up money precision",
    )


def _adapt_calculations_init(content: str) -> str:
    for old, new in (
        (
            "    from server.argus_core.calculations.debt_to_income import get_debt_to_income_declaration\n",
            "    from server.argus_core.calculations.debt_to_income import (\n"
            "        get_debt_to_income_declaration,\n"
            "    )\n",
        ),
        (
            "    from server.argus_core.calculations.effective_rate import get_effective_rate_declaration\n",
            "    from server.argus_core.calculations.effective_rate import (\n"
            "        get_effective_rate_declaration,\n"
            "    )\n",
        ),
        (
            "    from server.argus_core.calculations.price_multiple import get_price_multiple_declaration\n",
            "    from server.argus_core.calculations.price_multiple import (\n"
            "        get_price_multiple_declaration,\n"
            "    )\n",
        ),
    ):
        content = _replace_once(content, old, new, adapter="local import formatting")
    return content


def _adapt_ranked_comparison(content: str) -> str:
    content = _replace_once(
        content,
        "    input_fact,\n    text,",
        "    input_fact,\n    money_round,\n    text,",
        adapter="ranked money precision import",
    )
    content = _replace_once(
        content,
        "    unit = _unit(arguments.key_kind, arguments.currency)\n    facts = [",
        """    unit = _unit(arguments.key_kind, arguments.currency)

    def display_value(value: float) -> float:
        if arguments.key_kind == "money":
            return money_round(value, arguments.currency)
        return round(value, 2)

    facts = [""",
        adapter="ranked money precision helper",
    )
    content = _replace_once(
        content,
        "            value=round(row.value, 2),",
        "            value=display_value(row.value),",
        adapter="ranked values",
    )
    return _replace_once(
        content,
        "                value=round(row.gap_to_best, 2),",
        "                value=display_value(row.gap_to_best),",
        adapter="ranked gaps",
    )


def _adapt_time_value(content: str) -> str:
    return _replace_once(
        content,
        "                raise no_solution(_periods_repair(count, pv_s, per_period, arguments))",
        "                raise no_solution(\n"
        "                    _periods_repair(count, pv_s, per_period, arguments),\n"
        "                    currency=arguments.currency,\n"
        "                )",
        adapter="repair currency precision",
    )


def _adapt_valuation_scenarios(content: str) -> str:
    content = _replace_once(
        content,
        "    money_input,\n    no_solution,",
        "    money_input,\n    money_round,\n    no_solution,",
        adapter="scenario money precision import",
    )
    for field in (
        "base.value_at_horizon",
        "row.value_at_horizon",
        "row.price_at_horizon",
    ):
        content = _replace_once(
            content,
            f"value=round({field}, 2),",
            f"value=money_round({field}, currency),",
            adapter=f"scenario precision for {field}",
        )
    return content


ADAPTERS: dict[str, Callable[[str], str]] = {
    "tool_declaration.py": _adapt_tool_declaration,
    "tool_contracts.py": _adapt_tool_contracts,
    "calculations/__init__.py": _adapt_calculations_init,
    "calculations/_shared.py": _adapt_shared,
    "calculations/ranked_comparison.py": _adapt_ranked_comparison,
    "calculations/time_value.py": _adapt_time_value,
    "calculations/valuation_scenarios.py": _adapt_valuation_scenarios,
}


def _target_path(source_path: str) -> str:
    return source_path.removeprefix("src/argus/domain/")


def _generate() -> dict[str, str]:
    generated: dict[str, str] = {}
    for source_path, expected_hash in SOURCE_HASHES.items():
        source = REPOSITORY_ROOT / source_path
        content_bytes = source.read_bytes()
        actual_hash = _digest(content_bytes)
        if actual_hash != expected_hash:
            raise VendorError(
                f"canonical source drift: {source_path} is {actual_hash}, "
                f"expected {expected_hash} from {SOURCE_REVISION}"
            )
        target = _target_path(source_path)
        content = content_bytes.decode("utf-8").replace(
            "argus.domain.", "server.argus_core."
        )
        adapter = ADAPTERS.get(target)
        if adapter is not None:
            content = adapter(content)
        generated[target] = GENERATED_HEADER + content

    manifest = {
        "schema_version": 1,
        "source_revision": SOURCE_REVISION,
        "source_files": SOURCE_HASHES,
        "generated_files": {
            path: _digest(content) for path, content in sorted(generated.items())
        },
    }
    generated["_generated_manifest.json"] = (
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return generated


def _write(output: Path, generated: dict[str, str]) -> None:
    for relative_path, content in generated.items():
        destination = output / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")


def _check(output: Path, generated: dict[str, str]) -> None:
    drifted: list[str] = []
    for relative_path, expected in generated.items():
        destination = output / relative_path
        if (
            not destination.is_file()
            or destination.read_text(encoding="utf-8") != expected
        ):
            drifted.append(relative_path)
    expected_files = set(generated) | LOCAL_PYTHON_FILES
    actual_files = {
        path.relative_to(output).as_posix()
        for path in output.rglob("*")
        if path.is_file()
        and "__pycache__" not in path.relative_to(output).parts
        and path.suffix != ".pyc"
    }
    drifted.extend(f"unexpected:{path}" for path in sorted(actual_files - expected_files))
    if output.resolve() == DEFAULT_OUTPUT.resolve():
        drifted.extend(
            f"missing-local:{path}" for path in sorted(LOCAL_PYTHON_FILES - actual_files)
        )
    if drifted:
        raise VendorError("generated core drift: " + ", ".join(sorted(drifted)))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true", help="verify generated files")
    action.add_argument("--write", action="store_true", help="regenerate pinned files")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="package root to write/check (defaults to the committed local package)",
    )
    arguments = parser.parse_args()
    try:
        generated = _generate()
        if arguments.write:
            _write(arguments.output, generated)
            print(f"wrote {len(generated)} generated files to {arguments.output}")
        else:
            _check(arguments.output, generated)
            print(f"verified {len(generated)} generated files in {arguments.output}")
    except (OSError, UnicodeError, VendorError) as exc:
        print(f"argus core sync failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
