// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteStrategiesByIdData, DeleteStrategiesByIdResponses, GetAssetsData, GetAssetsResponses, GetAuthSessionData, GetAuthSessionResponses, GetBacktestsByIdData, GetBacktestsByIdErrors, GetBacktestsByIdResponses, GetHealthData, GetHealthResponses, GetHistoryData, GetHistoryResponses, GetMarketBarsData, GetMarketBarsResponses, GetScreenersData, GetScreenersResponses, GetStrategiesByIdData, GetStrategiesByIdResponses, GetStrategiesData, GetStrategiesResponses, PatchAuthProfileData, PatchAuthProfileResponses, PostAgentDraftData, PostAgentDraftResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostBacktestsData, PostBacktestsErrors, PostBacktestsResponses, PostBillingCheckoutData, PostBillingCheckoutResponses, PostFeedbackData, PostFeedbackResponses, PostMocksBacktestData, PostMocksBacktestResponses, PostShareData, PostShareResponses, PostStrategiesData, PostStrategiesResponses, PostWebhookBillingData, PostWebhookBillingResponses, PutStrategiesByIdData, PutStrategiesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get current authenticated user session
 */
export const getAuthSession = <ThrowOnError extends boolean = false>(options?: Options<GetAuthSessionData, ThrowOnError>) => (options?.client ?? client).get<GetAuthSessionResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/auth/session',
    ...options
});

/**
 * Update user profile settings
 */
export const patchAuthProfile = <ThrowOnError extends boolean = false>(options?: Options<PatchAuthProfileData, ThrowOnError>) => (options?.client ?? client).patch<PatchAuthProfileResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/auth/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List user strategies
 */
export const getStrategies = <ThrowOnError extends boolean = false>(options?: Options<GetStrategiesData, ThrowOnError>) => (options?.client ?? client).get<GetStrategiesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/strategies',
    ...options
});

/**
 * Save a new strategy
 */
export const postStrategies = <ThrowOnError extends boolean = false>(options?: Options<PostStrategiesData, ThrowOnError>) => (options?.client ?? client).post<PostStrategiesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/strategies',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a strategy
 */
export const deleteStrategiesById = <ThrowOnError extends boolean = false>(options: Options<DeleteStrategiesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteStrategiesByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/strategies/{id}',
    ...options
});

/**
 * Get strategy by id
 */
export const getStrategiesById = <ThrowOnError extends boolean = false>(options: Options<GetStrategiesByIdData, ThrowOnError>) => (options.client ?? client).get<GetStrategiesByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/strategies/{id}',
    ...options
});

/**
 * Update a strategy
 */
export const putStrategiesById = <ThrowOnError extends boolean = false>(options: Options<PutStrategiesByIdData, ThrowOnError>) => (options.client ?? client).put<PutStrategiesByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/strategies/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user run history
 */
export const getHistory = <ThrowOnError extends boolean = false>(options?: Options<GetHistoryData, ThrowOnError>) => (options?.client ?? client).get<GetHistoryResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/history',
    ...options
});

/**
 * Execute a backtest simulation
 */
export const postBacktests = <ThrowOnError extends boolean = false>(options: Options<PostBacktestsData, ThrowOnError>) => (options.client ?? client).post<PostBacktestsResponses, PostBacktestsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/backtests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get detailed backtest results
 */
export const getBacktestsById = <ThrowOnError extends boolean = false>(options: Options<GetBacktestsByIdData, ThrowOnError>) => (options.client ?? client).get<GetBacktestsByIdResponses, GetBacktestsByIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/backtests/{id}',
    ...options
});

/**
 * Draft a strategy using AI Natural Language input
 */
export const postAgentDraft = <ThrowOnError extends boolean = false>(options: Options<PostAgentDraftData, ThrowOnError>) => (options.client ?? client).post<PostAgentDraftResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/agent/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke upstream session and clear local auth cookies
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Search available market assets
 */
export const getAssets = <ThrowOnError extends boolean = false>(options: Options<GetAssetsData, ThrowOnError>) => (options.client ?? client).get<GetAssetsResponses, unknown, ThrowOnError>({ url: '/assets', ...options });

/**
 * TradingView Universal Datafeed Proxy
 */
export const getMarketBars = <ThrowOnError extends boolean = false>(options: Options<GetMarketBarsData, ThrowOnError>) => (options.client ?? client).get<GetMarketBarsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/market/bars',
    ...options
});

/**
 * Alpaca Movers / Most-Actives proxy
 */
export const getScreeners = <ThrowOnError extends boolean = false>(options?: Options<GetScreenersData, ThrowOnError>) => (options?.client ?? client).get<GetScreenersResponses, unknown, ThrowOnError>({ url: '/screeners', ...options });

/**
 * Initialize payment gateway session
 */
export const postBillingCheckout = <ThrowOnError extends boolean = false>(options?: Options<PostBillingCheckoutData, ThrowOnError>) => (options?.client ?? client).post<PostBillingCheckoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/billing/checkout',
    ...options
});

/**
 * Supabase Edge Function to intercept gateway updates
 */
export const postWebhookBilling = <ThrowOnError extends boolean = false>(options?: Options<PostWebhookBillingData, ThrowOnError>) => (options?.client ?? client).post<PostWebhookBillingResponses, unknown, ThrowOnError>({ url: '/webhook/billing', ...options });

/**
 * Create OpenGraph shareable link from simulation
 */
export const postShare = <ThrowOnError extends boolean = false>(options?: Options<PostShareData, ThrowOnError>) => (options?.client ?? client).post<PostShareResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/share',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Submit user feedback
 */
export const postFeedback = <ThrowOnError extends boolean = false>(options?: Options<PostFeedbackData, ThrowOnError>) => (options?.client ?? client).post<PostFeedbackResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sb-access-token',
            type: 'apiKey'
        }],
    url: '/feedback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * API health and uptime check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Dev-only endpoint for Prism mocking
 */
export const postMocksBacktest = <ThrowOnError extends boolean = false>(options?: Options<PostMocksBacktestData, ThrowOnError>) => (options?.client ?? client).post<PostMocksBacktestResponses, unknown, ThrowOnError>({ url: '/_mocks/backtest', ...options });
