// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api/v1' | 'https://argus-app-suz5.onrender.com/api/v1' | (string & {});
};

export type UserResponse = {
    id: string;
    is_admin: boolean;
    subscription_tier: 'free' | 'plus' | 'pro' | 'max';
    backtest_quota: number;
    remaining_quota: number;
    ai_draft_quota?: number;
    remaining_ai_draft_quota?: number;
    feature_flags: {
        advanced_charting?: boolean;
        options_enabled?: boolean;
        memos_sync?: boolean;
    };
    theme: 'light' | 'dark' | 'system';
    onboarding_completed: boolean;
    onboarding_step: string;
    onboarding_intent?: string;
};

export type ErrorResponse = {
    type: string;
    title: string;
    status: number;
    detail: string;
    instance?: string;
    error_code: string;
};

export type StrategySchema = {
    id?: string;
    name: string;
    symbols: Array<string>;
    timeframe: string;
    slippage?: number;
    fees?: number;
    entry_criteria?: Array<{
        [key: string]: unknown;
    }>;
    exit_criteria?: Array<{
        [key: string]: unknown;
    }>;
    stop_loss_pct?: number;
    take_profit_pct?: number;
    ai_explanation?: string;
};

export type BacktestRequest = {
    strategy_id?: string;
    symbols?: Array<string>;
    timeframe?: string;
    slippage?: number;
    fees?: number;
    side?: 'long' | 'short';
    participation_rate?: number;
    execution_priority?: number;
    va_sensitivity?: number;
    slippage_model?: 'fixed' | 'vol_adjusted';
    entry_criteria?: Array<{
        [key: string]: unknown;
    }>;
    exit_criteria?: Array<{
        [key: string]: unknown;
    }>;
    stop_loss_pct?: number;
    take_profit_pct?: number;
};

export type BacktestResults = {
    total_return_pct?: number;
    win_rate?: number;
    sharpe_ratio?: number;
    sortino_ratio?: number;
    calmar_ratio?: number;
    profit_factor?: number;
    expectancy?: number;
    max_drawdown_pct?: number;
    equity_curve?: Array<number>;
    ideal_equity_curve?: Array<number>;
    benchmark_equity_curve?: Array<number>;
    benchmark_symbol?: string;
    trades?: Array<TradeSnippet>;
    reality_gap_metrics?: RealityGapMetrics;
    pattern_breakdown?: {
        [key: string]: number;
    };
};

export type BacktestResponse = {
    id: string;
    config_snapshot: {
        [key: string]: unknown;
    };
    results: BacktestResults;
};

export type RealityGapMetrics = {
    slippage_impact_pct?: number;
    fee_impact_pct?: number;
    vol_hazard_pct?: number;
    fidelity_score?: number;
};

export type TradeSnippet = {
    entry_time?: string;
    entry_price?: number;
    exit_price?: number;
    pnl_pct?: number;
};

export type SimulationLogEntry = {
    id?: string;
    strategy_name?: string;
    symbols?: Array<string>;
    timeframe?: string;
    status?: 'pending' | 'completed' | 'failed' | 'processing';
    total_return_pct?: number;
    sharpe_ratio?: number;
    max_drawdown_pct?: number;
    win_rate?: number;
    total_trades?: number;
    created_at?: string;
    completed_at?: string;
};

export type ShareResponse = {
    vanity_url: string;
    og_image: string;
    og_title?: string;
};

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionResponses = {
    /**
     * Session details
     */
    200: UserResponse;
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PatchAuthProfileData = {
    body?: {
        theme?: 'light' | 'dark' | 'system';
        onboarding_completed?: boolean;
        onboarding_step?: string;
        onboarding_intent?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type PatchAuthProfileResponses = {
    /**
     * Profile updated
     */
    200: UserResponse;
};

export type PatchAuthProfileResponse = PatchAuthProfileResponses[keyof PatchAuthProfileResponses];

export type GetStrategiesData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/strategies';
};

export type GetStrategiesResponses = {
    /**
     * Paginated strategies
     */
    200: {
        strategies?: Array<StrategySchema>;
        next_cursor?: string;
    };
};

export type GetStrategiesResponse = GetStrategiesResponses[keyof GetStrategiesResponses];

export type PostStrategiesData = {
    body?: StrategySchema;
    path?: never;
    query?: never;
    url: '/strategies';
};

export type PostStrategiesResponses = {
    /**
     * Strategy created
     */
    201: StrategySchema;
};

export type PostStrategiesResponse = PostStrategiesResponses[keyof PostStrategiesResponses];

export type DeleteStrategiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/strategies/{id}';
};

export type DeleteStrategiesByIdResponses = {
    /**
     * Strategy deleted
     */
    204: void;
};

export type DeleteStrategiesByIdResponse = DeleteStrategiesByIdResponses[keyof DeleteStrategiesByIdResponses];

export type GetStrategiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/strategies/{id}';
};

export type GetStrategiesByIdResponses = {
    /**
     * Strategy response
     */
    200: StrategySchema;
};

export type GetStrategiesByIdResponse = GetStrategiesByIdResponses[keyof GetStrategiesByIdResponses];

export type PutStrategiesByIdData = {
    body?: StrategySchema;
    path: {
        id: string;
    };
    query?: never;
    url: '/strategies/{id}';
};

export type PutStrategiesByIdResponses = {
    /**
     * Structure updated
     */
    200: unknown;
};

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
    };
    url: '/history';
};

export type GetHistoryResponses = {
    /**
     * Paginated run history
     */
    200: {
        simulations?: Array<SimulationLogEntry>;
        total?: number;
        next_cursor?: string;
    };
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type PostBacktestsData = {
    body: BacktestRequest;
    path?: never;
    query?: never;
    url: '/backtests';
};

export type PostBacktestsErrors = {
    /**
     * Quota exceeded
     */
    402: ErrorResponse;
};

export type PostBacktestsError = PostBacktestsErrors[keyof PostBacktestsErrors];

export type PostBacktestsResponses = {
    /**
     * Backtest results returned
     */
    200: BacktestResponse;
};

export type PostBacktestsResponse = PostBacktestsResponses[keyof PostBacktestsResponses];

export type GetBacktestsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/backtests/{id}';
};

export type GetBacktestsByIdErrors = {
    /**
     * Backtest not found
     */
    404: unknown;
};

export type GetBacktestsByIdResponses = {
    /**
     * Detailed backtest results
     */
    200: BacktestResponse;
};

export type GetBacktestsByIdResponse = GetBacktestsByIdResponses[keyof GetBacktestsByIdResponses];

export type PostAgentDraftData = {
    body: {
        prompt?: string;
    };
    path?: never;
    query?: never;
    url: '/agent/draft';
};

export type PostAgentDraftResponses = {
    /**
     * Returns an unexecuted draft StrategySchema plus AI explanation
     */
    200: {
        draft: StrategySchema;
        ai_explanation: string;
    };
};

export type PostAgentDraftResponse = PostAgentDraftResponses[keyof PostAgentDraftResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAssetsData = {
    body?: never;
    path?: never;
    query: {
        search: string;
    };
    url: '/assets';
};

export type GetAssetsResponses = {
    /**
     * List of matched tickers
     */
    200: Array<string>;
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type GetMarketBarsData = {
    body?: never;
    path?: never;
    query: {
        symbol: string;
        from: number;
        to: number;
        resolution: string;
    };
    url: '/market/bars';
};

export type GetMarketBarsResponses = {
    /**
     * UDF formatted arrays
     */
    200: {
        t?: Array<number>;
        o?: Array<number>;
        h?: Array<number>;
        l?: Array<number>;
        c?: Array<number>;
        v?: Array<number>;
        s?: string;
    };
};

export type GetMarketBarsResponse = GetMarketBarsResponses[keyof GetMarketBarsResponses];

export type GetScreenersData = {
    body?: never;
    path?: never;
    query?: {
        type?: 'movers' | 'active';
    };
    url: '/screeners';
};

export type GetScreenersResponses = {
    /**
     * Assets list
     */
    200: unknown;
};

export type PostBillingCheckoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/checkout';
};

export type PostBillingCheckoutResponses = {
    /**
     * Checkout URL
     */
    200: unknown;
};

export type PostWebhookBillingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhook/billing';
};

export type PostWebhookBillingResponses = {
    /**
     * Billing updated
     */
    200: unknown;
};

export type PostShareData = {
    body?: {
        simulation_id?: string;
    };
    path?: never;
    query?: never;
    url: '/share';
};

export type PostShareResponses = {
    /**
     * Vanity URL configured
     */
    200: ShareResponse;
};

export type PostShareResponse = PostShareResponses[keyof PostShareResponses];

export type PostFeedbackData = {
    body?: {
        type?: 'bug' | 'feature_request' | 'general';
        message?: string;
        simulation_id?: string;
    };
    path?: never;
    query?: never;
    url: '/feedback';
};

export type PostFeedbackResponses = {
    /**
     * Feedback received
     */
    201: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMocksBacktestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/_mocks/backtest';
};

export type PostMocksBacktestResponses = {
    /**
     * Mocked BacktestResponse return
     */
    200: BacktestResponse;
};

export type PostMocksBacktestResponse = PostMocksBacktestResponses[keyof PostMocksBacktestResponses];
