import type { Locale } from "../../platform/types";

const es = {
  accounts: "Cuentas",
  accountsIntro: "Cada cuenta, con su saldo y su origen.",
  addAccount: "Agregar cuenta",
  editAccount: "Editar cuenta",
  name: "Nombre",
  institution: "Institución",
  kind: "Tipo",
  currency: "Moneda",
  opening: "Saldo inicial",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Cancelar",
  edit: "Editar",
  remove: "Eliminar",
  restore: "Restaurar",
  deleted: "Eliminada",
  includeDeleted: "Mostrar cuentas eliminadas",
  account: "Cuenta",
  allAccounts: "Todas las cuentas",
  noAccounts: "No hay cuentas en esta moneda.",
  noAccountsDetail: "Agrega una cuenta manual para comenzar tu registro.",
  noConversion:
    "Los saldos se muestran en su moneda original. No se convierten.",
  saved: "Cambios guardados.",
  removed: "Registro eliminado. Puedes restaurarlo.",
  error:
    "No pudimos completar la acción. Revisa los datos e inténtalo de nuevo.",
  loadError: "No pudimos cargar estos registros.",
  retry: "Reintentar",
  loading: "Cargando registros…",
  connectors: "Conexiones de demostración",
  connectorsIntro:
    "Simulaciones locales. No conectan con bancos ni mueven dinero.",
  connect: "Conectar demo",
  refresh: "Simular actualización",
  failSync: "Simular fallo",
  lastGood: "Última actualización correcta",
  never: "Sin actualización",
  failedSync: "La actualización falló. Se conservan los últimos datos.",
  connected: "Conectada",
  deletedExplain:
    "Eliminar oculta esta cuenta y sus movimientos de los totales. Puedes restaurarla después.",
  confirmRemove: "Eliminar cuenta",
  viewTransactions: "Ver movimientos",
  transactions: "Movimientos",
  transactionsIntro: "Encuentra, revisa y organiza tu registro.",
  addTransaction: "Agregar movimiento",
  search: "Buscar comercio o descripción",
  from: "Desde",
  to: "Hasta",
  category: "Categoría",
  allCategories: "Todas las categorías",
  status: "Estado",
  allStatuses: "Todos los estados",
  posted: "Registrado",
  pending: "Pendiente",
  sort: "Orden",
  date_desc: "Más recientes",
  date_asc: "Más antiguos",
  amount_desc: "Importe mayor",
  amount_asc: "Importe menor",
  perPage: "Filas por página",
  previous: "Anterior",
  next: "Siguiente",
  page: "Página",
  of: "de",
  matches: "movimientos coincidentes",
  noTransactions: "No hay movimientos con estos filtros.",
  clearFilters: "Quitar filtros",
  date: "Fecha",
  merchant: "Comercio o concepto",
  description: "Descripción",
  amount: "Importe",
  notes: "Notas",
  details: "Detalles",
  detail: "Detalle del movimiento",
  filteredTotals: "Totales de todos los movimientos filtrados",
  income: "Ingresos",
  spending: "Gastos",
  net: "Neto",
  transferNote:
    "Las transferencias y los movimientos pendientes no cuentan como ingresos o gastos.",
  manualNote:
    "Registro local. Usa importes negativos para gastos y positivos para ingresos.",
  split: "Dividir por categorías",
  addSplit: "Agregar parte",
  removeSplit: "Quitar parte",
  splitNote:
    "Los importes de las partes deben sumar exactamente el importe del movimiento, con el mismo signo.",
  splitTotalError: "Las partes deben sumar el importe del movimiento.",
  reverse: "Crear contrapartida",
  reverseNote:
    "Se guardará un movimiento nuevo con el importe opuesto. El original permanece.",
  deleteTransaction: "Eliminar movimiento",
  deleteTransactionNote:
    "Se excluirá de los totales. Si es una transferencia, se eliminarán ambas partes.",
  undo: "Deshacer eliminación",
  destination: "Cuenta de destino",
  importCsv: "Importar CSV",
  exportCsv: "Exportar CSV",
  sampleCsv: "Descargar ejemplo",
  file: "Archivo CSV",
  csvText: "Contenido CSV",
  preview: "Validar archivo",
  previewTitle: "Revisión de importación",
  newRows: "filas válidas",
  duplicates: "duplicadas",
  line: "Línea",
  duplicate: "Duplicada, se omite",
  valid: "Lista para importar",
  confirmImport: "Confirmar importación",
  imported: "movimientos importados",
  csvHint: "Máximo 1 MB y 2,000 filas. La moneda debe coincidir con la cuenta.",
  csvErrors: "Corrige estas filas antes de importar.",
  fileTooLarge: "El archivo supera el límite de 1 MB.",
  invalidCsv: "La fila contiene datos inválidos.",
  spendingIntro: "Qué entró, qué salió y dónde fue, mes a mes.",
  month: "Mes",
  categories: "Por categoría",
  merchants: "Comercios principales",
  periodTotals: "Totales del mes",
  noSpending: "No hay gastos en este periodo.",
  spendingNote:
    "Los reembolsos reducen los gastos. No se incluyen transferencias ni movimientos pendientes.",
  matching: "Ver movimientos de",
  noMerchants: "No hay comercios en este periodo.",
  sourceScope: "Las cifras y categorías comparten la misma fuente y fecha.",
  checking: "Corriente",
  savings: "Ahorro",
  credit_card: "Tarjeta de crédito",
  loan: "Préstamo",
  investment: "Inversión",
  cash: "Efectivo",
  expense: "Gasto",
  refund: "Reembolso",
  transfer: "Transferencia",
  adjustment: "Ajuste",
  groceries: "Supermercado",
  dining: "Restaurantes",
  housing: "Vivienda",
  transport: "Transporte",
  utilities: "Servicios",
  health: "Salud",
  shopping: "Compras",
  entertainment: "Entretenimiento",
  travel: "Viajes",
  education: "Educación",
  insurance: "Seguros",
  other: "Otros",
};
const en: typeof es = {
  accounts: "Accounts",
  accountsIntro: "Every account, with its balance and source.",
  addAccount: "Add account",
  editAccount: "Edit account",
  name: "Name",
  institution: "Institution",
  kind: "Type",
  currency: "Currency",
  opening: "Opening balance",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  edit: "Edit",
  remove: "Delete",
  restore: "Restore",
  deleted: "Deleted",
  includeDeleted: "Show deleted accounts",
  account: "Account",
  allAccounts: "All accounts",
  noAccounts: "No accounts in this currency.",
  noAccountsDetail: "Add a manual account to start your ledger.",
  noConversion:
    "Balances stay in their original currency. No conversion is applied.",
  saved: "Changes saved.",
  removed: "Record deleted. You can restore it.",
  error: "We could not complete the action. Check the details and try again.",
  loadError: "We could not load these records.",
  retry: "Retry",
  loading: "Loading records…",
  connectors: "Demo connections",
  connectorsIntro:
    "Local simulations. They do not connect to banks or move money.",
  connect: "Connect demo",
  refresh: "Simulate refresh",
  failSync: "Simulate failure",
  lastGood: "Last successful refresh",
  never: "No refresh yet",
  failedSync: "The refresh failed. The last data is preserved.",
  connected: "Connected",
  deletedExplain:
    "Deleting hides this account and its transactions from totals. You can restore it later.",
  confirmRemove: "Delete account",
  viewTransactions: "View transactions",
  transactions: "Transactions",
  transactionsIntro: "Find, review, and organize your ledger.",
  addTransaction: "Add transaction",
  search: "Search merchant or description",
  from: "From",
  to: "To",
  category: "Category",
  allCategories: "All categories",
  status: "Status",
  allStatuses: "All statuses",
  posted: "Posted",
  pending: "Pending",
  sort: "Sort",
  date_desc: "Newest first",
  date_asc: "Oldest first",
  amount_desc: "Largest amount",
  amount_asc: "Smallest amount",
  perPage: "Rows per page",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  matches: "matching transactions",
  noTransactions: "No transactions match these filters.",
  clearFilters: "Clear filters",
  date: "Date",
  merchant: "Merchant or purpose",
  description: "Description",
  amount: "Amount",
  notes: "Notes",
  details: "Details",
  detail: "Transaction detail",
  filteredTotals: "Totals for all matching transactions",
  income: "Income",
  spending: "Spending",
  net: "Net",
  transferNote:
    "Transfers and pending transactions do not count as income or spending.",
  manualNote:
    "Local record. Use negative amounts for expenses and positive amounts for income.",
  split: "Split into categories",
  addSplit: "Add split",
  removeSplit: "Remove split",
  splitNote:
    "Split amounts must add up exactly to the transaction amount, with the same sign.",
  splitTotalError: "Splits must add up to the transaction amount.",
  reverse: "Create reversal",
  reverseNote:
    "A new transaction with the opposite amount will be saved. The original remains.",
  deleteTransaction: "Delete transaction",
  deleteTransactionNote:
    "It will be excluded from totals. For a transfer, both sides will be deleted.",
  undo: "Undo deletion",
  destination: "Destination account",
  importCsv: "Import CSV",
  exportCsv: "Export CSV",
  sampleCsv: "Download example",
  file: "CSV file",
  csvText: "CSV content",
  preview: "Validate file",
  previewTitle: "Import review",
  newRows: "valid rows",
  duplicates: "duplicates",
  line: "Line",
  duplicate: "Duplicate, skipped",
  valid: "Ready to import",
  confirmImport: "Confirm import",
  imported: "transactions imported",
  csvHint: "Maximum 1 MB and 2,000 rows. Currency must match the account.",
  csvErrors: "Correct these rows before importing.",
  fileTooLarge: "The file exceeds the 1 MB limit.",
  invalidCsv: "The row contains invalid data.",
  spendingIntro:
    "What came in, what went out, and where it went, month by month.",
  month: "Month",
  categories: "By category",
  merchants: "Top merchants",
  periodTotals: "Monthly totals",
  noSpending: "No spending in this period.",
  spendingNote:
    "Refunds reduce spending. Transfers and pending transactions are excluded.",
  matching: "View transactions for",
  noMerchants: "No merchants in this period.",
  sourceScope: "Figures and categories share the same source and date.",
  checking: "Checking",
  savings: "Savings",
  credit_card: "Credit card",
  loan: "Loan",
  investment: "Investment",
  cash: "Cash",
  expense: "Expense",
  refund: "Refund",
  transfer: "Transfer",
  adjustment: "Adjustment",
  groceries: "Groceries",
  dining: "Dining",
  housing: "Housing",
  transport: "Transport",
  utilities: "Utilities",
  health: "Health",
  shopping: "Shopping",
  entertainment: "Entertainment",
  travel: "Travel",
  education: "Education",
  insurance: "Insurance",
  other: "Other",
};
export const copy = (locale: Locale) => (locale === "en" ? en : es);
export function categoryLabel(value: string, locale: Locale) {
  const catalog = copy(locale);
  return catalog[value as keyof typeof catalog] || value;
}
export function dateLabel(value: string, locale: Locale) {
  return new Intl.DateTimeFormat(locale, {
    dateStyle: "medium",
    timeZone: "UTC",
  }).format(new Date(value.length === 10 ? `${value}T12:00:00Z` : value));
}
