import type { Locale } from "../../platform/types";

const es = {
  accounts: "Cuentas",
  accountsIntro: "Cada cuenta, con su saldo y su origen.",
  addAccount: "Agregar cuenta",
  editAccount: "Editar cuenta",
  name: "Nombre",
  institution: "Institución",
  kind: "Tipo",
  currency: "Moneda",
  opening: "Saldo inicial",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Cancelar",
  edit: "Editar",
  remove: "Eliminar",
  restore: "Restaurar",
  deleted: "Eliminada",
  includeDeleted: "Mostrar cuentas eliminadas",
  account: "Cuenta",
  allAccounts: "Todas las cuentas",
  noAccounts: "No hay cuentas en esta moneda.",
  noAccountsDetail: "Agrega una cuenta manual para comenzar tu registro.",
  noConversion:
    "Los saldos se muestran en su moneda original. No se convierten.",
  saved: "Cambios guardados.",
  removed: "Registro eliminado. Puedes restaurarlo.",
  error:
    "No pudimos completar la acción. Revisa los datos e inténtalo de nuevo.",
  loadError: "No pudimos cargar estos registros.",
  retry: "Reintentar",
  loading: "Cargando registros…",
  connectors: "Conexiones de demostración",
  connectorsIntro:
    "Simulaciones locales. No conectan con bancos ni mueven dinero.",
  connect: "Conectar demo",
  refresh: "Simular actualización",
  failSync: "Simular fallo",
  lastGood: "Última actualización correcta",
  never: "Sin actualización",
  failedSync: "La actualización falló. Se conservan los últimos datos.",
  connected: "Conectada",
  deletedExplain:
    "Eliminar oculta esta cuenta y sus movimientos de los totales. Puedes restaurarla después.",
  confirmRemove: "Eliminar cuenta",
  viewTransactions: "Ver movimientos",
  transactions: "Movimientos",
  transactionsIntro: "Encuentra, revisa y organiza tu registro.",
  addTransaction: "Agregar movimiento",
  search: "Buscar comercio o descripción",
  from: "Desde",
  to: "Hasta",
  category: "Categoría",
  allCategories: "Todas las categorías",
  status: "Estado",
  allStatuses: "Todos los estados",
  posted: "Registrado",
  pending: "Pendiente",
  sort: "Orden",
  date_desc: "Más recientes",
  date_asc: "Más antiguos",
  amount_desc: "Importe mayor",
  amount_asc: "Importe menor",
  perPage: "Filas por página",
  previous: "Anterior",
  next: "Siguiente",
  page: "Página",
  of: "de",
  matches: "movimientos coincidentes",
  noTransactions: "No hay movimientos con estos filtros.",
  clearFilters: "Quitar filtros",
  date: "Fecha",
  merchant: "Comercio o concepto",
  description: "Descripción",
  amount: "Importe",
  notes: "Notas",
  details: "Detalles",
  detail: "Detalle del movimiento",
  filteredTotals: "Totales de todos los movimientos filtrados",
  income: "Ingresos",
  spending: "Gastos",
  net: "Neto",
  transferNote:
    "Las transferencias y los movimientos pendientes no cuentan como ingresos o gastos.",
  manualNote:
    "Registro local. Usa importes negativos para gastos y positivos para ingresos.",
  split: "Dividir por categorías",
  addSplit: "Agregar parte",
  removeSplit: "Quitar parte",
  splitNote:
    "Los importes de las partes deben sumar exactamente el importe del movimiento, con el mismo signo.",
  splitTotalError: "Las partes deben sumar el importe del movimiento.",
  reverse: "Crear contrapartida",
  reverseNote:
    "Se guardará un movimiento nuevo con el importe opuesto. El original permanece.",
  deleteTransaction: "Eliminar movimiento",
  deleteTransactionNote:
    "Se excluirá de los totales. Si es una transferencia, se eliminarán ambas partes.",
  undo: "Deshacer eliminación",
  destination: "Cuenta de destino",
  importCsv: "Importar CSV",
  exportCsv: "Exportar CSV",
  sampleCsv: "Descargar ejemplo",
  file: "Archivo CSV",
  csvText: "Contenido CSV",
  preview: "Validar archivo",
  previewTitle: "Revisión de importación",
  newRows: "filas válidas",
  duplicates: "duplicadas",
  line: "Línea",
  duplicate: "Duplicada, se omite",
  valid: "Lista para importar",
  confirmImport: "Confirmar importación",
  imported: "movimientos importados",
  csvHint: "Máximo 1 MB y 2,000 filas. La moneda debe coincidir con la cuenta.",
  csvErrors: "Corrige estas filas antes de importar.",
  fileTooLarge: "El archivo supera el límite de 1 MB.",
  invalidCsv: "La fila contiene datos inválidos.",
  spendingIntro: "Qué entró, qué salió y dónde fue, mes a mes.",
  month: "Mes",
  categories: "Por categoría",
  merchants: "Comercios principales",
  periodTotals: "Totales del mes",
  noSpending: "No hay gastos en este periodo.",
  spendingNote:
    "Los reembolsos reducen los gastos. No se incluyen transferencias ni movimientos pendientes.",
  matching: "Ver movimientos de",
  noMerchants: "No hay comercios en este periodo.",
  sourceScope: "Las cifras y categorías comparten la misma fuente y fecha.",
  checking: "Corriente",
  savings: "Ahorro",
  credit_card: "Tarjeta de crédito",
  loan: "Préstamo",
  investment: "Inversión",
  cash: "Efectivo",
  expense: "Gasto",
  refund: "Reembolso",
  transfer: "Transferencia",
  adjustment: "Ajuste",
  groceries: "Supermercado",
  dining: "Restaurantes",
  housing: "Vivienda",
  transport: "Transporte",
  utilities: "Servicios",
  health: "Salud",
  shopping: "Compras",
  entertainment: "Entretenimiento",
  travel: "Viajes",
  education: "Educación",
  insurance: "Seguros",
  other: "Otros",
};
const en: typeof es = {
  accounts: "Accounts",
  accountsIntro: "Every account, with its balance and source.",
  addAccount: "Add account",
  editAccount: "Edit account",
  name: "Name",
  institution: "Institution",
  kind: "Type",
  currency: "Currency",
  opening: "Opening balance",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  edit: "Edit",
  remove: "Delete",
  restore: "Restore",
  deleted: "Deleted",
  includeDeleted: "Show deleted accounts",
  account: "Account",
  allAccounts: "All accounts",
  noAccounts: "No accounts in this currency.",
  noAccountsDetail: "Add a manual account to start your ledger.",
  noConversion:
    "Balances stay in their original currency. No conversion is applied.",
  saved: "Changes saved.",
  removed: "Record deleted. You can restore it.",
  error: "We could not complete the action. Check the details and try again.",
  loadError: "We could not load these records.",
  retry: "Retry",
  loading: "Loading records…",
  connectors: "Demo connections",
  connectorsIntro:
    "Local simulations. They do not connect to banks or move money.",
  connect: "Connect demo",
  refresh: "Simulate refresh",
  failSync: "Simulate failure",
  lastGood: "Last successful refresh",
  never: "No refresh yet",
  failedSync: "The refresh failed. The last data is preserved.",
  connected: "Connected",
  deletedExplain:
    "Deleting hides this account and its transactions from totals. You can restore it later.",
  confirmRemove: "Delete account",
  viewTransactions: "View transactions",
  transactions: "Transactions",
  transactionsIntro: "Find, review, and organize your ledger.",
  addTransaction: "Add transaction",
  search: "Search merchant or description",
  from: "From",
  to: "To",
  category: "Category",
  allCategories: "All categories",
  status: "Status",
  allStatuses: "All statuses",
  posted: "Posted",
  pending: "Pending",
  sort: "Sort",
  date_desc: "Newest first",
  date_asc: "Oldest first",
  amount_desc: "Largest amount",
  amount_asc: "Smallest amount",
  perPage: "Rows per page",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  matches: "matching transactions",
  noTransactions: "No transactions match these filters.",
  clearFilters: "Clear filters",
  date: "Date",
  merchant: "Merchant or purpose",
  description: "Description",
  amount: "Amount",
  notes: "Notes",
  details: "Details",
  detail: "Transaction detail",
  filteredTotals: "Totals for all matching transactions",
  income: "Income",
  spending: "Spending",
  net: "Net",
  transferNote:
    "Transfers and pending transactions do not count as income or spending.",
  manualNote:
    "Local record. Use negative amounts for expenses and positive amounts for income.",
  split: "Split into categories",
  addSplit: "Add split",
  removeSplit: "Remove split",
  splitNote:
    "Split amounts must add up exactly to the transaction amount, with the same sign.",
  splitTotalError: "Splits must add up to the transaction amount.",
  reverse: "Create reversal",
  reverseNote:
    "A new transaction with the opposite amount will be saved. The original remains.",
  deleteTransaction: "Delete transaction",
  deleteTransactionNote:
    "It will be excluded from totals. For a transfer, both sides will be deleted.",
  undo: "Undo deletion",
  destination: "Destination account",
  importCsv: "Import CSV",
  exportCsv: "Export CSV",
  sampleCsv: "Download example",
  file: "CSV file",
  csvText: "CSV content",
  preview: "Validate file",
  previewTitle: "Import review",
  newRows: "valid rows",
  duplicates: "duplicates",
  line: "Line",
  duplicate: "Duplicate, skipped",
  valid: "Ready to import",
  confirmImport: "Confirm import",
  imported: "transactions imported",
  csvHint: "Maximum 1 MB and 2,000 rows. Currency must match the account.",
  csvErrors: "Correct these rows before importing.",
  fileTooLarge: "The file exceeds the 1 MB limit.",
  invalidCsv: "The row contains invalid data.",
  spendingIntro:
    "What came in, what went out, and where it went, month by month.",
  month: "Month",
  categories: "By category",
  merchants: "Top merchants",
  periodTotals: "Monthly totals",
  noSpending: "No spending in this period.",
  spendingNote:
    "Refunds reduce spending. Transfers and pending transactions are excluded.",
  matching: "View transactions for",
  noMerchants: "No merchants in this period.",
  sourceScope: "Figures and categories share the same source and date.",
  checking: "Checking",
  savings: "Savings",
  credit_card: "Credit card",
  loan: "Loan",
  investment: "Investment",
  cash: "Cash",
  expense: "Expense",
  refund: "Refund",
  transfer: "Transfer",
  adjustment: "Adjustment",
  groceries: "Groceries",
  dining: "Dining",
  housing: "Housing",
  transport: "Transport",
  utilities: "Utilities",
  health: "Health",
  shopping: "Shopping",
  entertainment: "Entertainment",
  travel: "Travel",
  education: "Education",
  insurance: "Insurance",
  other: "Other",
};
export const copy = (locale: Locale) => (locale === "en" ? en : es);
export function categoryLabel(value: string, locale: Locale) {
  const catalog = copy(locale);
  return catalog[value as keyof typeof catalog] || value;
}
export function dateLabel(value: string, locale: Locale) {
  return new Intl.DateTimeFormat(locale, {
    dateStyle: "medium",
    timeZone: "UTC",
  }).format(new Date(value.length === 10 ? `${value}T12:00:00Z` : value));
}

const statementEs = {
  title: "Importar estado de cuenta",
  intro:
    "Agrega movimientos de un banco que no esté conectado. Revisa todo antes de guardar.",
  supported:
    "Archivos CSV y TSV de tu banco, hasta 1 MB y 2,000 filas. PDF, Excel e imágenes todavía no se pueden importar. Descarga la versión CSV o TSV.",
  fileStep: "1. Archivo y cuenta",
  mappingStep: "2. Relacionar columnas",
  reviewStep: "3. Revisar movimientos",
  readColumns: "Leer columnas",
  reading: "Leyendo archivo…",
  paste: "Pegar contenido",
  format: "Formato del archivo",
  delimiter: "Separador de columnas",
  comma: "Coma",
  semicolon: "Punto y coma",
  tab: "Tabulación",
  headerRow: "Fila que contiene los títulos",
  mapIntro:
    "Elige la columna de tu archivo que corresponde a cada dato. La cuenta seleccionada aporta la moneda.",
  column: "Columna",
  choose: "Seleccionar columna",
  notIncluded: "No incluida",
  signed: "Una columna con importe y signo",
  separate: "Columnas separadas de salida y entrada",
  amountLayout: "Cómo aparecen los importes",
  debit: "Salida / débito",
  credit: "Entrada / crédito",
  sourceId: "Identificador del movimiento del banco (opcional)",
  dateFormat: "Formato de fecha",
  ymd: "Año-mes-día (2026-09-20)",
  dmy: "Día/mes/año (20/09/2026)",
  mdy: "Mes/día/año (09/20/2026)",
  decimal: "Separador decimal",
  dotDecimal: "Punto (12.50)",
  commaDecimal: "Coma (12,50)",
  decimalHelp:
    "Sin separadores de miles. Si el banco los incluye, elimínalos en el archivo antes de importar.",
  optional: "Más columnas (opcional)",
  positiveKind: "Cómo registrar las entradas sin tipo en el archivo",
  chooseKind: "Elegir si el archivo contiene entradas",
  positiveHelp:
    "Esta elección se aplica a todas las entradas sin tipo. Las transferencias se registran desde el formulario de movimientos.",
  currencyHelp:
    "Sin conversión. Si asignas una columna de moneda, todas sus filas deben coincidir con la cuenta.",
  sourceHelp:
    "Si el banco incluye una referencia única por movimiento, permite reconocer duplicados exactos.",
  kindHelp:
    "Los tipos y categorías del archivo deben usar los códigos del ejemplo de Argus.",
  back: "Atrás",
  prepare: "Preparar revisión",
  exact: "Duplicado exacto, se omite",
  possible: "Parece repetido",
  newRow: "Nuevo",
  decision: "Qué hacer",
  undecided: "Revisar",
  keep: "Importar también",
  skip: "Omitir",
  keepAll: "Importar todos los similares",
  skipAll: "Omitir todos los similares",
  reviewHelp:
    "Dos compras iguales pueden ser distintas. Decide si importar u omitir cada movimiento que parece repetido.",
  reviewRemaining: "movimientos similares pendientes de revisar",
  confirm: "Guardar movimientos revisados",
  expired: "La revisión vence a las",
  imported: "movimientos guardados",
  done: "Listo",
  noFile: "Selecciona un archivo o pega su contenido.",
  invalidFile:
    "No pudimos leer el archivo. Usa CSV o TSV con codificación UTF-8.",
  changed:
    "La revisión cambió o venció. Vuelve atrás y prepara una revisión nueva.",
  empty: "El archivo no tiene movimientos para importar.",
};
const statementEn: typeof statementEs = {
  title: "Import bank statement",
  intro:
    "Add transactions from a bank that is not connected. Review everything before saving.",
  supported:
    "Bank CSV and TSV files, up to 1 MB and 2,000 rows. PDF, Excel, and images cannot be imported yet. Download the CSV or TSV version.",
  fileStep: "1. File and account",
  mappingStep: "2. Match columns",
  reviewStep: "3. Review transactions",
  readColumns: "Read columns",
  reading: "Reading file…",
  paste: "Paste content",
  format: "File format",
  delimiter: "Column separator",
  comma: "Comma",
  semicolon: "Semicolon",
  tab: "Tab",
  headerRow: "Row containing column headings",
  mapIntro:
    "Choose the file column that matches each field. The selected account supplies the currency.",
  column: "Column",
  choose: "Choose column",
  notIncluded: "Not included",
  signed: "One column with signed amounts",
  separate: "Separate money out and money in columns",
  amountLayout: "How amounts appear",
  debit: "Money out / debit",
  credit: "Money in / credit",
  sourceId: "Bank transaction identifier (optional)",
  dateFormat: "Date format",
  ymd: "Year-month-day (2026-09-20)",
  dmy: "Day/month/year (20/09/2026)",
  mdy: "Month/day/year (09/20/2026)",
  decimal: "Decimal separator",
  dotDecimal: "Period (12.50)",
  commaDecimal: "Comma (12,50)",
  decimalHelp:
    "No thousands separators. If your bank includes them, remove them from the file before importing.",
  optional: "More columns (optional)",
  positiveKind: "How to record money in when the file has no type",
  chooseKind: "Choose if the file contains money in",
  positiveHelp:
    "This choice applies to every incoming amount without a type. Record transfers using the transaction form.",
  currencyHelp:
    "No conversion. If you map a currency column, every row must match the account.",
  sourceHelp:
    "A unique transaction reference supplied by the bank identifies exact duplicates.",
  kindHelp: "File types and categories must use the codes in the Argus sample.",
  back: "Back",
  prepare: "Prepare review",
  exact: "Exact duplicate, skipped",
  possible: "Looks repeated",
  newRow: "New",
  decision: "What to do",
  undecided: "Review",
  keep: "Import as well",
  skip: "Skip",
  keepAll: "Import all similar transactions",
  skipAll: "Skip all similar transactions",
  reviewHelp:
    "Two identical purchases may be separate transactions. Choose whether to import or skip each possible repeat.",
  reviewRemaining: "similar transactions still need review",
  confirm: "Save reviewed transactions",
  expired: "Review expires at",
  imported: "transactions saved",
  done: "Done",
  noFile: "Choose a file or paste its content.",
  invalidFile:
    "We could not read the file. Use a UTF-8 encoded CSV or TSV file.",
  changed: "The review changed or expired. Go back and prepare a new review.",
  empty: "The file has no transactions to import.",
};
export const statementCopy = (locale: Locale) =>
  locale === "en" ? statementEn : statementEs;
export function statementError(code: string, locale: Locale) {
  const errors: Record<string, [string, string]> = {
    unsupported_statement_file: [
      "Usa CSV o TSV. PDF, Excel e imágenes todavía no son compatibles.",
      "Use CSV or TSV. PDF, Excel, and images are not supported yet.",
    ],
    invalid_statement_amount: [
      "Revisa el importe y el separador decimal. No se admiten separadores de miles.",
      "Check the amount and decimal separator. Thousands separators are not supported.",
    ],
    invalid_statement_date: [
      "La fecha no coincide con el formato seleccionado.",
      "The date does not match the selected format.",
    ],
    invalid_debit_credit: [
      "Debe haber una sola salida o entrada positiva por fila.",
      "Each row needs only one positive debit or credit.",
    ],
    statement_positive_kind_required: [
      "Elige cómo registrar las entradas o asigna la columna de tipo.",
      "Choose how to record incoming amounts or map the type column.",
    ],
    import_currency_mismatch: [
      "La moneda no coincide con la cuenta seleccionada.",
      "The currency does not match the selected account.",
    ],
    invalid_money_precision: [
      "El importe supera el límite o tiene demasiados decimales para esta moneda.",
      "The amount exceeds the limit or has too many decimal places for this currency.",
    ],
    source_transaction_changed: [
      "La referencia del banco coincide, pero sus datos cambiaron. Revisa este movimiento antes de importar.",
      "The bank reference matches, but its details changed. Check this transaction before importing.",
    ],
    invalid_column_mapping: [
      "Revisa las columnas seleccionadas.",
      "Check the selected columns.",
    ],
    invalid_csv_headers: [
      "Los títulos de columna deben existir y no repetirse. Revisa la fila de títulos y el separador.",
      "Column headings must be present and unique. Check the heading row and separator.",
    ],
    invalid_csv_row: [
      "Revisa los campos de esta fila, su tipo y su categoría.",
      "Check the fields, type, and category in this row.",
    ],
    invalid_category: [
      "El tipo y la categoría deben corresponder a los códigos del ejemplo de Argus.",
      "Type and category must match the codes in the Argus sample.",
    ],
    invalid_csv_quoting: [
      "El archivo contiene comillas incompletas o mal ubicadas.",
      "The file contains incomplete or misplaced quotes.",
    ],
    invalid_csv: [
      "No pudimos leer las filas del archivo. Revisa su formato.",
      "We could not read the file rows. Check the format.",
    ],
    invalid_file_content: [
      "El archivo contiene caracteres no admitidos. Descárgalo como CSV o TSV UTF-8.",
      "The file contains unsupported characters. Download it as UTF-8 CSV or TSV.",
    ],
    invalid_file_encoding: [
      "Descarga el archivo con codificación UTF-8.",
      "Download the file with UTF-8 encoding.",
    ],
    import_too_large: [
      "El archivo supera 1 MB. Divide el archivo antes de importarlo.",
      "The file exceeds 1 MB. Split it before importing.",
    ],
    import_too_many_rows: [
      "El archivo supera 2,000 filas. Divide el periodo antes de importar.",
      "The file exceeds 2,000 rows. Split the period before importing.",
    ],
    import_too_many_columns: [
      "El archivo supera 64 columnas. Conserva las columnas del estado de cuenta.",
      "The file exceeds 64 columns. Keep only the statement columns.",
    ],
    import_cell_too_large: [
      "Una celda supera 4,096 caracteres. Revisa el archivo.",
      "A cell exceeds 4,096 characters. Check the file.",
    ],
    import_review_required: [
      "Decide qué hacer con todos los movimientos similares.",
      "Choose what to do with every similar transaction.",
    ],
    csv_transfer_unsupported: [
      "Registra las transferencias con el formulario de movimientos.",
      "Record transfers using the transaction form.",
    ],
  };
  if (
    [
      "import_preview_changed",
      "import_preview_expired",
      "import_decisions_changed",
    ].includes(code)
  )
    return statementCopy(locale).changed;
  return errors[code]?.[locale === "en" ? 1 : 0] ?? null;
}
