import type { Locale } from '../../platform/types';

const es = {
  title: 'Inversiones',
  intro: 'Revisa tus registros y prueba cambios con dinero ficticio.',
  portfolio: 'Cartera',
  simulation: 'Simulación',
  simulatedBoundary: 'Espacio de práctica local. No conecta con un bróker ni ejecuta operaciones reales.',
  asOf: 'Datos al',
  linkedAccounts: 'Cuentas de inversión',
  linkedIntro: 'Saldos que ya forman parte de tu patrimonio.',
  alternatives: 'Activos alternativos manuales',
  alternativesIntro: 'Registros persistentes fuera de tus cuentas vinculadas.',
  addHolding: 'Agregar activo manual',
  editHolding: 'Editar activo',
  importCsv: 'Importar CSV',
  sampleCsv: 'Descargar ejemplo',
  refreshPrices: 'Actualizar precios demo',
  refreshing: 'Actualizando…',
  summary: 'Resumen por moneda',
  value: 'Valor de cartera',
  linkedValue: 'Cuentas vinculadas',
  alternativeValue: 'Alternativos con precio',
  cost: 'Costo registrado',
  gainLoss: 'Ganancia o pérdida',
  allocation: 'Asignación',
  quantity: 'Cantidad',
  price: 'Precio',
  marketValue: 'Valor actual',
  unavailable: 'No disponible',
  partial: 'Total parcial. Hay activos sin precio fechado.',
  noLinked: 'No hay cuentas de inversión registradas.',
  noAlternatives: 'Aún no hay activos alternativos.',
  noAlternativesHelp: 'Agrega un registro manual o importa un archivo CSV.',
  benchmarks: 'Referencias de rendimiento',
  benchmarkIntro: 'Comparación ilustrativa, separada de tu rendimiento personal.',
  start: 'Inicio',
  end: 'Final',
  return: 'Cambio',
  performanceChart: 'Cambio de precio de referencia',
  chartDescription: 'Gráfico de dos puntos con el precio inicial y final. La tabla siguiente contiene los mismos valores.',
  symbol: 'Símbolo',
  name: 'Nombre',
  currency: 'Moneda',
  date: 'Fecha',
  save: 'Guardar registro',
  saving: 'Guardando…',
  cancel: 'Cancelar',
  close: 'Cerrar',
  edit: 'Editar',
  remove: 'Eliminar',
  removeTitle: 'Eliminar activo manual',
  removeBody: 'Se quitará este registro de la cartera y de sus totales.',
  confirmRemove: 'Eliminar registro',
  loadError: 'No pudimos cargar la cartera.',
  retry: 'Volver a cargar',
  loading: 'Cargando tus inversiones…',
  genericError: 'No pudimos completar la acción. Revisa los datos e inténtalo de nuevo.',
  readOnlyError: 'Tu rol no permite guardar cambios.',
  staleQuote: 'El precio de esta vista previa ya venció. Crea una nueva.',
  insufficientCash: 'El saldo ficticio no alcanza para esta compra simulada.',
  insufficientQuantity: 'La cantidad ficticia disponible no alcanza para esta venta simulada.',
  saved: 'Cambio guardado en esta demostración.',
  csvFile: 'Archivo CSV',
  csvContent: 'Contenido CSV',
  csvHint: 'Máximo 1 MB y 2,000 filas. La vista previa no cambia tus registros.',
  previewImport: 'Validar archivo',
  previewTitle: 'Revisión de importación',
  validRows: 'filas válidas',
  duplicates: 'duplicadas',
  rowStatus: 'Estado',
  ready: 'Lista',
  importErrors: 'Corrige las filas indicadas antes de importar.',
  commitImport: 'Confirmar importación',
  imported: 'Activos importados',
  fileTooLarge: 'El archivo supera el límite de 1 MB.',
  fictionalCash: 'Efectivo ficticio',
  initialCash: 'Efectivo inicial',
  practicePositions: 'Posiciones ficticias',
  noPositions: 'Aún no hay posiciones ficticias.',
  simulateChange: 'Simular cambio',
  newSimulation: 'Nueva simulación',
  buy: 'Compra',
  sell: 'Venta',
  side: 'Acción ficticia',
  target: 'Tipo',
  singleAsset: 'Activo',
  curatedBundle: 'Conjunto curado',
  book: 'Cuenta ficticia',
  amount: 'Importe',
  preview: 'Crear vista previa',
  previewing: 'Calculando…',
  previewReady: 'Vista previa de operación ficticia',
  gross: 'Importe bruto',
  roundingCost: 'Costo exacto de redondeo',
  roundingRule: 'Regla de liquidación',
  roundingRuleDetail: 'Las compras se liquidan hacia arriba y las ventas hacia abajo en la unidad mínima de la moneda.',
  fee: 'Costo modelado',
  cashEffect: 'Cambio en efectivo',
  expires: 'Vence',
  confirmSimulation: 'Confirmar en simulación',
  confirming: 'Confirmando…',
  confirmedReceipt: 'Recibo guardado',
  cashBefore: 'Efectivo anterior',
  cashAfter: 'Efectivo restante',
  confirmedAt: 'Confirmado',
  recentOrders: 'Recibos recientes',
  noOrders: 'No hay operaciones ficticias confirmadas.',
  bundles: 'Conjuntos curados',
  bundleIntro: 'Ejemplos sintéticos para aprender. No son recomendaciones.',
  useBundle: 'Usar en simulación',
  weight: 'peso',
  recurring: 'Planes recurrentes',
  recurringIntro: 'Cada ejecución usa efectivo y precios ficticios del simulador.',
  createPlan: 'Crear plan recurrente',
  cadence: 'Frecuencia',
  weekly: 'Semanal',
  monthly: 'Mensual',
  nextRun: 'Próxima ejecución',
  active: 'Activo',
  paused: 'En pausa',
  pause: 'Pausar',
  resume: 'Reanudar',
  runPeriod: 'Ejecutar periodo',
  running: 'Ejecutando…',
  noPlans: 'No hay planes recurrentes.',
  runSaved: 'Ejecución guardada. Un periodo nunca se duplica.',
};

const en: typeof es = {
  title: 'Investments',
  intro: 'Review your records and try changes with fictional money.',
  portfolio: 'Portfolio',
  simulation: 'Simulation',
  simulatedBoundary: 'Local practice workspace. It does not connect to a broker or execute real trades.',
  asOf: 'Data as of',
  linkedAccounts: 'Investment accounts',
  linkedIntro: 'Balances already included in your net worth.',
  alternatives: 'Manual alternative assets',
  alternativesIntro: 'Persistent records outside your linked accounts.',
  addHolding: 'Add manual asset',
  editHolding: 'Edit asset',
  importCsv: 'Import CSV',
  sampleCsv: 'Download example',
  refreshPrices: 'Refresh demo prices',
  refreshing: 'Refreshing…',
  summary: 'Summary by currency',
  value: 'Portfolio value',
  linkedValue: 'Linked accounts',
  alternativeValue: 'Priced alternatives',
  cost: 'Recorded cost',
  gainLoss: 'Gain or loss',
  allocation: 'Allocation',
  quantity: 'Quantity',
  price: 'Price',
  marketValue: 'Current value',
  unavailable: 'Unavailable',
  partial: 'Partial total. Some assets have no dated price.',
  noLinked: 'No investment accounts are recorded.',
  noAlternatives: 'No alternative assets yet.',
  noAlternativesHelp: 'Add a manual record or import a CSV file.',
  benchmarks: 'Performance references',
  benchmarkIntro: 'Illustrative comparison, separate from your personal performance.',
  start: 'Start',
  end: 'End',
  return: 'Change',
  performanceChart: 'Reference price change',
  chartDescription: 'Two-point chart with the starting and ending price. The following table contains the same values.',
  symbol: 'Symbol',
  name: 'Name',
  currency: 'Currency',
  date: 'Date',
  save: 'Save record',
  saving: 'Saving…',
  cancel: 'Cancel',
  close: 'Close',
  edit: 'Edit',
  remove: 'Delete',
  removeTitle: 'Delete manual asset',
  removeBody: 'This record will be removed from the portfolio and its totals.',
  confirmRemove: 'Delete record',
  loadError: 'We could not load the portfolio.',
  retry: 'Reload',
  loading: 'Loading your investments…',
  genericError: 'We could not complete the action. Check the details and try again.',
  readOnlyError: 'Your role cannot save changes.',
  staleQuote: 'This preview price has expired. Create a new one.',
  insufficientCash: 'The fictional cash balance is not enough for this simulated purchase.',
  insufficientQuantity: 'The fictional quantity is not enough for this simulated sale.',
  saved: 'Change saved in this demonstration.',
  csvFile: 'CSV file',
  csvContent: 'CSV content',
  csvHint: 'Maximum 1 MB and 2,000 rows. Previewing does not change your records.',
  previewImport: 'Validate file',
  previewTitle: 'Import review',
  validRows: 'valid rows',
  duplicates: 'duplicates',
  rowStatus: 'Status',
  ready: 'Ready',
  importErrors: 'Correct the listed rows before importing.',
  commitImport: 'Confirm import',
  imported: 'Assets imported',
  fileTooLarge: 'The file exceeds the 1 MB limit.',
  fictionalCash: 'Fictional cash',
  initialCash: 'Initial cash',
  practicePositions: 'Fictional positions',
  noPositions: 'No fictional positions yet.',
  simulateChange: 'Simulate change',
  newSimulation: 'New simulation',
  buy: 'Buy',
  sell: 'Sell',
  side: 'Fictional action',
  target: 'Type',
  singleAsset: 'Asset',
  curatedBundle: 'Curated bundle',
  book: 'Fictional account',
  amount: 'Amount',
  preview: 'Create preview',
  previewing: 'Calculating…',
  previewReady: 'Fictional order preview',
  gross: 'Gross amount',
  roundingCost: 'Exact rounding cost',
  roundingRule: 'Settlement rule',
  roundingRuleDetail: "Buys settle upward and sells downward at the currency's minor unit.",
  fee: 'Modeled cost',
  cashEffect: 'Cash change',
  expires: 'Expires',
  confirmSimulation: 'Confirm in simulation',
  confirming: 'Confirming…',
  confirmedReceipt: 'Saved receipt',
  cashBefore: 'Cash before',
  cashAfter: 'Cash remaining',
  confirmedAt: 'Confirmed',
  recentOrders: 'Recent receipts',
  noOrders: 'No fictional orders have been confirmed.',
  bundles: 'Curated bundles',
  bundleIntro: 'Synthetic learning examples. They are not recommendations.',
  useBundle: 'Use in simulation',
  weight: 'weight',
  recurring: 'Recurring plans',
  recurringIntro: 'Each run uses fictional cash and prices in the simulator.',
  createPlan: 'Create recurring plan',
  cadence: 'Cadence',
  weekly: 'Weekly',
  monthly: 'Monthly',
  nextRun: 'Next run',
  active: 'Active',
  paused: 'Paused',
  pause: 'Pause',
  resume: 'Resume',
  runPeriod: 'Run period',
  running: 'Running…',
  noPlans: 'No recurring plans.',
  runSaved: 'Run saved. A period is never duplicated.',
};

export const copy = (locale: Locale) => locale === 'en' ? en : es;

export function dateLabel(value: string, locale: Locale) {
  const parsed = new Date(value.length === 10 ? `${value}T12:00:00Z` : value);
  return Number.isNaN(parsed.valueOf())
    ? value
    : new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: 'UTC' }).format(parsed);
}

export function dateTimeLabel(value: string, locale: Locale) {
  const parsed = new Date(value);
  return Number.isNaN(parsed.valueOf())
    ? value
    : new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }).format(parsed);
}

export function percentLabel(value: string | null, locale: Locale) {
  if (value === null || !Number.isFinite(Number(value))) return null;
  return new Intl.NumberFormat(locale, { style: 'percent', maximumFractionDigits: 2 }).format(Number(value) / 100);
}

export function exactCurrencyLabel(amount: string, currency: string) {
  return `${currency} ${amount}`;
}
