var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dev/bottom-sheet/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xsehr4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0e1~81g.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rnk4i0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tz4w46._.js")
R.c("server/chunks/ssr/_02p6a15._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_dev_bottom-sheet_page_actions_03hp76l.js")
R.m(854)
module.exports=R.m(854).exports
