import type { Locale } from '../../platform/types';

const es = {
  title: 'Argus',
  subtitle: 'Tus preguntas y registros, en una sola conversación.',
  newChat: 'Nueva conversación',
  emptyTitle: '¿Qué quieres revisar?',
  emptyBody: 'Pregunta por tus registros o prueba uno de los ejemplos preparados.',
  examples: 'Prueba una pregunta',
  freeTextUnavailable: 'La interpretación de texto no está disponible. Los ejemplos preparados siguen funcionando con tus registros.',
  composerPlaceholder: 'Pregunta a Argus',
  loading: 'Cargando conversación…',
  loadError: 'No se pudo abrir esta conversación.',
  retry: 'Reintentar',
  reload: 'Recargar conversación',
  sendError: 'No se pudo enviar el mensaje. Tu borrador sigue aquí.',
  interrupted: 'La respuesta se interrumpió. Puedes reintentar el mismo turno.',
  modelUnavailable: 'La interpretación de texto no está disponible ahora. Puedes usar un ejemplo preparado.',
  failed: 'Argus no pudo completar este turno.',
  inProgress: 'Este turno sigue en curso. Recarga la conversación para ver su estado.',
  understanding: 'Entendiendo tu solicitud…',
  executing: 'Revisando tus registros…',
  stop: 'Detener',
  jumpLatest: 'Ir a lo más reciente',
  openRecord: 'Abrir registro',
  partial: 'Total parcial: faltan precios para algunos activos.',
  noFacts: 'No hay registros para esta consulta.',
  accountsRead: 'Cuentas',
  transactionsRead: 'Movimientos',
  recordsRange: 'Registros',
  previousRecords: 'Registros anteriores',
  nextRecords: 'Registros siguientes',
  calculation: 'Cálculo',
  showNumbers: 'Mostrar cifras e insumos',
  hideNumbers: 'Ocultar cifras e insumos',
  inputs: 'Insumos',
  previousResult: 'El resultado guardado sigue visible mientras revisas los cambios.',
  updateResult: 'Actualizar cálculo',
  updating: 'Actualizando…',
  proposal: 'Cambio propuesto',
  proposedOnly: 'Nada se guardará hasta que confirmes este cambio.',
  fieldMissing: 'Este dato falta. Complétalo antes de confirmar.',
  edit: 'Editar',
  saveEdits: 'Guardar cambios',
  cancelEdit: 'Cancelar edición',
  confirm: 'Confirmar cambio',
  confirming: 'Confirmando…',
  cancelProposal: 'Cancelar propuesta',
  cancelling: 'Cancelando…',
  expired: 'Esta propuesta venció. Pide una propuesta nueva.',
  proposalChanged: 'La propuesta cambió en otra vista. Recargamos la versión vigente.',
  receipt: 'Cambio guardado',
  receiptDetail: 'Recibo local e inmutable',
  savedAt: 'Guardado',
  source: 'Fuente',
  currencySource: 'Origen de la moneda',
  currencyAccount: 'Cuenta',
  currencyRecord: 'Registro',
  currencyExplicit: 'Indicada en la solicitud',
  currencyDefault: 'Preferencia de moneda de la interfaz',
  paperOnly: 'Simulación local solamente. No envía dinero ni se conecta con un bróker.',
  openArtifact: 'Abrir el registro guardado',
  conversationMenu: 'Acciones de conversación',
  rename: 'Renombrar',
  pin: 'Fijar',
  unpin: 'Quitar de fijadas',
  archive: 'Archivar',
  trash: 'Mover a papelera',
  restore: 'Restaurar',
  titleLabel: 'Título',
  save: 'Guardar',
  cancel: 'Cancelar',
  active: 'Activas',
  archived: 'Archivadas',
  trashed: 'Papelera',
  recent: 'Conversaciones recientes',
  noConversations: 'Todavía no hay conversaciones.',
  older: 'Cargar anteriores',
  legacyTitle: 'Conversación anterior',
  legacyBody: 'Esta respuesta se conserva con las cifras y fechas que tenía al guardarse.',
  legacyOpenSaved: 'Abrir en guardadas',
  legacyExport: 'Descargar copia local',
  legacyExportError: 'No se pudo descargar la copia local.',
  exportTooLarge: 'La conversación es demasiado grande para descargarla completa.',
  continueNew: 'Continuar en una conversación nueva',
  legacyBacklink: 'Esta conversación nueva comenzó desde una respuesta anterior. Argus no incorpora esa respuesta como contexto automáticamente.',
  openLegacy: 'Abrir respuesta anterior',
  attachContext: 'El archivo se revisa en Movimientos. Su contenido no se envía al modelo.',
  referenceError: 'No se pudieron cargar tus registros para mencionarlos.',
  draftRestored: 'Se restauró tu borrador.',
  genericError: 'No se pudo completar la acción. Inténtalo de nuevo.',
  invalidResponse: 'Argus recibió una respuesta que no pudo validar.',
  conversationInactive: 'Esta conversación está archivada o en la papelera. Restáurala para continuar.',
  conversationBusy: 'Esta conversación ya está procesando otro turno.',
  contextTooLarge: 'La solicitud incluye demasiado contexto. Reduce los registros mencionados.',
  currencyMismatch: 'La moneda indicada no coincide con la cuenta o el registro seleccionado. Revisa la propuesta antes de continuar.',
  fieldListHelp: 'Un valor por línea.',
  yes: 'Sí',
  no: 'No',
};

const en: typeof es = {
  title: 'Argus',
  subtitle: 'Your questions and records, in one conversation.',
  newChat: 'New conversation',
  emptyTitle: 'What would you like to review?',
  emptyBody: 'Ask about your records or try one of the prepared examples.',
  examples: 'Try a question',
  freeTextUnavailable: 'Text interpretation is unavailable. Prepared examples still work with your records.',
  composerPlaceholder: 'Ask Argus',
  loading: 'Loading conversation…',
  loadError: 'This conversation could not be opened.',
  retry: 'Retry',
  reload: 'Reload conversation',
  sendError: 'Your message could not be sent. Your draft is still here.',
  interrupted: 'The response was interrupted. You can retry the same turn.',
  modelUnavailable: 'Text interpretation is unavailable right now. You can use a prepared example.',
  failed: 'Argus could not complete this turn.',
  inProgress: 'This turn is still running. Reload the conversation to check its status.',
  understanding: 'Understanding your request…',
  executing: 'Reviewing your records…',
  stop: 'Stop',
  jumpLatest: 'Jump to latest',
  openRecord: 'Open record',
  partial: 'Partial total: some assets do not have prices.',
  noFacts: 'There are no records for this question.',
  accountsRead: 'Accounts',
  transactionsRead: 'Transactions',
  recordsRange: 'Records',
  previousRecords: 'Previous records',
  nextRecords: 'Next records',
  calculation: 'Calculation',
  showNumbers: 'Show numbers and inputs',
  hideNumbers: 'Hide numbers and inputs',
  inputs: 'Inputs',
  previousResult: 'The saved result remains visible while you review changes.',
  updateResult: 'Update calculation',
  updating: 'Updating…',
  proposal: 'Proposed change',
  proposedOnly: 'Nothing is saved until you confirm this change.',
  fieldMissing: 'This field is missing. Complete it before confirming.',
  edit: 'Edit',
  saveEdits: 'Save changes',
  cancelEdit: 'Cancel editing',
  confirm: 'Confirm change',
  confirming: 'Confirming…',
  cancelProposal: 'Cancel proposal',
  cancelling: 'Cancelling…',
  expired: 'This proposal expired. Ask for a new proposal.',
  proposalChanged: 'The proposal changed in another view. We reloaded the current version.',
  receipt: 'Change saved',
  receiptDetail: 'Local immutable receipt',
  savedAt: 'Saved',
  source: 'Source',
  currencySource: 'Currency source',
  currencyAccount: 'Account',
  currencyRecord: 'Record',
  currencyExplicit: 'Stated in the request',
  currencyDefault: 'Currency preference from the app',
  paperOnly: 'Local simulation only. It does not send money or connect to a broker.',
  openArtifact: 'Open the saved record',
  conversationMenu: 'Conversation actions',
  rename: 'Rename',
  pin: 'Pin',
  unpin: 'Unpin',
  archive: 'Archive',
  trash: 'Move to trash',
  restore: 'Restore',
  titleLabel: 'Title',
  save: 'Save',
  cancel: 'Cancel',
  active: 'Active',
  archived: 'Archived',
  trashed: 'Trash',
  recent: 'Recent conversations',
  noConversations: 'There are no conversations yet.',
  older: 'Load older',
  legacyTitle: 'Earlier conversation',
  legacyBody: 'This answer keeps the figures and dates it had when it was saved.',
  legacyOpenSaved: 'Open in Saved',
  legacyExport: 'Download local copy',
  legacyExportError: 'The local copy could not be downloaded.',
  exportTooLarge: 'This conversation is too large to download in full.',
  continueNew: 'Continue in a new conversation',
  legacyBacklink: 'This new conversation started from an earlier answer. Argus does not automatically include that answer as context.',
  openLegacy: 'Open earlier answer',
  attachContext: 'The file is reviewed in Transactions. Its contents are not sent to the model.',
  referenceError: 'Your records could not be loaded for mentions.',
  draftRestored: 'Your draft was restored.',
  genericError: 'The action could not be completed. Try again.',
  invalidResponse: 'Argus received a response it could not validate.',
  conversationInactive: 'This conversation is archived or in the trash. Restore it to continue.',
  conversationBusy: 'This conversation is already processing another turn.',
  contextTooLarge: 'This request includes too much context. Mention fewer records.',
  currencyMismatch: 'The stated currency does not match the selected account or record. Review the proposal before continuing.',
  fieldListHelp: 'One value per line.',
  yes: 'Yes',
  no: 'No',
};

export const copy = (locale: Locale) => locale === 'en' ? en : es;

const commandTitles: Record<Locale, Record<string, string>> = {
  'es-419': {
    'account.create': 'Crear cuenta', 'account.edit': 'Editar cuenta',
    'transaction.create': 'Registrar movimiento', 'transaction.edit': 'Editar movimiento',
    'budget.create': 'Crear presupuesto', 'budget.edit': 'Editar presupuesto',
    'bill.create': 'Crear pago recurrente', 'bill.edit': 'Editar pago recurrente',
    'goal.create': 'Crear meta', 'goal.edit': 'Editar meta', 'goal.allocate': 'Asignar cuentas a la meta',
    'scenario.create': 'Guardar escenario', 'holding.create': 'Agregar activo manual', 'holding.edit': 'Editar activo manual',
    'credit.create': 'Agregar cuenta de crédito', 'credit.edit': 'Editar cuenta de crédito',
    'tax.organizer.create': 'Crear carpeta fiscal', 'tax.scenario': 'Guardar escenario fiscal',
    'estate.asset.create': 'Agregar activo patrimonial', 'estate.contact.create': 'Agregar contacto',
    'estate.beneficiaries.set': 'Asignar beneficiarios', 'memory.create': 'Guardar recuerdo confirmado',
    'memory.edit': 'Editar recuerdo confirmado', 'tax.item.create': 'Agregar elemento fiscal',
    'estate.document.create': 'Agregar documento patrimonial', 'estate.checklist.create': 'Agregar tarea patrimonial',
    'investing.recurring.create': 'Crear plan de inversión simulado', 'bill.payment.record': 'Registrar pago de factura',
  },
  en: {
    'account.create': 'Create account', 'account.edit': 'Edit account',
    'transaction.create': 'Record transaction', 'transaction.edit': 'Edit transaction',
    'budget.create': 'Create budget', 'budget.edit': 'Edit budget',
    'bill.create': 'Create recurring bill', 'bill.edit': 'Edit recurring bill',
    'goal.create': 'Create goal', 'goal.edit': 'Edit goal', 'goal.allocate': 'Allocate accounts to goal',
    'scenario.create': 'Save scenario', 'holding.create': 'Add manual asset', 'holding.edit': 'Edit manual asset',
    'credit.create': 'Add credit account', 'credit.edit': 'Edit credit account',
    'tax.organizer.create': 'Create tax folder', 'tax.scenario': 'Save tax scenario',
    'estate.asset.create': 'Add estate asset', 'estate.contact.create': 'Add contact',
    'estate.beneficiaries.set': 'Set beneficiaries', 'memory.create': 'Save confirmed memory',
    'memory.edit': 'Edit confirmed memory', 'tax.item.create': 'Add tax item',
    'estate.document.create': 'Add estate document', 'estate.checklist.create': 'Add estate task',
    'investing.recurring.create': 'Create simulated investment plan', 'bill.payment.record': 'Record bill payment',
  },
};

const fieldLabels: Record<Locale, Record<string, string>> = {
  'es-419': {
    name:'Nombre', institution:'Institución', kind:'Tipo', currency:'Moneda', opening_balance:'Saldo inicial', record_id:'Registro', net_worth:'Patrimonio neto', assets:'Activos', liabilities:'Pasivos', spending:'Gastos', net:'Flujo neto', budget_review:'Revisión del presupuesto', goal_progress:'Progreso de metas', portfolio_review:'Revisión de inversiones', credit_review:'Revisión de crédito', income:'Ingresos', actual:'Gasto real', allocated:'Asignado', remaining:'Disponible', linked_accounts:'Cuentas vinculadas', priced_alternatives:'Activos alternativos con precio', portfolio_value:'Valor de la cartera', credit_score:'Puntaje de crédito', progress_pct:'Progreso', market_value:'Valor de mercado', gain_loss:'Ganancia o pérdida', utilization_pct:'Uso de crédito',
    account_id:'Cuenta', date:'Fecha', merchant:'Comercio', description:'Descripción', amount:'Importe', category:'Categoría', status:'Estado', notes:'Notas', splits:'Divisiones', to_account_id:'Cuenta de destino',
    month:'Mes', limit:'Límite', cadence:'Frecuencia', anchor_date:'Fecha inicial', target_date:'Fecha objetivo', target_amount:'Importe objetivo', monthly_contribution:'Aporte mensual', allocations:'Asignaciones',
    template:'Plantilla', initial_balance:'Saldo inicial', monthly_withdrawal:'Retiro mensual', horizon_years:'Horizonte en años', annual_return_pct:'Rendimiento anual', inflation_pct:'Inflación', annual_fee_pct:'Costo anual', contribution_start_month:'Inicio de aportes', contribution_end_month:'Fin de aportes', withdrawal_start_month:'Inicio de retiros', withdrawal_end_month:'Fin de retiros', timing:'Momento del flujo',
    symbol:'Símbolo', quantity:'Cantidad', total_cost:'Costo total', as_of:'Fecha del registro', balance:'Saldo', credit_limit:'Límite de crédito', apr_pct:'Tasa anual', minimum_payment:'Pago mínimo', country:'País', year:'Año', organizer_id:'Carpeta fiscal', user_rate_pct:'Tasa indicada', value:'Valor', relationship:'Relación', email:'Correo', shares:'Participaciones', content:'Contenido', confirmed:'Confirmado', scope:'Alcance de ejecución', real_money:'Dinero real', scheduled_after_confirmation:'Programado después de confirmar', reference:'Referencia', bill_id:'Factura', payment_date:'Fecha de pago',
  },
  en: {
    name:'Name', institution:'Institution', kind:'Type', currency:'Currency', opening_balance:'Opening balance', record_id:'Record', net_worth:'Net worth', assets:'Assets', liabilities:'Liabilities', spending:'Spending', net:'Net cash flow', budget_review:'Budget review', goal_progress:'Goal progress', portfolio_review:'Investment review', credit_review:'Credit review', income:'Income', actual:'Actual spending', allocated:'Allocated', remaining:'Available', linked_accounts:'Linked accounts', priced_alternatives:'Priced alternative assets', portfolio_value:'Portfolio value', credit_score:'Credit score', progress_pct:'Progress', market_value:'Market value', gain_loss:'Gain or loss', utilization_pct:'Credit use',
    account_id:'Account', date:'Date', merchant:'Merchant', description:'Description', amount:'Amount', category:'Category', status:'Status', notes:'Notes', splits:'Splits', to_account_id:'Destination account',
    month:'Month', limit:'Limit', cadence:'Cadence', anchor_date:'Start date', target_date:'Target date', target_amount:'Target amount', monthly_contribution:'Monthly contribution', allocations:'Allocations',
    template:'Template', initial_balance:'Initial balance', monthly_withdrawal:'Monthly withdrawal', horizon_years:'Horizon in years', annual_return_pct:'Annual return', inflation_pct:'Inflation', annual_fee_pct:'Annual fee', contribution_start_month:'Contribution start', contribution_end_month:'Contribution end', withdrawal_start_month:'Withdrawal start', withdrawal_end_month:'Withdrawal end', timing:'Cash-flow timing',
    symbol:'Symbol', quantity:'Quantity', total_cost:'Total cost', as_of:'Record date', balance:'Balance', credit_limit:'Credit limit', apr_pct:'Annual rate', minimum_payment:'Minimum payment', country:'Country', year:'Year', organizer_id:'Tax folder', user_rate_pct:'Stated rate', value:'Value', relationship:'Relationship', email:'Email', shares:'Shares', content:'Content', confirmed:'Confirmed', scope:'Execution scope', real_money:'Real money', scheduled_after_confirmation:'Scheduled after confirmation', reference:'Reference', bill_id:'Bill', payment_date:'Payment date',
  },
};

const enumLabels: Record<Locale, Record<string, string>> = {
  'es-419': { checking:'Corriente', savings:'Ahorros', credit_card:'Tarjeta de crédito', loan:'Préstamo', investment:'Inversión', cash:'Efectivo', expense:'Gasto', income:'Ingreso', refund:'Reembolso', transfer:'Transferencia', adjustment:'Ajuste', posted:'Contabilizado', pending:'Pendiente', weekly:'Semanal', monthly:'Mensual', quarterly:'Trimestral', yearly:'Anual', home:'Vivienda', kids:'Hijos', job:'Trabajo', move:'Mudanza', marriage:'Matrimonio', retirement:'Retiro', sabbatical:'Año sabático', begin:'Al inicio', end:'Al final', local_record:'Registro local', scheduled_paper:'Simulación programada', recorded_bill_payment:'Pago de factura registrado' },
  en: { checking:'Checking', savings:'Savings', credit_card:'Credit card', loan:'Loan', investment:'Investment', cash:'Cash', expense:'Expense', income:'Income', refund:'Refund', transfer:'Transfer', adjustment:'Adjustment', posted:'Posted', pending:'Pending', weekly:'Weekly', monthly:'Monthly', quarterly:'Quarterly', yearly:'Yearly', home:'Home', kids:'Children', job:'Job', move:'Move', marriage:'Marriage', retirement:'Retirement', sabbatical:'Sabbatical', begin:'At the beginning', end:'At the end', local_record:'Local record', scheduled_paper:'Scheduled simulation', recorded_bill_payment:'Recorded bill payment' },
};

export function commandTitle(key: string, locale: Locale) {
  return commandTitles[locale][key] ?? key.replaceAll('.', ' ');
}

export function commandFieldLabel(key: string, locale: Locale) {
  const leaf = key.split('.').at(-1) ?? key;
  return fieldLabels[locale][leaf] ?? leaf.replaceAll('_', ' ');
}

export function enumValueLabel(value: string, locale: Locale) {
  return enumLabels[locale][value] ?? value.replaceAll('_', ' ');
}

export function dateLabel(value: string, locale: Locale, includeTime = false) {
  const parsed = new Date(value.length === 10 ? `${value}T12:00:00Z` : value);
  if (Number.isNaN(parsed.valueOf())) return value;
  return new Intl.DateTimeFormat(locale, {
    dateStyle: 'medium',
    ...(includeTime ? { timeStyle: 'short' as const } : {}),
    timeZone: 'UTC',
  }).format(parsed);
}
