// Adapted from web/public/locales/{en,es-419}/common.json.
// Calculation cards keep the same backend-owned locale keys as Argus.
import type { Locale } from '../../platform/types';
import type { LocalizedText } from './contracts';

const messages: Record<Locale, Record<string, string>> = {
  "en": {
    "tools.calc.missing_inputs.ask": "To work this out, tell me {{inputs}}.",
    "tools.calc.assumed_inputs.line": "Assumed for this calculation: {{inputs}}.",
    "tools.calc.units.currency": "{{code}}",
    "tools.calc.units.months": "months",
    "tools.calc.units.years": "years",
    "tools.calc.units.multiple": "x",
    "tools.calc.fields.direction": "Plan",
    "tools.calc.fields.present_value": "Starting amount",
    "tools.calc.fields.payment": "Payment per period",
    "tools.calc.fields.future_value": "Ending amount",
    "tools.calc.fields.annual_rate_pct": "Annual rate",
    "tools.calc.fields.periods": "Periods",
    "tools.calc.fields.periods_per_year": "Periods per year",
    "tools.calc.fields.payment_timing": "Payment timing",
    "tools.calc.fields.total_payments": "Total paid in",
    "tools.calc.fields.total_interest": "Total interest",
    "tools.calc.fields.total_growth": "Total growth",
    "tools.calc.fields.start_value": "Starting value",
    "tools.calc.fields.contribution": "Contribution per period",
    "tools.calc.fields.end_value": "Ending value",
    "tools.calc.fields.inflation_rate_pct": "Inflation rate",
    "tools.calc.fields.total_contributed": "Total contributed",
    "tools.calc.fields.growth": "Growth",
    "tools.calc.fields.real_end_value": "Ending value in today's money",
    "tools.calc.fields.real_annual_rate_pct": "Real annual rate",
    "tools.calc.fields.symbol": "Asset",
    "tools.calc.fields.face_value": "Face value",
    "tools.calc.fields.coupon_rate_pct": "Coupon rate",
    "tools.calc.fields.years": "Years",
    "tools.calc.fields.coupons_per_year": "Coupons per year",
    "tools.calc.fields.price": "Price",
    "tools.calc.fields.yield_to_maturity_pct": "Yield to maturity",
    "tools.calc.fields.current_yield_pct": "Current yield",
    "tools.calc.fields.annual_coupon": "Yearly coupon",
    "tools.calc.fields.total_coupons": "Total coupons",
    "tools.calc.fields.total_return": "Total return at maturity",
    "tools.calc.fields.cash_flow": "Cash flow",
    "tools.calc.fields.growth_rate_pct": "Growth rate",
    "tools.calc.fields.discount_rate_pct": "Discount rate",
    "tools.calc.fields.terminal_growth_rate_pct": "Terminal growth rate",
    "tools.calc.fields.value": "Value",
    "tools.calc.fields.cash_flow_at_horizon": "Cash flow at the horizon",
    "tools.calc.fields.per_share": "Per share",
    "tools.calc.fields.multiple": "Multiple",
    "tools.calc.fields.earnings_yield_pct": "Earnings yield",
    "tools.calc.fields.annual_income": "Yearly income",
    "tools.calc.fields.yield_pct": "Yield",
    "tools.calc.fields.monthly_income": "Monthly income",
    "tools.calc.fields.nominal_rate_pct": "Nominal rate",
    "tools.calc.fields.compounding_per_year": "Compounding per year",
    "tools.calc.fields.amount": "Amount",
    "tools.calc.fields.fees": "Fees",
    "tools.calc.fields.effective_rate_pct": "Effective annual rate",
    "tools.calc.fields.total_paid": "Total paid",
    "tools.calc.fields.total_cost": "Total cost",
    "tools.calc.fields.monthly_debt_payments": "Monthly debt payments",
    "tools.calc.fields.ratio_pct": "Ratio",
    "tools.calc.fields.income_after_debt": "Income after debt",
    "tools.calc.fields.assets": "Assets",
    "tools.calc.fields.annual_fee": "Yearly fee",
    "tools.calc.fields.cost_over_years": "Cost over the years",
    "tools.calc.fields.ending_with_fee": "Ending value with the fee",
    "tools.calc.fields.ending_without_fee": "Ending value without the fee",
    "tools.calc.fields.key_label": "Ranked by",
    "tools.calc.fields.prefer": "Prefer",
    "tools.calc.fields.growth_low_pct": "Growth, low case",
    "tools.calc.fields.growth_base_pct": "Growth, base case",
    "tools.calc.fields.growth_high_pct": "Growth, high case",
    "tools.calc.fields.multiple_low": "Multiple, low case",
    "tools.calc.fields.multiple_base": "Multiple, base case",
    "tools.calc.fields.multiple_high": "Multiple, high case",
    "tools.calc.fields.horizon_years": "Horizon",
    "tools.calc.notes.already_covered": "The other inputs already cover this, so nothing more is needed.",
    "tools.calc.notes.single_growth_forecast": "Only one growth forecast was given, so the low and high cases use it too.",
    "tools.calc.notes.current_multiple_held": "No multiple was given, so every case holds today's multiple.",
    "tools.calc.notes.single_multiple": "Only one multiple was given, so the low and high cases use it too.",
    "tools.calc.notes.includes_fees": "The effective rate includes the fees.",
    "tools.calc.notes.ranked_not_recommended": "Ranked by the stated figure only. Nothing here is a recommendation.",
    "tools.calc.notes.scenarios_not_forecasts": "Scenarios are arithmetic on the stated inputs, not forecasts.",
    "tools.calc.repairs.payment_below_interest": "Use a payment that clears the balance",
    "tools.calc.time_value.title_save": "Savings plan",
    "tools.calc.time_value.title_borrow": "Loan",
    "tools.calc.time_value.progress": "Working out the plan",
    "tools.calc.growth_projection.title": "Growth projection",
    "tools.calc.growth_projection.progress": "Projecting the growth",
    "tools.calc.bond_value.title": "Bond value",
    "tools.calc.bond_value.progress": "Pricing the bond",
    "tools.calc.discounted_cash_flow.title": "Discounted cash flow",
    "tools.calc.discounted_cash_flow.progress": "Discounting the cash flows",
    "tools.calc.price_multiple.title": "Price multiple",
    "tools.calc.price_multiple.progress": "Working out the multiple",
    "tools.calc.income_yield.title": "Income yield",
    "tools.calc.income_yield.progress": "Working out the yield",
    "tools.calc.effective_rate.title": "Effective rate",
    "tools.calc.effective_rate.progress": "Working out the effective rate",
    "tools.calc.debt_to_income.title": "Debt to income",
    "tools.calc.debt_to_income.progress": "Working out debt to income",
    "tools.calc.expense_ratio.title": "Expense ratio",
    "tools.calc.expense_ratio.progress": "Working out the fee",
    "tools.calc.ranked_comparison.title": "Ranked by {{key}}",
    "tools.calc.ranked_comparison.progress": "Ranking by {{key_label}}",
    "tools.calc.ranked_comparison.row": "{{rank}}. {{label}}",
    "tools.calc.ranked_comparison.gap": "{{label}}, gap to the best",
    "tools.calc.valuation_scenarios.title": "Valuation scenarios",
    "tools.calc.valuation_scenarios.progress": "Building the scenarios",
    "tools.calc.valuation_scenarios.price_at_horizon_low": "Price at the horizon, low case",
    "tools.calc.valuation_scenarios.price_at_horizon_base": "Price at the horizon, base case",
    "tools.calc.valuation_scenarios.price_at_horizon_high": "Price at the horizon, high case",
    "tools.calc.valuation_scenarios.annual_return_low": "Annual return, low case",
    "tools.calc.valuation_scenarios.annual_return_base": "Annual return, base case",
    "tools.calc.valuation_scenarios.value_at_horizon_low": "Value of the amount at the horizon, low case",
    "tools.calc.valuation_scenarios.value_at_horizon_base": "Value of the amount at the horizon, base case",
    "tools.calc.valuation_scenarios.value_at_horizon_high": "Value of the amount at the horizon, high case",
    "tools.calc.valuation_scenarios.annual_return_high": "Annual return, high case",
    "tools.card.retry": "Retry",
    "tools.card.source.user": "You said it",
    "tools.card.source.page": "{{title}}",
    "tools.card.source.page_dated": "{{title}}, {{date}}",
    "tools.card.source.computed": "Computed from the other inputs",
    "tools.card.source.not_found": "Not found",
    "tools.card.source.market_data": "Argus market data",
    "tools.card.source.market_data_dated": "Argus market data, {{date}}",
    "tools.card.source.assumption": "Assumed in the answer",
    "tools.card.failure.exactly_one_unknown": "Leave exactly one input blank to solve for it.",
    "tools.card.failure.missing_input": "No source supplied the {{field}}. Type it to compute.",
    "tools.card.failure.unknown_argument": "One of these inputs is not part of this calculation.",
    "tools.card.failure.invalid_arguments": "These inputs could not produce a result.",
    "tools.card.failure.tool_execution_failed": "This result is unavailable right now.",
    "tools.card.failure.no_solution": "No {{field}} fits these inputs.",
    "tools.card.failure.payment_never_balances": "With this {{field}}, no number of periods balances the plan.",
    "tools.card.failure.payment_below_interest": "The {{field}} is below the interest each period, so the balance never falls.",
    "tools.card.failure.no_rate_fits": "No {{field}} fits these inputs.",
    "tools.card.failure.rate_out_of_range": "The {{field}} is out of range.",
    "tools.card.failure.division_by_zero": "The {{field}} cannot be zero here.",
    "tools.card.failure.growth_needs_positive_values": "The {{field}} must be above zero.",
    "tools.card.failure.rate_never_reaches_target": "At this {{field}}, the target is never reached.",
    "tools.card.failure.discount_below_terminal_growth": "The {{field}} must be above the terminal growth rate.",
    "tools.card.failure.fees_exceed_amount": "The {{field}} exceed the amount received.",
    "tools.card.failure.no_periods": "The {{field}} must be at least one.",
    "tools.card.failure.periods_not_whole": "The {{field}} must end on a coupon date.",
    "tools.card.failure.scenarios_out_of_order": "The low, base and high cases must rise in order; check the {{field}}.",
    "tools.card.failure.periods_beyond_limit": "With this {{field}}, the plan would take more than 1,200 periods.",
    "tools.card.failure.fee_above_balance": "The {{field}} takes more than the whole balance each year.",
    "tools.card.failure.fees_need_loan_terms": "Add the {{field}} to count the fees in the rate.",
    "tools.card.failure.price_below_zero": "With this {{field}}, the price would be below zero.",
    "tools.card.title": "Result",
    "tools.card.solved_value": "Solved value",
    "tools.card.input": "Input",
    "tools.card.named_input": "Input {{name}}",
    "tools.card.inputs": "Inputs",
    "tools.card.unknown": "To solve",
    "tools.card.show_numbers": "Show the numbers",
    "tools.card.hide_numbers": "Hide the numbers",
    "tools.card.yes": "Yes",
    "tools.card.no": "No",
    "tools.card.unavailable": "This result is unavailable.",
    "tools.card.enter_value": "Enter a value to update this result.",
    "tools.card.recompute_failed": "Could not update this result. Try again.",
    "tools.card.saved_result": "The saved result is shown while your inputs change.",
    "tools.card.updating": "Updating...",
    "tools.card.status.invalid": "These inputs could not produce a result.",
    "tools.card.status.ambiguous": "These inputs have more than one possible answer.",
    "tools.card.status.bounded": "A reliable answer is outside this tool’s limits.",
    "tools.card.status.unavailable": "This result is unavailable right now."
  },
  "es-419": {
    "tools.calc.missing_inputs.ask": "Para calcularlo, dime {{inputs}}.",
    "tools.calc.assumed_inputs.line": "Supuestos de este cálculo: {{inputs}}.",
    "tools.calc.units.currency": "{{code}}",
    "tools.calc.units.months": "meses",
    "tools.calc.units.years": "años",
    "tools.calc.units.multiple": "x",
    "tools.calc.fields.direction": "Plan",
    "tools.calc.fields.present_value": "Monto inicial",
    "tools.calc.fields.payment": "Pago por período",
    "tools.calc.fields.future_value": "Monto final",
    "tools.calc.fields.annual_rate_pct": "Tasa anual",
    "tools.calc.fields.periods": "Períodos",
    "tools.calc.fields.periods_per_year": "Períodos por año",
    "tools.calc.fields.payment_timing": "Momento del pago",
    "tools.calc.fields.total_payments": "Total aportado",
    "tools.calc.fields.total_interest": "Interés total",
    "tools.calc.fields.total_growth": "Crecimiento total",
    "tools.calc.fields.start_value": "Valor inicial",
    "tools.calc.fields.contribution": "Aporte por período",
    "tools.calc.fields.end_value": "Valor final",
    "tools.calc.fields.inflation_rate_pct": "Tasa de inflación",
    "tools.calc.fields.total_contributed": "Total aportado",
    "tools.calc.fields.growth": "Crecimiento",
    "tools.calc.fields.real_end_value": "Valor final en dinero de hoy",
    "tools.calc.fields.real_annual_rate_pct": "Tasa anual real",
    "tools.calc.fields.symbol": "Activo",
    "tools.calc.fields.face_value": "Valor nominal",
    "tools.calc.fields.coupon_rate_pct": "Tasa del cupón",
    "tools.calc.fields.years": "Años",
    "tools.calc.fields.coupons_per_year": "Cupones por año",
    "tools.calc.fields.price": "Precio",
    "tools.calc.fields.yield_to_maturity_pct": "Rendimiento al vencimiento",
    "tools.calc.fields.current_yield_pct": "Rendimiento corriente",
    "tools.calc.fields.annual_coupon": "Cupón anual",
    "tools.calc.fields.total_coupons": "Cupones totales",
    "tools.calc.fields.total_return": "Retorno total al vencimiento",
    "tools.calc.fields.cash_flow": "Flujo de caja",
    "tools.calc.fields.growth_rate_pct": "Tasa de crecimiento",
    "tools.calc.fields.discount_rate_pct": "Tasa de descuento",
    "tools.calc.fields.terminal_growth_rate_pct": "Tasa de crecimiento terminal",
    "tools.calc.fields.value": "Valor",
    "tools.calc.fields.cash_flow_at_horizon": "Flujo de caja en el horizonte",
    "tools.calc.fields.per_share": "Por acción",
    "tools.calc.fields.multiple": "Múltiplo",
    "tools.calc.fields.earnings_yield_pct": "Rendimiento por ganancias",
    "tools.calc.fields.annual_income": "Ingreso anual",
    "tools.calc.fields.yield_pct": "Rendimiento",
    "tools.calc.fields.monthly_income": "Ingreso mensual",
    "tools.calc.fields.nominal_rate_pct": "Tasa nominal",
    "tools.calc.fields.compounding_per_year": "Capitalizaciones por año",
    "tools.calc.fields.amount": "Monto",
    "tools.calc.fields.fees": "Comisiones",
    "tools.calc.fields.effective_rate_pct": "Tasa efectiva anual",
    "tools.calc.fields.total_paid": "Total pagado",
    "tools.calc.fields.total_cost": "Costo total",
    "tools.calc.fields.monthly_debt_payments": "Pagos mensuales de deuda",
    "tools.calc.fields.ratio_pct": "Proporción",
    "tools.calc.fields.income_after_debt": "Ingreso después de la deuda",
    "tools.calc.fields.assets": "Activos",
    "tools.calc.fields.annual_fee": "Comisión anual",
    "tools.calc.fields.cost_over_years": "Costo a lo largo de los años",
    "tools.calc.fields.ending_with_fee": "Valor final con la comisión",
    "tools.calc.fields.ending_without_fee": "Valor final sin la comisión",
    "tools.calc.fields.key_label": "Ordenado por",
    "tools.calc.fields.prefer": "Preferir",
    "tools.calc.fields.growth_low_pct": "Crecimiento, caso bajo",
    "tools.calc.fields.growth_base_pct": "Crecimiento, caso base",
    "tools.calc.fields.growth_high_pct": "Crecimiento, caso alto",
    "tools.calc.fields.multiple_low": "Múltiplo, caso bajo",
    "tools.calc.fields.multiple_base": "Múltiplo, caso base",
    "tools.calc.fields.multiple_high": "Múltiplo, caso alto",
    "tools.calc.fields.horizon_years": "Horizonte",
    "tools.calc.notes.already_covered": "Los otros datos ya cubren esto, así que no hace falta nada más.",
    "tools.calc.notes.single_growth_forecast": "Solo se dio un pronóstico de crecimiento, así que los casos bajo y alto también lo usan.",
    "tools.calc.notes.current_multiple_held": "No se dio un múltiplo, así que cada caso mantiene el múltiplo de hoy.",
    "tools.calc.notes.single_multiple": "Solo se dio un múltiplo, así que los casos bajo y alto también lo usan.",
    "tools.calc.notes.includes_fees": "La tasa efectiva incluye las comisiones.",
    "tools.calc.notes.ranked_not_recommended": "Ordenado solo por la cifra indicada. Nada aquí es una recomendación.",
    "tools.calc.notes.scenarios_not_forecasts": "Los escenarios son aritmética sobre los datos indicados, no pronósticos.",
    "tools.calc.repairs.payment_below_interest": "Usar un pago que sí amortice el saldo",
    "tools.calc.time_value.title_save": "Plan de ahorro",
    "tools.calc.time_value.title_borrow": "Préstamo",
    "tools.calc.time_value.progress": "Calculando el plan",
    "tools.calc.growth_projection.title": "Proyección de crecimiento",
    "tools.calc.growth_projection.progress": "Proyectando el crecimiento",
    "tools.calc.bond_value.title": "Valor del bono",
    "tools.calc.bond_value.progress": "Valuando el bono",
    "tools.calc.discounted_cash_flow.title": "Flujo de caja descontado",
    "tools.calc.discounted_cash_flow.progress": "Descontando los flujos",
    "tools.calc.price_multiple.title": "Múltiplo de precio",
    "tools.calc.price_multiple.progress": "Calculando el múltiplo",
    "tools.calc.income_yield.title": "Rendimiento del ingreso",
    "tools.calc.income_yield.progress": "Calculando el rendimiento",
    "tools.calc.effective_rate.title": "Tasa efectiva",
    "tools.calc.effective_rate.progress": "Calculando la tasa efectiva",
    "tools.calc.debt_to_income.title": "Deuda sobre ingreso",
    "tools.calc.debt_to_income.progress": "Calculando deuda sobre ingreso",
    "tools.calc.expense_ratio.title": "Ratio de gastos",
    "tools.calc.expense_ratio.progress": "Calculando la comisión",
    "tools.calc.ranked_comparison.title": "Ordenado por {{key}}",
    "tools.calc.ranked_comparison.progress": "Ordenando por {{key_label}}",
    "tools.calc.ranked_comparison.row": "{{rank}}. {{label}}",
    "tools.calc.ranked_comparison.gap": "{{label}}, diferencia con el mejor",
    "tools.calc.valuation_scenarios.title": "Escenarios de valuación",
    "tools.calc.valuation_scenarios.progress": "Armando los escenarios",
    "tools.calc.valuation_scenarios.price_at_horizon_low": "Precio en el horizonte, caso bajo",
    "tools.calc.valuation_scenarios.price_at_horizon_base": "Precio en el horizonte, caso base",
    "tools.calc.valuation_scenarios.price_at_horizon_high": "Precio en el horizonte, caso alto",
    "tools.calc.valuation_scenarios.annual_return_low": "Retorno anual, caso bajo",
    "tools.calc.valuation_scenarios.annual_return_base": "Retorno anual, caso base",
    "tools.calc.valuation_scenarios.value_at_horizon_low": "Valor del monto en el horizonte, caso bajo",
    "tools.calc.valuation_scenarios.value_at_horizon_base": "Valor del monto en el horizonte, caso base",
    "tools.calc.valuation_scenarios.value_at_horizon_high": "Valor del monto en el horizonte, caso alto",
    "tools.calc.valuation_scenarios.annual_return_high": "Retorno anual, caso alto",
    "tools.card.retry": "Reintentar",
    "tools.card.source.user": "Lo dijiste tú",
    "tools.card.source.page": "{{title}}",
    "tools.card.source.page_dated": "{{title}}, {{date}}",
    "tools.card.source.computed": "Calculado a partir de los otros datos",
    "tools.card.source.not_found": "No encontrado",
    "tools.card.source.market_data": "Datos de mercado de Argus",
    "tools.card.source.market_data_dated": "Datos de mercado de Argus, {{date}}",
    "tools.card.source.assumption": "Supuesto en la respuesta",
    "tools.card.failure.exactly_one_unknown": "Deja exactamente un dato en blanco para calcularlo.",
    "tools.card.failure.missing_input": "Ninguna fuente aportó {{field}}. Escríbelo para calcular.",
    "tools.card.failure.unknown_argument": "Uno de estos datos no forma parte de este cálculo.",
    "tools.card.failure.invalid_arguments": "Estos datos no pudieron producir un resultado.",
    "tools.card.failure.tool_execution_failed": "Este resultado no está disponible por ahora.",
    "tools.card.failure.no_solution": "Ningún valor de {{field}} encaja con estos datos.",
    "tools.card.failure.payment_never_balances": "Con este {{field}}, ningún número de períodos cuadra el plan.",
    "tools.card.failure.payment_below_interest": "El {{field}} es menor que el interés de cada período, así que el saldo nunca baja.",
    "tools.card.failure.no_rate_fits": "Ninguna {{field}} encaja con estos datos.",
    "tools.card.failure.rate_out_of_range": "La {{field}} está fuera de rango.",
    "tools.card.failure.division_by_zero": "El dato {{field}} no puede ser cero aquí.",
    "tools.card.failure.growth_needs_positive_values": "El dato {{field}} debe ser mayor que cero.",
    "tools.card.failure.rate_never_reaches_target": "Con esta {{field}}, la meta nunca se alcanza.",
    "tools.card.failure.discount_below_terminal_growth": "La {{field}} debe ser mayor que la tasa de crecimiento terminal.",
    "tools.card.failure.fees_exceed_amount": "Las {{field}} superan el monto recibido.",
    "tools.card.failure.no_periods": "El dato {{field}} debe ser al menos uno.",
    "tools.card.failure.periods_not_whole": "El dato {{field}} debe terminar en una fecha de cupón.",
    "tools.card.failure.scenarios_out_of_order": "Los casos bajo, base y alto deben subir en orden; revisa el dato {{field}}.",
    "tools.card.failure.periods_beyond_limit": "Con este dato {{field}}, el plan tomaría más de 1,200 periodos.",
    "tools.card.failure.fee_above_balance": "El dato {{field}} se lleva más que todo el saldo cada año.",
    "tools.card.failure.fees_need_loan_terms": "Agrega el dato {{field}} para contar las comisiones en la tasa.",
    "tools.card.failure.price_below_zero": "Con este dato {{field}}, el precio quedaría por debajo de cero.",
    "tools.card.title": "Resultado",
    "tools.card.solved_value": "Valor calculado",
    "tools.card.input": "Dato",
    "tools.card.named_input": "Dato {{name}}",
    "tools.card.inputs": "Datos usados",
    "tools.card.unknown": "Por calcular",
    "tools.card.show_numbers": "Ver los números",
    "tools.card.hide_numbers": "Ocultar los números",
    "tools.card.yes": "Sí",
    "tools.card.no": "No",
    "tools.card.unavailable": "Este resultado no está disponible.",
    "tools.card.enter_value": "Ingresa un valor para actualizar el resultado.",
    "tools.card.recompute_failed": "No se pudo actualizar el resultado. Inténtalo de nuevo.",
    "tools.card.saved_result": "Se muestra el resultado guardado mientras cambias los datos.",
    "tools.card.updating": "Actualizando...",
    "tools.card.status.invalid": "Estos datos no pudieron producir un resultado.",
    "tools.card.status.ambiguous": "Estos datos tienen más de una respuesta posible.",
    "tools.card.status.bounded": "Una respuesta confiable está fuera de los límites de esta herramienta.",
    "tools.card.status.unavailable": "Este resultado no está disponible por ahora."
  }
} as const;

function interpolate(template: string, values: Record<string, string | number | boolean | null>) {
  return template.replace(/\{\{([^}]+)\}\}/g, (_match, key: string) => String(values[key] ?? key));
}

export function toolText(value: LocalizedText | null | undefined, locale: Locale) {
  if (!value) return '';
  const template = messages[locale][value.locale_key] ?? value.locale_key.split('.').at(-1)?.replaceAll('_', ' ') ?? value.locale_key;
  return interpolate(template, value.interpolation_args);
}

export function toolFailureText(code: string, fields: string[], locale: Locale) {
  const key = `tools.card.failure.${code}`;
  const template = messages[locale][key] ?? (locale === 'en' ? 'This calculation could not be completed.' : 'No se pudo completar este cálculo.');
  const field = fields[0] ? fieldLabel(fields[0], locale) : (locale === 'en' ? 'input' : 'dato');
  return interpolate(template, { field });
}

export function toolStatusText(status: string, locale: Locale) {
  return messages[locale][`tools.card.status.${status}`] ?? (locale === 'en' ? 'This result is unavailable.' : 'Este resultado no está disponible.');
}

export function toolSourceText(kind: string, locale: Locale, values: Record<string, string> = {}) {
  const dated = values.date && ['page', 'market_data'].includes(kind) ? `${kind}_dated` : kind;
  return interpolate(messages[locale][`tools.card.source.${dated}`] ?? kind.replaceAll('_', ' '), values);
}

export function fieldLabel(key: string, locale: Locale) {
  return messages[locale][`tools.calc.fields.${key}`] ?? key.split('.').at(-1)?.replaceAll('_', ' ') ?? key;
}
