# Generated by scripts/sync_argus_core.py.
# Source revision: 5430d98d61d815e6c4a2bed60213b411a2bb875e; do not edit by hand.
"""Neutral tool transports; importing these types never loads the tool catalog.

Arguments and returns are validated by each declaration. These envelopes carry
them without pretending every tool has the same inputs or financial result.
"""

from __future__ import annotations

from typing import Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    JsonValue,
    SerializerFunctionWrapHandler,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    model_serializer,
    model_validator,
)

from server.argus_core.research_contracts import ResearchSource

ToolScalar = StrictBool | StrictInt | StrictFloat | StrictStr | None
ToolFailureStatus = Literal["invalid", "ambiguous", "bounded", "unavailable"]
ToolStatus = Literal["succeeded", ToolFailureStatus]
MAX_TOOL_CALLS = 8
# Where an input fact came from: the user stated it, a dated page supplied it,
# Argus's own market data supplied it, the answer assumed it and says so, or the
# calculation derived it. ``not_found`` stays readable on older cards.
ToolFactSourceKind = Literal[
    "user",
    "page",
    "market_data",
    "account",
    "record",
    "assumption",
    "computed",
    "not_found",
]
# An argument model may carry its inputs' provenance under this one field name;
# the declaration projects it onto the card and marks an edited input as stated.
TOOL_INPUT_SOURCES_FIELD = "sources"


class ToolContract(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, allow_inf_nan=False)


class ToolCall(ToolContract):
    tool_name: str = Field(min_length=1, max_length=80, pattern=r"^[a-z][a-z0-9_]*$")
    call_id: str = Field(min_length=1, max_length=128)
    arguments: dict[str, JsonValue] = Field(default_factory=dict)


class LocalizedText(ToolContract):
    locale_key: str = Field(min_length=1, max_length=160)
    interpolation_args: dict[str, ToolScalar] = Field(default_factory=dict)


class ToolRepair(ToolContract):
    """A typed fix the user can tap: an argument edit the recompute route accepts."""

    kind: Literal["set_inputs"] = "set_inputs"
    label: LocalizedText
    changes: dict[str, ToolScalar] = Field(min_length=1)


class ToolFailure(ToolContract):
    code: str = Field(min_length=1, max_length=128, pattern=r"^[a-z][a-z0-9_]*$")
    fields: list[str] = Field(default_factory=list)
    repair: ToolRepair | None = None


class ToolOutcome(ToolContract):
    status: ToolStatus
    result: dict[str, JsonValue] | None = None
    failure: ToolFailure | None = None

    @model_validator(mode="after")
    def answer_and_failure_are_exclusive(self) -> ToolOutcome:
        if self.status == "succeeded":
            if self.result is None or self.failure is not None:
                raise ValueError("A successful tool must have a result and no failure")
        elif self.result is not None or self.failure is None:
            raise ValueError("An unsuccessful tool must have a failure and no result")
        return self


class ToolProgress(LocalizedText):
    call_id: str
    tool_name: str


class ToolFactSource(ToolContract):
    """Where a fact came from. A page names its title and date, market data names
    the date of its bar, and local account/record facts name their dated owner."""

    kind: ToolFactSourceKind
    title: str | None = Field(default=None, max_length=300)
    url: str | None = Field(default=None, max_length=2048)
    date: str | None = Field(default=None, pattern=r"^\d{4}-\d{2}-\d{2}$")
    ref: str | None = Field(default=None, min_length=1, max_length=160)
    currency: str | None = Field(default=None, pattern=r"^[A-Z]{3}$")

    @model_validator(mode="after")
    def only_a_page_is_cited(self) -> ToolFactSource:
        if self.kind == "page":
            if self.ref or self.currency:
                raise ValueError("A page source does not carry a local record reference")
            return self
        if self.title or self.url:
            raise ValueError("Only a page source carries a title or url")
        if self.kind in {"account", "record"}:
            if not self.date or not self.ref or not self.currency:
                raise ValueError(
                    "An account or record source requires date, ref and currency"
                )
            return self
        if self.ref or self.currency:
            raise ValueError("Only an account or record source carries ref or currency")
        if self.date and self.kind != "market_data":
            raise ValueError(
                "Only a page, market data, account or record source carries a date"
            )
        return self

    @model_serializer(mode="wrap")
    def _omit_absent_citation(self, handler: SerializerFunctionWrapHandler):
        data = handler(self)
        return {key: value for key, value in data.items() if value is not None}


class ToolFact(ToolContract):
    name: str
    label: LocalizedText
    value: ToolScalar
    value_text: LocalizedText | None = None
    unit: LocalizedText | None = None
    # Additive: older cards carry no source and remain readable.
    source: ToolFactSource | None = None
    # Supporting rows retained for comparisons, omitted from card display.
    comparison_only: bool = Field(default=False, exclude_if=lambda value: not value)


class ToolInputFact(ToolFact):
    editable: bool = False
    unknown: bool = False
    # One of the few inputs that drive the result, shown under the answer.
    driving: bool = False
    visibility: Literal["public", "private"] = "private"

    @model_validator(mode="after")
    def unknown_is_blank_and_read_only(self) -> ToolInputFact:
        if self.unknown and (self.value is not None or self.editable):
            raise ValueError("The retained unknown must be blank and read-only")
        if self.driving and self.value is None:
            raise ValueError("A driving input always carries a value")
        return self


class ToolVisualPoint(ToolContract):
    time: str
    value: StrictFloat


class ToolVisual(ToolContract):
    """Frozen visual evidence owned by the tool card, without a later fetch.

    ``portfolio_equity`` is a run's equity curve; ``value_path`` is a computed
    path over dated periods, such as a balance paid down or savings built up.
    """

    kind: Literal["portfolio_equity", "value_path"]
    currency: str | None = None
    base_value: StrictFloat | None = None
    series: list[ToolVisualPoint]


class ToolCardPresentation(ToolContract):
    title: LocalizedText
    answer: ToolFact | None = None
    narrative: str | None = None
    sources: list[ResearchSource] = Field(default_factory=list)
    visual: ToolVisual | None = None
    rows: list[ToolFact] = Field(default_factory=list)
    inputs: list[ToolInputFact] = Field(default_factory=list)
    notes: list[LocalizedText] = Field(default_factory=list)


class ToolResultCard(ToolContract):
    kind: Literal["tool_result"] = "tool_result"
    schema_version: Literal[1] = 1
    tool_name: str
    call_id: str
    artifact_id: str
    input_revision: int = Field(default=0, ge=0)
    card_type: str = Field(min_length=1)
    card_version: int = Field(ge=1)
    arguments: dict[str, JsonValue]
    outcome: ToolOutcome
    presentation: ToolCardPresentation
    artifact_state: Literal["active", "consumed", "cancelled", "superseded"] = "active"

    @model_validator(mode="after")
    def failure_cannot_present_an_answer(self) -> ToolResultCard:
        if self.outcome.status != "succeeded" and (
            self.presentation.answer is not None
            or self.presentation.narrative is not None
            or self.presentation.visual is not None
        ):
            raise ValueError("A failed or bounded tool cannot present an answer")
        return self
