import { businessContactEmail, siteCopy } from "./site-copy";
export type { BusinessLocale } from "@/lib/site-routes";

const es = {
  navigation: {
    business: "Para negocios",
    personal: "Personal",
    approach: "La idea",
    howItWorks: "Cómo funciona",
    about: "Nosotros",
    demo: siteCopy.es.cta,
    menu: "Abrir menú",
    close: "Cerrar menú",
    label: "Navegación principal",
    language: "Idioma",
    back: "Volver a negocios",
    skip: "Ir al contenido",
  },
  closing: { footerLabel: "Navegación al pie" },
  contact: {
    noScript: `Activa JavaScript para enviar este formulario o escríbenos a ${businessContactEmail}.`,
    name: "Tu nombre",
    email: "Correo electrónico",
    description: "¿Qué te cuesta mantener al día?",
    optional: "(opcional)",
    namePlaceholder: "Tu nombre",
    emailPlaceholder: "tu@negocio.com",
    descriptionPlaceholder: "Unas palabras son suficientes.",
    submit: "Enviar mensaje",
    sending: "Enviando…",
    required: "Completa este campo.",
    invalidEmail: "Escribe un correo válido, como tu@negocio.com.",
    successTitle: "Recibimos tu mensaje.",
    successBody: "Te responderemos al correo que escribiste.",
    empty: "Sin comentario",
    privacy: "Usamos tu nombre, correo y mensaje para responderte.",
    privacyLink: "Política de privacidad",
    errors: "Revisa los campos marcados.",
    unavailable: `No pudimos enviar tu mensaje. Lo que escribiste sigue aquí. Inténtalo de nuevo o escríbenos a ${businessContactEmail}.`,
    rateLimited: "Hiciste varios intentos seguidos. Espera unos minutos e inténtalo de nuevo.",
    rejected: "Revisa los campos marcados e inténtalo de nuevo.",
  },
  personal: {
    eyebrow: "CUADRAO PERSONAL",
    title: "Tu dinero también merece estar cuadrao.",
    body: "Estamos preparando Cuadrao para tus finanzas personales. Pronto compartiremos más.",
    status: "En preparación",
    return: "Conoce Cuadrao para negocios",
  },
};
const en: typeof es = {
  navigation: {
    business: "Business",
    personal: "Personal",
    approach: "The idea",
    howItWorks: "How it works",
    about: "About",
    demo: siteCopy.en.cta,
    menu: "Open menu",
    close: "Close menu",
    label: "Main navigation",
    language: "Language",
    back: "Back to Business",
    skip: "Skip to content",
  },
  closing: { footerLabel: "Footer navigation" },
  contact: {
    noScript: `Enable JavaScript to send this form or email us at ${businessContactEmail}.`,
    name: "Your name",
    email: "Email address",
    description: "What’s hard to keep up with?",
    optional: "(optional)",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@business.com",
    descriptionPlaceholder: "A few words are enough.",
    submit: "Send message",
    sending: "Sending…",
    required: "Complete this field.",
    invalidEmail: "Enter a valid email, such as you@business.com.",
    successTitle: "We received your message.",
    successBody: "We’ll reply to the email address you entered.",
    empty: "No comment",
    privacy: "We use your name, email and message to reply to you.",
    privacyLink: "Privacy policy",
    errors: "Check the marked fields.",
    unavailable: `We couldn’t send your message. What you wrote is still here. Try again or email us at ${businessContactEmail}.`,
    rateLimited: "You made several attempts in a row. Wait a few minutes and try again.",
    rejected: "Check the marked fields and try again.",
  },
  personal: {
    eyebrow: "CUADRAO PERSONAL",
    title: "Your money deserves to be squared away, too.",
    body: "We’re preparing Cuadrao for your personal finances. More to come soon.",
    status: "In preparation",
    return: "Explore Cuadrao for business",
  },
};
export const businessContent = { es, en };
