# Generated by scripts/sync_argus_core.py.
# Source revision: 5430d98d61d815e6c4a2bed60213b411a2bb875e; do not edit by hand.
"""Money math Argus owns, in Python, under unit tests (operating rule 6).

Every function here is pure: typed inputs in, a typed answer or a typed
``NoSolution`` out, never an exception for an input that has no answer and
never a guess. Money amounts carry their currency. Nothing here reads a
message, calls a provider or formats prose.
"""

from server.argus_core.finance.money import Money
from server.argus_core.finance.outcomes import NoSolution

__all__ = ["Money", "NoSolution"]
