# Generated by scripts/sync_argus_core.py.
# Source revision: 5430d98d61d815e6c4a2bed60213b411a2bb875e; do not edit by hand.
"""Comparison over a set, ranked by a computed key, never by recommendation."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Literal

Preference = Literal["higher", "lower"]


@dataclass(frozen=True)
class RankedItem:
    label: str
    value: float
    rank: int
    gap_to_best: float


def rank_by_key(
    items: Sequence[tuple[str, float]], *, prefer: Preference
) -> list[RankedItem]:
    """Order ``(label, value)`` pairs by value; ties share a rank, first wins order."""
    ordered = sorted(items, key=lambda item: item[1], reverse=prefer == "higher")
    if not ordered:
        return []
    best = ordered[0][1]
    ranked: list[RankedItem] = []
    rank = 0
    previous: float | None = None
    for index, (label, value) in enumerate(ordered, start=1):
        if previous is None or value != previous:
            rank = index
            previous = value
        ranked.append(
            RankedItem(label=label, value=value, rank=rank, gap_to_best=value - best)
        )
    return ranked
