# Generated by scripts/sync_argus_core.py.
# Source revision: 5430d98d61d815e6c4a2bed60213b411a2bb875e; do not edit by hand.
"""Discounted cash flow, and the growth a price implies (reverse DCF)."""

from __future__ import annotations

from server.argus_core.finance._roots import bracketed_root
from server.argus_core.finance.outcomes import NoSolution


def dcf_value(
    cash_flow: float,
    growth: float,
    discount_rate: float,
    years: int,
    terminal_growth: float,
) -> float | NoSolution:
    """Present value of ``years`` growing cash flows plus a Gordon terminal value."""
    if years <= 0:
        return NoSolution(field="years", code="no_periods")
    if discount_rate <= terminal_growth:
        return NoSolution(field="discount_rate", code="discount_below_terminal_growth")
    if discount_rate <= -1 or growth <= -1:
        return NoSolution(field="discount_rate", code="rate_out_of_range")
    value = 0.0
    flow = cash_flow
    for year in range(1, years + 1):
        flow = cash_flow * (1.0 + growth) ** year
        value += flow / (1.0 + discount_rate) ** year
    terminal = flow * (1.0 + terminal_growth) / (discount_rate - terminal_growth)
    value += terminal / (1.0 + discount_rate) ** years
    return value


def implied_growth(
    value: float,
    cash_flow: float,
    discount_rate: float,
    years: int,
    terminal_growth: float,
) -> float | NoSolution:
    """The constant growth over ``years`` that makes the DCF equal ``value``."""
    if value <= 0 or cash_flow <= 0:
        return NoSolution(field="cash_flow", code="growth_needs_positive_values")
    if years <= 0:
        return NoSolution(field="years", code="no_periods")
    if discount_rate <= terminal_growth:
        return NoSolution(field="discount_rate", code="discount_below_terminal_growth")

    def difference(candidate: float) -> float:
        priced = dcf_value(cash_flow, candidate, discount_rate, years, terminal_growth)
        if isinstance(priced, NoSolution):
            raise ValueError(priced.code)
        return priced - value

    root = bracketed_root(difference)
    if root is None:
        return NoSolution(field="value", code="no_rate_fits")
    return root
