#!/bin/bash
# Writes untracked worktree-local QA env files for the LOCAL Supabase stack.
# Output files hold local-stack credentials only and must never be committed.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

eval "$(supabase status -o env)"
for required in API_URL ANON_KEY SERVICE_ROLE_KEY DB_URL JWT_SECRET; do
  if [ -z "${!required:-}" ]; then
    echo "❌ supabase status did not provide $required" >&2
    exit 1
  fi
done
case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *)
    echo "❌ refusing to write env files: supabase status returned a non-loopback API URL" >&2
    exit 1
    ;;
esac

umask 177
cat > .env <<EOF
# Generated by scripts/qa/write-local-env.sh for LOCAL issue-248 QA only.
# Untracked; regenerate at will; never commit; never point at production.
SUPABASE_PROJECT_URL=$API_URL
SUPABASE_URL=$API_URL
SUPABASE_ANON_PUBLIC_KEY=$ANON_KEY
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
SUPABASE_JWT_SECRET=$JWT_SECRET
SUPABASE_POSTGRES_SESSION_POOLER_URL=$DB_URL
ALPACA_API_KEY=local-qa-disabled
ALPACA_SECRET_KEY=local-qa-disabled
ALPACA_PAPER_TRADING=true
OPENROUTER_API_KEY=local-qa-disabled
ARGUS_UTILITY_MODEL=local-qa/disabled
ARGUS_UTILITY_FALLBACK_MODEL=local-qa/disabled
ARGUS_CHAT_MODEL=local-qa/disabled
ARGUS_CHAT_FALLBACK_MODEL=local-qa/disabled
ARGUS_STRUCTURED_MODEL=local-qa/disabled
ARGUS_STRUCTURED_FALLBACK_MODEL=local-qa/disabled
ARGUS_CONTEXT_MODEL=local-qa/disabled
ARGUS_CONTEXT_FALLBACK_MODEL=local-qa/disabled
EOF

cat > web/.env.local <<EOF
# Generated by scripts/qa/write-local-env.sh for LOCAL issue-248 QA only.
# Untracked; regenerate at will; never commit; never point at production.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
NEXT_PUBLIC_MOCK_AUTH=false
# Same-site host (localhost:3000 -> localhost:8000) so the Argus HttpOnly
# cookie transport is real in local QA, matching a same-site deployment.
NEXT_PUBLIC_ARGUS_API_URL=http://localhost:8000/api/v1
ARGUS_APP_ORIGIN=http://localhost:3000
NEXT_PUBLIC_ENABLE_SPANISH=true
NEXT_PUBLIC_STRATEGIES_ENABLED=false
NEXT_PUBLIC_COLLECTIONS_ENABLED=false
NEXT_PUBLIC_OMNISEARCH_ENABLED=true
NEXT_PUBLIC_CHAT_EXPLORATORY_SUGGESTIONS_ENABLED=false
NEXT_PUBLIC_PRIVATE_ALPHA_ONBOARDING_ENABLED=false
EOF

bash "$ROOT_DIR/scripts/qa/assert-nonprod-target.sh"
echo "✅ wrote worktree-local .env and web/.env.local for the local QA stack"
