// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteStrategiesById, getAssets, getAuthSession, getBacktestsById, getHealth, getHistory, getMarketBars, getScreeners, getStrategies, getStrategiesById, type Options, patchAuthProfile, postAgentDraft, postAuthLogout, postBacktests, postBillingCheckout, postFeedback, postMocksBacktest, postShare, postStrategies, postWebhookBilling, putStrategiesById } from '../sdk.gen';
import type { DeleteStrategiesByIdData, DeleteStrategiesByIdResponse, GetAssetsData, GetAssetsResponse, GetAuthSessionData, GetAuthSessionResponse, GetBacktestsByIdData, GetBacktestsByIdResponse, GetHealthData, GetHistoryData, GetHistoryResponse, GetMarketBarsData, GetMarketBarsResponse, GetScreenersData, GetStrategiesByIdData, GetStrategiesByIdResponse, GetStrategiesData, GetStrategiesResponse, PatchAuthProfileData, PatchAuthProfileResponse, PostAgentDraftData, PostAgentDraftResponse, PostAuthLogoutData, PostAuthLogoutResponse, PostBacktestsData, PostBacktestsError, PostBacktestsResponse, PostBillingCheckoutData, PostFeedbackData, PostMocksBacktestData, PostMocksBacktestResponse, PostShareData, PostShareResponse, PostStrategiesData, PostStrategiesResponse, PostWebhookBillingData, PutStrategiesByIdData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthSessionQueryKey = (options?: Options<GetAuthSessionData>) => createQueryKey('getAuthSession', options);

/**
 * Get current authenticated user session
 */
export const getAuthSessionOptions = (options?: Options<GetAuthSessionData>) => queryOptions<GetAuthSessionResponse, DefaultError, GetAuthSessionResponse, ReturnType<typeof getAuthSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthSessionQueryKey(options)
});

/**
 * Update user profile settings
 */
export const patchAuthProfileMutation = (options?: Partial<Options<PatchAuthProfileData>>): UseMutationOptions<PatchAuthProfileResponse, DefaultError, Options<PatchAuthProfileData>> => {
    const mutationOptions: UseMutationOptions<PatchAuthProfileResponse, DefaultError, Options<PatchAuthProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAuthProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStrategiesQueryKey = (options?: Options<GetStrategiesData>) => createQueryKey('getStrategies', options);

/**
 * List user strategies
 */
export const getStrategiesOptions = (options?: Options<GetStrategiesData>) => queryOptions<GetStrategiesResponse, DefaultError, GetStrategiesResponse, ReturnType<typeof getStrategiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStrategies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStrategiesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getStrategiesInfiniteQueryKey = (options?: Options<GetStrategiesData>): QueryKey<Options<GetStrategiesData>> => createQueryKey('getStrategies', options, true);

/**
 * List user strategies
 */
export const getStrategiesInfiniteOptions = (options?: Options<GetStrategiesData>) => infiniteQueryOptions<GetStrategiesResponse, DefaultError, InfiniteData<GetStrategiesResponse>, QueryKey<Options<GetStrategiesData>>, string | Pick<QueryKey<Options<GetStrategiesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetStrategiesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getStrategies({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStrategiesInfiniteQueryKey(options)
});

/**
 * Save a new strategy
 */
export const postStrategiesMutation = (options?: Partial<Options<PostStrategiesData>>): UseMutationOptions<PostStrategiesResponse, DefaultError, Options<PostStrategiesData>> => {
    const mutationOptions: UseMutationOptions<PostStrategiesResponse, DefaultError, Options<PostStrategiesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postStrategies({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a strategy
 */
export const deleteStrategiesByIdMutation = (options?: Partial<Options<DeleteStrategiesByIdData>>): UseMutationOptions<DeleteStrategiesByIdResponse, DefaultError, Options<DeleteStrategiesByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteStrategiesByIdResponse, DefaultError, Options<DeleteStrategiesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteStrategiesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStrategiesByIdQueryKey = (options: Options<GetStrategiesByIdData>) => createQueryKey('getStrategiesById', options);

/**
 * Get strategy by id
 */
export const getStrategiesByIdOptions = (options: Options<GetStrategiesByIdData>) => queryOptions<GetStrategiesByIdResponse, DefaultError, GetStrategiesByIdResponse, ReturnType<typeof getStrategiesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStrategiesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStrategiesByIdQueryKey(options)
});

/**
 * Update a strategy
 */
export const putStrategiesByIdMutation = (options?: Partial<Options<PutStrategiesByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PutStrategiesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutStrategiesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putStrategiesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getHistoryQueryKey = (options?: Options<GetHistoryData>) => createQueryKey('getHistory', options);

/**
 * Get user run history
 */
export const getHistoryOptions = (options?: Options<GetHistoryData>) => queryOptions<GetHistoryResponse, DefaultError, GetHistoryResponse, ReturnType<typeof getHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHistoryQueryKey(options)
});

export const getHistoryInfiniteQueryKey = (options?: Options<GetHistoryData>): QueryKey<Options<GetHistoryData>> => createQueryKey('getHistory', options, true);

/**
 * Get user run history
 */
export const getHistoryInfiniteOptions = (options?: Options<GetHistoryData>) => infiniteQueryOptions<GetHistoryResponse, DefaultError, InfiniteData<GetHistoryResponse>, QueryKey<Options<GetHistoryData>>, string | Pick<QueryKey<Options<GetHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getHistory({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHistoryInfiniteQueryKey(options)
});

/**
 * Execute a backtest simulation
 */
export const postBacktestsMutation = (options?: Partial<Options<PostBacktestsData>>): UseMutationOptions<PostBacktestsResponse, PostBacktestsError, Options<PostBacktestsData>> => {
    const mutationOptions: UseMutationOptions<PostBacktestsResponse, PostBacktestsError, Options<PostBacktestsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBacktests({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBacktestsByIdQueryKey = (options: Options<GetBacktestsByIdData>) => createQueryKey('getBacktestsById', options);

/**
 * Get detailed backtest results
 */
export const getBacktestsByIdOptions = (options: Options<GetBacktestsByIdData>) => queryOptions<GetBacktestsByIdResponse, DefaultError, GetBacktestsByIdResponse, ReturnType<typeof getBacktestsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBacktestsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBacktestsByIdQueryKey(options)
});

/**
 * Draft a strategy using AI Natural Language input
 */
export const postAgentDraftMutation = (options?: Partial<Options<PostAgentDraftData>>): UseMutationOptions<PostAgentDraftResponse, DefaultError, Options<PostAgentDraftData>> => {
    const mutationOptions: UseMutationOptions<PostAgentDraftResponse, DefaultError, Options<PostAgentDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAgentDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke upstream session and clear local auth cookies
 */
export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<PostAuthLogoutResponse, DefaultError, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLogoutResponse, DefaultError, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAssetsQueryKey = (options: Options<GetAssetsData>) => createQueryKey('getAssets', options);

/**
 * Search available market assets
 */
export const getAssetsOptions = (options: Options<GetAssetsData>) => queryOptions<GetAssetsResponse, DefaultError, GetAssetsResponse, ReturnType<typeof getAssetsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAssets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAssetsQueryKey(options)
});

export const getMarketBarsQueryKey = (options: Options<GetMarketBarsData>) => createQueryKey('getMarketBars', options);

/**
 * TradingView Universal Datafeed Proxy
 */
export const getMarketBarsOptions = (options: Options<GetMarketBarsData>) => queryOptions<GetMarketBarsResponse, DefaultError, GetMarketBarsResponse, ReturnType<typeof getMarketBarsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMarketBars({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMarketBarsQueryKey(options)
});

export const getScreenersQueryKey = (options?: Options<GetScreenersData>) => createQueryKey('getScreeners', options);

/**
 * Alpaca Movers / Most-Actives proxy
 */
export const getScreenersOptions = (options?: Options<GetScreenersData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getScreenersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScreeners({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScreenersQueryKey(options)
});

/**
 * Initialize payment gateway session
 */
export const postBillingCheckoutMutation = (options?: Partial<Options<PostBillingCheckoutData>>): UseMutationOptions<unknown, DefaultError, Options<PostBillingCheckoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostBillingCheckoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBillingCheckout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Supabase Edge Function to intercept gateway updates
 */
export const postWebhookBillingMutation = (options?: Partial<Options<PostWebhookBillingData>>): UseMutationOptions<unknown, DefaultError, Options<PostWebhookBillingData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostWebhookBillingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWebhookBilling({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create OpenGraph shareable link from simulation
 */
export const postShareMutation = (options?: Partial<Options<PostShareData>>): UseMutationOptions<PostShareResponse, DefaultError, Options<PostShareData>> => {
    const mutationOptions: UseMutationOptions<PostShareResponse, DefaultError, Options<PostShareData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postShare({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Submit user feedback
 */
export const postFeedbackMutation = (options?: Partial<Options<PostFeedbackData>>): UseMutationOptions<unknown, DefaultError, Options<PostFeedbackData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostFeedbackData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postFeedback({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * API health and uptime check
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

/**
 * Dev-only endpoint for Prism mocking
 */
export const postMocksBacktestMutation = (options?: Partial<Options<PostMocksBacktestData>>): UseMutationOptions<PostMocksBacktestResponse, DefaultError, Options<PostMocksBacktestData>> => {
    const mutationOptions: UseMutationOptions<PostMocksBacktestResponse, DefaultError, Options<PostMocksBacktestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postMocksBacktest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
