var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/chat/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00yc.j9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0sp2xph.js")
R.c("server/chunks/ssr/_0kgfci1._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rnk4i0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tz4w46._.js")
R.c("server/chunks/ssr/_02p6a15._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_chat_page_actions_0ymiytn.js")
R.m(35133)
module.exports=R.m(35133).exports
