from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "web" / "lib" / "search-casefold-data.ts"
BACKEND_TARGET = ROOT / "src" / "argus" / "domain" / "search_symbol_casefold_data.py"
EXPECTED_UNICODE_VERSION = "13.0.0"
_CHUNK_SIZE = 80


def _typescript_string(value: str) -> str:
    return (
        json.dumps(value, ensure_ascii=False)
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def _string_chunks(value: str) -> list[str]:
    characters = list(value)
    return [
        "".join(characters[index : index + _CHUNK_SIZE])
        for index in range(0, len(characters), _CHUNK_SIZE)
    ]


def _casefold_contract() -> tuple[str, str, list[tuple[str, str]], list[tuple[int, int]]]:
    if unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        raise RuntimeError(
            "Search casefold data must be generated with the pinned "
            f"Python 3.10 Unicode {EXPECTED_UNICODE_VERSION} contract; got "
            f"{unicodedata.unidata_version}."
        )

    single_character_folds: list[tuple[str, str]] = []
    expansions: list[tuple[str, str]] = []
    alphanumeric_ranges: list[tuple[int, int]] = []
    range_start: int | None = None
    range_end: int | None = None
    for codepoint in range(sys.maxunicode + 1):
        if 0xD800 <= codepoint <= 0xDFFF:
            continue
        source = chr(codepoint)
        if source.isalnum():
            if range_start is None:
                range_start = range_end = codepoint
            elif range_end is not None and codepoint == range_end + 1:
                range_end = codepoint
            else:
                assert range_end is not None
                alphanumeric_ranges.append((range_start, range_end))
                range_start = range_end = codepoint
        folded = source.casefold()
        if folded == source:
            continue
        if len(folded) == 1:
            single_character_folds.append((source, folded))
        else:
            expansions.append((source, folded))
    if range_start is not None:
        assert range_end is not None
        alphanumeric_ranges.append((range_start, range_end))

    return (
        "".join(source for source, _ in single_character_folds),
        "".join(target for _, target in single_character_folds),
        expansions,
        alphanumeric_ranges,
    )


def render_casefold_module(
    contract: tuple[str, str, list[tuple[str, str]], list[tuple[int, int]]] | None = None,
) -> str:
    single_source, single_target, expansions, alphanumeric_ranges = (
        contract or _casefold_contract()
    )
    source_chunks = ",\n".join(
        f"  {_typescript_string(chunk)}" for chunk in _string_chunks(single_source)
    )
    target_chunks = ",\n".join(
        f"  {_typescript_string(chunk)}" for chunk in _string_chunks(single_target)
    )
    expansion_rows = ",\n".join(
        f"  [{_typescript_string(source)}, {_typescript_string(target)}]"
        for source, target in expansions
    )
    alphanumeric_rows = ",\n".join(
        f"  [{start}, {end}]" for start, end in alphanumeric_ranges
    )

    return f"""// Generated by scripts/generate_frontend_search_casefold.py.
// Keep this data pinned to the Python 3.10 backend search contract.

export const PYTHON_CASEFOLD_UNICODE_VERSION = "{EXPECTED_UNICODE_VERSION}";

export const PYTHON_CASEFOLD_SINGLE_SOURCE = [
{source_chunks}
].join("");

export const PYTHON_CASEFOLD_SINGLE_TARGET = [
{target_chunks}
].join("");

export const PYTHON_CASEFOLD_EXPANSIONS = [
{expansion_rows}
] as const;

export const PYTHON_ALPHANUMERIC_RANGES = [
{alphanumeric_rows}
] as const;
"""


def render_backend_symbol_casefold_module(
    contract: tuple[str, str, list[tuple[str, str]], list[tuple[int, int]]] | None = None,
) -> str:
    single_source, single_target, expansions, _ = contract or _casefold_contract()
    source_chunks = "\n".join(
        f"    {_typescript_string(chunk)}" for chunk in _string_chunks(single_source)
    )
    target_chunks = "\n".join(
        f"    {_typescript_string(chunk)}" for chunk in _string_chunks(single_target)
    )
    expansion_rows = "\n".join(
        f"    ({_typescript_string(source)}, {_typescript_string(target)}),"
        for source, target in expansions
    )

    return f'''"""Generated raw Python 3.10 casefold data for Postgres symbols."""

from __future__ import annotations

PYTHON_CASEFOLD_UNICODE_VERSION = "{EXPECTED_UNICODE_VERSION}"

PYTHON_CASEFOLD_SINGLE_SOURCE = (
{source_chunks}
)

PYTHON_CASEFOLD_SINGLE_TARGET = (
{target_chunks}
)

PYTHON_CASEFOLD_EXPANSIONS = (
{expansion_rows}
)
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the checked-in TypeScript map is stale.",
    )
    args = parser.parse_args()
    contract = _casefold_contract()
    expected_by_target = {
        TARGET: render_casefold_module(contract).encode("utf-8"),
        BACKEND_TARGET: render_backend_symbol_casefold_module(contract).encode("utf-8"),
    }
    if args.check:
        if any(
            not target.exists() or target.read_bytes() != expected
            for target, expected in expected_by_target.items()
        ):
            print(
                "Search casefold data is stale; regenerate it with "
                f"{Path(__file__).relative_to(ROOT)}.",
                file=sys.stderr,
            )
            return 1
        return 0

    for target, expected in expected_by_target.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
