# Generated by scripts/sync_argus_core.py.
# Source revision: 5430d98d61d815e6c4a2bed60213b411a2bb875e; do not edit by hand.
"""Comparison over a set: items ranked by one computed key, never recommended."""

from __future__ import annotations

from dataclasses import replace
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from server.argus_core.calculations._shared import (
    CalculationArguments,
    CalculationResult,
    Symbol,
    free_policy,
    input_fact,
    money_round,
    text,
)
from server.argus_core.finance import comparison
from server.argus_core.tool_contracts import (
    LocalizedText,
    ToolCardPresentation,
    ToolFact,
    ToolOutcome,
)
from server.argus_core.tool_declaration import (
    ToolCardBinding,
    ToolDeclaration,
    ToolProgressTemplate,
)

KeyKind = Literal["percent", "money", "multiple", "count"]


class ComparisonItem(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False)

    label: str = Field(min_length=1, max_length=120)
    symbol: Symbol
    value: float


class RankedComparisonArguments(CalculationArguments):
    key_label: str = Field(min_length=1, max_length=120)
    key_kind: KeyKind = "percent"
    prefer: Literal["higher", "lower"] = "lower"
    items: list[ComparisonItem] = Field(min_length=2, max_length=12)


# Each ranked figure's fact name: the prefix and its position from the best item.
RANK_FACT_PREFIX = "rank_"
# Each ranked item's gap to the best, named by its position like its figure.
GAP_FACT_PREFIX = "gap_"


class RankedRow(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False)

    label: str
    symbol: str | None
    value: float
    rank: int
    gap_to_best: float


class RankedComparisonResult(CalculationResult):
    key_label: str
    prefer: str
    rows: list[RankedRow]


def compute_ranked_comparison(
    arguments: RankedComparisonArguments,
) -> RankedComparisonResult:
    # Ranked by position, so items that share a label keep their own symbols.
    ranked = comparison.rank_by_key(
        [(str(index), item.value) for index, item in enumerate(arguments.items)],
        prefer=arguments.prefer,
    )
    return RankedComparisonResult(
        key_label=arguments.key_label,
        prefer=arguments.prefer,
        rows=[
            RankedRow(
                label=arguments.items[int(row.label)].label,
                symbol=arguments.items[int(row.label)].symbol,
                value=row.value,
                rank=row.rank,
                gap_to_best=row.gap_to_best,
            )
            for row in ranked
        ],
    )


def _unit(kind: KeyKind, currency: str) -> LocalizedText | None:
    if kind == "percent":
        return text("chat.tools.units.percent")
    if kind == "money":
        return text("tools.calc.units.currency", code=currency)
    if kind == "multiple":
        return text("tools.calc.units.multiple")
    return None


def present_ranked_comparison(
    arguments: RankedComparisonArguments, outcome: ToolOutcome
) -> ToolCardPresentation:
    inputs = [
        input_fact("key_label", arguments.key_label),
        input_fact("prefer", arguments.prefer),
    ]
    title = text("tools.calc.ranked_comparison.title", key=arguments.key_label)
    if outcome.status != "succeeded":
        return ToolCardPresentation(title=title, inputs=inputs)
    result = RankedComparisonResult.model_validate(outcome.result)
    unit = _unit(arguments.key_kind, arguments.currency)

    def display_value(value: float) -> float:
        if arguments.key_kind == "money":
            return money_round(value, arguments.currency)
        return round(value, 2)

    facts = [
        ToolFact(
            name=f"{RANK_FACT_PREFIX}{index}",
            label=text(
                "tools.calc.ranked_comparison.row", rank=row.rank, label=row.label
            ),
            value=display_value(row.value),
            unit=unit,
        )
        for index, row in enumerate(result.rows)
    ]
    rows: list[ToolFact] = []
    for index, row in enumerate(result.rows):
        if index > 0:
            rows.append(facts[index])
        rows.append(
            ToolFact(
                name=f"{GAP_FACT_PREFIX}{index}",
                label=text("tools.calc.ranked_comparison.gap", label=row.label),
                value=display_value(row.gap_to_best),
                unit=unit,
                comparison_only=index == 0,
            )
        )
    return ToolCardPresentation(
        title=title,
        answer=facts[0],
        rows=rows,
        inputs=inputs,
        notes=[text("tools.calc.notes.ranked_not_recommended")],
    )


def get_ranked_comparison_declaration() -> ToolDeclaration:
    return ToolDeclaration(
        name="ranked_comparison",
        description=(
            "Rank a set of products or instruments by one stated numeric key, "
            "preferring higher or lower values, and show each item's gap to the best. "
            "Items carry the figure a page or the user supplied; nothing is recommended. "
            "The ranked figures are rank_0, rank_1 and so on, from the best item."
        ),
        handler=compute_ranked_comparison,
        policy=replace(
            free_policy("prefer", "key_label", driving=()), public_receipt="cited_facts"
        ),
        progress=ToolProgressTemplate(
            locale_key="tools.calc.ranked_comparison.progress",
            argument_fields=("key_label",),
        ),
        card=ToolCardBinding(
            card_type="ranked_comparison", version=1, presenter=present_ranked_comparison
        ),
        domain=("Ranked by the stated key only; ties share a rank (decision 6).",),
    )
