import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect, login, navigate, read, screenshot, noOverflow, evidenceDirectory, openSettingsPanel } from './fixtures';

for (const locale of ['en', 'es'] as const) {
  test(`${locale}: real ledger import, edit and bounded full-volume pagination`, async ({ page }, testInfo) => {
    await login(page, locale);
    const en = locale === 'en';
    const started = performance.now();
    const all = await read(page, '/transactions?limit=25');
    const duration = performance.now() - started;
    expect(all.total).toBeGreaterThanOrEqual(12_000);
    expect(all.items).toHaveLength(25);
    expect(JSON.stringify(all).length).toBeLessThan(100_000);
    expect(duration).toBeLessThan(3000);
    const volume = { rows: all.total, pageRows: all.items.length, bytes: JSON.stringify(all).length, milliseconds: duration, recordedAt: new Date().toISOString(), origin: 'isolated local fixture on 8022' };
    writeFileSync(join(evidenceDirectory, `${locale}-ledger-volume.json`), JSON.stringify(volume, null, 2));
    await testInfo.attach('volume-and-latency', { body: JSON.stringify(volume), contentType: 'application/json' });
    await navigate(page, 'accounts');
    await page.getByRole('button', { name: en ? 'Add account' : 'Agregar cuenta', exact: true }).first().click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel(en ? 'Name' : 'Nombre', { exact: true }).fill('Browser savings');
    await dialog.getByLabel(en ? 'Institution' : 'Institución').fill('Local fixture');
    await dialog.getByLabel(en ? 'Currency' : 'Moneda', { exact: true }).fill('USD');
    await dialog.getByLabel(en ? 'Opening balance' : 'Saldo inicial').fill('1000');
    await dialog.getByRole('button', { name: en ? 'Save' : 'Guardar', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    const account = (await read(page, '/accounts?currency=USD')).items.find((item: {name:string}) => item.name === 'Browser savings');
    expect(account.balance).toBe('1000.00');
    await navigate(page, 'transactions');
    await page.getByRole('button', { name: en ? 'Import CSV' : 'Importar CSV', exact: true }).click();
    await dialog.getByRole('combobox', { name: en ? 'Account' : 'Cuenta', exact: true }).selectOption(account.id);
    await dialog.locator('summary').filter({ hasText: en ? 'Paste content' : 'Pegar contenido' }).click();
    await dialog.getByLabel(en ? 'CSV content' : 'Contenido CSV').fill('date,merchant,description,amount,currency,category,kind\n2026-09-18,Browser market,Weekly groceries,-45.50,USD,groceries,expense\n');
    await dialog.getByRole('button', { name: en ? 'Read columns' : 'Leer columnas' }).click();
    await dialog.getByRole('button', { name: en ? 'Prepare review' : 'Preparar revisión' }).click();
    await dialog.getByRole('button', { name: en ? 'Save reviewed transactions' : 'Guardar movimientos revisados' }).click();
    await expect(dialog.getByRole('status')).toContainText('1');
    await dialog.getByRole('button', { name: en ? 'Done' : 'Listo', exact: true }).click();
    // The same UI filter scopes the displayed rows and the full-filter totals.
    await page.getByLabel(en ? 'Search merchant or description' : 'Buscar comercio o descripción').fill('Browser market');
    await page.getByRole('button', { name: en ? 'Search' : 'Buscar', exact: true }).click();
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await page.getByRole('button', { name: en ? /^Details: Browser market/ : /^Detalles: Browser market/ }).click();
    await dialog.getByRole('combobox', { name: en ? 'Category' : 'Categoría', exact: true }).selectOption('shopping');
    await dialog.getByRole('button', { name: en ? 'Save' : 'Guardar', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await page.reload();
    await page.getByRole('combobox', { name: /Display currency, no conversion|Moneda, sin conversión/ }).selectOption('USD');
    await expect(page.locator('tbody tr')).toHaveCount(1);
    expect((await read(page, `/accounts/${account.id}`)).balance).toBe('954.50');
    const imported = await read(page, '/transactions?q=Browser%20market');
    expect(imported.items).toHaveLength(1);
    expect(imported.items[0].category).toBe('shopping');
    await screenshot(page, `${locale}-ledger-import`);
    await noOverflow(page);
  });
}

test('budget, recurring payment, allocated goal and immutable scenario', async ({ page }) => {
  await login(page);
  await navigate(page, 'budgets');
  await page.getByRole('button', { name: 'Create budget', exact: true }).first().click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Category', exact: true }).selectOption('shopping');
  await dialog.getByLabel('Limit', { exact: false }).fill('900');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Add recurring bill', exact: true }).first().click();
  await dialog.getByLabel('Name', { exact: true }).fill('Browser monthly internet');
  await dialog.getByRole('combobox', { name: 'Account', exact: true }).selectOption('acct-demo-01');
  await dialog.getByLabel('Amount', { exact: true }).fill('45');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const billRow = page.locator('tr').filter({ hasText: 'Browser monthly internet' });
  await billRow.getByRole('button', { name: 'Record as paid' }).click();
  await navigate(page, 'goals');
  await page.getByRole('button', { name: 'Create goal', exact: true }).first().click();
  await dialog.getByLabel('Name', { exact: true }).fill('Browser travel fund');
  await dialog.getByLabel('Target', { exact: true }).fill('3000');
  await dialog.getByLabel('Target date', { exact: true }).fill('2027-09-20');
  await dialog.getByLabel('Monthly contribution', { exact: true }).fill('250');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const goalRow = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Browser travel fund', exact: true }) });
  await goalRow.getByRole('button', { name: 'Allocate accounts', exact: true }).click();
  await dialog.locator('input[type=number]').first().fill('100');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect((await read(page, '/goals')).items.find((item: {name:string}) => item.name === 'Browser travel fund').allocated).toBe('100.00');
  await navigate(page, 'scenarios');
  await page.getByLabel('Scenario name').fill('Browser retirement baseline');
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await page.getByRole('button', { name: 'Save receipt', exact: true }).click();
  await expect.poll(async () => (await read(page, '/scenarios')).items.some((item: {name:string}) => item.name === 'Browser retirement baseline')).toBe(true);
  const baseline = (await read(page, '/scenarios')).items.find((item: {name:string}) => item.name === 'Browser retirement baseline');
  const original = await read(page, `/scenarios/${baseline.id}`);
  await page.getByLabel('Scenario name').fill('Browser retirement revised');
  await page.getByLabel('Monthly contribution', { exact: true }).fill('750');
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await page.getByRole('button', { name: 'Save receipt', exact: true }).click();
  await expect.poll(async () => (await read(page, '/scenarios')).items.some((item: {name:string}) => item.name === 'Browser retirement revised')).toBe(true);
  const revised = (await read(page, '/scenarios')).items.find((item: {name:string}) => item.name === 'Browser retirement revised');
  await page.getByRole('combobox', { name: 'Before', exact: true }).selectOption(baseline.id);
  await page.getByRole('combobox', { name: 'After', exact: true }).selectOption(revised.id);
  await page.getByRole('button', { name: 'Compare', exact: true }).click();
  await expect(page.locator('.planning-compare-panel')).toContainText('Browser retirement revised');
  expect(await read(page, `/scenarios/${baseline.id}`)).toEqual(original);
  await page.reload();
  await expect(page.getByText('Browser retirement baseline').first()).toBeVisible();
  await screenshot(page, 'en-planning-receipt');
});

test('paper investment preview confirms once and preserves linked net worth', async ({ page }) => {
  await login(page);
  const before = await read(page, '/overview');
  const initialSimulation = (await read(page, '/investing/portfolio')).simulation;
  await navigate(page, 'investments');
  await page.getByRole('tab', { name: 'Simulation', exact: true }).click();
  await page.getByRole('button', { name: 'Simulate change', exact: true }).first().click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Symbol', { exact: true }).fill('SPY');
  await dialog.getByLabel('Quantity', { exact: true }).fill('1');
  await dialog.getByRole('button', { name: 'Create preview' }).click();
  await expect(dialog).toContainText('Fictional order preview');
  await dialog.getByRole('button', { name: 'Confirm in simulation' }).click();
  await expect(dialog).toContainText('Cash remaining');
  await screenshot(page, 'en-paper-order-receipt');
  await dialog.getByRole('button', { name: 'Close', exact: true }).last().click();
  await page.reload();
  const after = await read(page, '/overview');
  const finalSimulation = (await read(page, '/investing/portfolio')).simulation;
  expect(finalSimulation.recent_orders).toHaveLength(initialSimulation.recent_orders.length + 1);
  expect(finalSimulation.positions.some((item: {symbol:string,quantity:string}) => item.symbol === 'SPY' && Number(item.quantity) > 0)).toBe(true);
  expect(after.net_worth.map((item: {net_worth:string}) => item.net_worth)).toEqual(before.net_worth.map((item: {net_worth:string}) => item.net_worth));
  await page.getByRole('button', { name: 'Simulate change', exact: true }).first().click();
  await dialog.getByLabel('Symbol', { exact: true }).fill('SPY');
  await dialog.getByLabel('Quantity', { exact: true }).fill('10000000');
  await dialog.getByRole('button', { name: 'Create preview' }).click();
  await dialog.getByRole('button', { name: 'Confirm in simulation' }).click();
  await expect(dialog.getByRole('alert')).toContainText('not enough');
  expect((await read(page, '/investing/portfolio')).simulation.recent_orders).toHaveLength(finalSimulation.recent_orders.length);
});

test('mobile settings, confirmed memory, privacy and keyless saved assistant', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page);
  await navigate(page, 'settings');
  await openSettingsPanel(page, 'profile');
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Display name', { exact: true }).fill('Browser household owner');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await openSettingsPanel(page, 'appearance');
  await dialog.getByRole('radio', { name: 'Dark', exact: true }).check();
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.locator('.platform-shell')).toHaveAttribute('data-theme', 'dark');
  await openSettingsPanel(page, 'memories');
  await dialog.getByRole('button', { name: 'Add memory' }).click();
  await dialog.getByLabel('Memory', { exact: true }).fill('Keep a separate emergency reserve.');
  await dialog.getByRole('checkbox', { name: 'I confirm this fact is correct and want to save it.' }).check();
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog.getByText('Keep a separate emergency reserve.', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await openSettingsPanel(page, 'privacy');
  await expect(dialog).toContainText(/local/i);
  await page.keyboard.press('Escape');
  await navigate(page, 'chat');
  await page.getByTestId('chat-input').fill('What should my next step be?');
  await page.getByTestId('chat-send').click();
  await expect(page.getByRole('alert')).toContainText('Text interpretation is unavailable');
  await navigate(page, 'chat');
  const netWorthResponse = page.waitForResponse(response => response.url().endsWith('/api/platform/chat/turn'));
  await page.locator('[data-example-id="net-worth"]').click();
  const netWorth = await netWorthResponse;
  expect(netWorth.ok(), `net-worth turn: ${netWorth.status()} ${netWorth.ok() ? '' : await netWorth.text()}`).toBe(true);
  await expect(page.locator('.argus-fact')).not.toHaveCount(0);
  const conversationId = new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('conversation_id');
  expect(conversationId).toBeTruthy();
  const thread = page.getByTestId('conversation-page');
  await thread.locator('summary[aria-label="Conversation actions"]').click();
  await thread.getByRole('menuitem', { name: 'Pin', exact: true }).click();
  await expect.poll(async () => (await read(page, `/chat/conversations/${conversationId}`)).conversation.pinned).toBe(true);
  const savedMessages = (await read(page, `/chat/conversations/${conversationId}`)).messages;
  await screenshot(page, 'en-390-assistant-sources');
  await page.locator('.argus-fact').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: join(evidenceDirectory, 'en-390-assistant-facts.png'), fullPage: false, animations: 'disabled' });
  await page.reload();
  expect((await read(page, '/settings')).profile.display_name).toBe('Browser household owner');
  expect((await read(page, '/settings/memories')).items).toHaveLength(1);
  expect((await read(page, `/chat/conversations/${conversationId}`)).messages).toEqual(savedMessages);
  await navigate(page, 'overview');
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await page.getByTestId('recent-conversations').locator(`[data-conversation-id="${conversationId}"]`).getByRole('button').first().click();
  await expect(page).toHaveURL(new RegExp(`conversation_id=${conversationId}`));
  await expect(page.locator('.argus-fact')).not.toHaveCount(0);
  await noOverflow(page);
});

test('Spanish 320: header actions reflow with increased text spacing', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 });
  await login(page, 'es');
  await navigate(page, 'transactions');
  await page.addStyleTag({ content: '.p-page-header button { letter-spacing: .12em; word-spacing: .16em; }' });
  await noOverflow(page);
  await screenshot(page, 'es-320-transactions-text-spacing');
  await page.getByRole('button', { name: 'Importar CSV', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await noOverflow(page);
});

for (const width of [1440, 1024, 768, 390, 320]) {
  test(`Spanish ${width}: route coverage, dated sources, no overflow and keyboard escape`, async ({ page }) => {
    const errors: string[] = [];
    const external: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (!['127.0.0.1', 'localhost'].includes(new URL(request.url()).hostname)) external.push(request.url()); });
    await page.setViewportSize({ width, height: 900 });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await login(page, 'es');
    for (const route of ['overview', 'accounts', 'transactions', 'budgets', 'goals', 'scenarios', 'investments', 'credit', 'tax-estate', 'membership', 'employer', 'help', 'settings']) {
      await navigate(page, route);
      await expect(page.locator('.p-main')).not.toContainText(/Cargando/);
      await expect(page.locator('.p-main')).not.toContainText('—');
      await expect(page.locator('vite-error-overlay')).toHaveCount(0);
      await noOverflow(page);
      if ([1440, 390].includes(width) && ['overview', 'transactions'].includes(route)) await screenshot(page, `es-${width}-${route}`);
    }
    await openSettingsPanel(page, 'privacy');
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Privacidad', exact: true })).toBeFocused();
    await screenshot(page, `es-${width}-settings`);
    expect(errors).toEqual([]);
    expect(external).toEqual([]);
  });
}

test('credit, tax, estate and membership produce local receipts', async ({ page }) => {
  await login(page);
  await navigate(page, 'credit');
  await page.getByRole('button', { name: 'Add debt', exact: true }).click();
  const dialog = page.getByRole('dialog');
  for (const [label, value] of Object.entries({ 'Debt name': 'Browser credit record', 'Outstanding balance': '1200', 'Credit limit': '3000', 'Annual rate (%)': '12', 'Fixed monthly payment': '100' })) await dialog.getByLabel(label, { exact: true }).fill(value);
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const debt = (await read(page, '/credit')).accounts.find((item:{name:string}) => item.name === 'Browser credit record');
  await page.getByRole('combobox', { name: 'Debt', exact: true }).selectOption(debt.id);
  await page.getByRole('button', { name: 'Calculate scenario', exact: true }).click();
  await expect(page.getByText('Balance payoff scenario', { exact: true })).toBeVisible();
  await navigate(page, 'tax-estate');
  await page.getByRole('button', { name: 'Create folder', exact: true }).click();
  await dialog.locator('input[name=country]').fill('US');
  await dialog.locator('input[name=year]').fill('2026');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Country, year and currency', exact: true }).selectOption({ label: 'US · 2026 · USD' });
  await page.getByRole('button', { name: 'Add income', exact: true }).click();
  await dialog.getByLabel('Description', { exact: true }).fill('Browser income');
  await dialog.getByLabel('Amount', { exact: true }).fill('1200');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Add document', exact: true }).click();
  await dialog.getByLabel('Description', { exact: true }).fill('Browser statement');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const statement = page.getByRole('checkbox', { name: /Browser statement/ });
  await statement.click();
  await expect(statement).toBeChecked();
  await page.getByRole('button', { name: 'Mark folder complete', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reopen folder', exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download JSON records', exact: true }).click();
  expect((await downloadEvent).suggestedFilename()).toMatch(/\.json$/);
  await page.getByLabel('Scenario rate (%)', { exact: true }).fill('10');
  await page.getByRole('button', { name: 'Calculate worksheet', exact: true }).click();
  await expect(page).toHaveURL(/record_id=tax-scenario-/);
  const taxId = new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('record_id');
  const worksheet = page.locator(`.services-result[data-record-id="${taxId}"]`);
  await expect(worksheet).toBeVisible();
  const worksheetText = await worksheet.innerText();
  await page.reload();
  await expect(worksheet).toHaveText(worksheetText, { useInnerText: true });
  await expect(page.getByRole('combobox', { name: 'Saved worksheets', exact: true })).toHaveValue(taxId!);
  await page.getByLabel('Scenario rate (%)', { exact: true }).fill('12');
  await page.getByRole('button', { name: 'Calculate worksheet', exact: true }).click();
  await expect(page.locator('.services-result')).toContainText('(12%)');
  await page.getByRole('combobox', { name: 'Saved worksheets', exact: true }).selectOption(taxId!);
  await expect(worksheet).toHaveText(worksheetText, { useInnerText: true });
  await page.getByRole('button', { name: 'Estate inventory', exact: true }).click();
  await page.getByRole('button', { name: 'Add asset', exact: true }).click();
  await dialog.getByLabel('Asset name', { exact: true }).fill('Browser keepsake');
  await dialog.getByLabel('Recorded value', { exact: true }).fill('250');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Add contact', exact: true }).click();
  await dialog.getByLabel('Name', { exact: true }).fill('Browser beneficiary');
  await dialog.getByLabel('Relationship', { exact: true }).fill('Family');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Edit allocation', exact: true }).last().click();
  await dialog.getByLabel('Browser beneficiary (%)').fill('100');
  await dialog.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await screenshot(page, 'en-estate-record');
  await navigate(page, 'membership');
  await page.getByRole('button', { name: 'Simulate this plan', exact: true }).first().click();
  await dialog.getByRole('button', { name: 'Confirm in demo' }).click();
  await expect(dialog).toHaveCount(0);
  await page.reload();
  expect((await read(page, '/membership')).receipts).toHaveLength(1);
  await navigate(page, 'employer');
  const code = await page.locator('.p-main code').innerText();
  await page.getByRole('button', { name: 'Enroll in the demo', exact: true }).click();
  await dialog.getByLabel('Demo program code', { exact: false }).fill(code);
  await dialog.getByRole('button', { name: 'Enroll locally' }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Choose benefit', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Selected', exact: true })).toBeVisible();
  await navigate(page, 'help');
  await page.getByRole('button', { name: /Reserve in demo$/ }).first().click();
  await dialog.getByRole('button', { name: 'Confirm in demo' }).click();
  await expect(dialog).toHaveCount(0);
  await page.reload();
  await expect(page.getByText(/Saved locally|Local reservation|Reserved/).first()).toBeVisible();
});

test('viewer permissions and other-household isolation are visible', async ({ page }) => {
  await login(page, 'en', 'user-viewer');
  await navigate(page, 'settings');
  await openSettingsPanel(page, 'data');
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('button', { name: 'Reset household data' })).toBeDisabled();
  await page.keyboard.press('Escape');
  await navigate(page, 'accounts');
  const before = await read(page, '/accounts');
  await page.getByRole('button', { name: 'Add account', exact: true }).click();
  await dialog.getByLabel('Name', { exact: true }).fill('Forbidden viewer account');
  await dialog.getByLabel('Institution', { exact: true }).fill('Local fixture');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  expect((await read(page, '/accounts')).total).toBe(before.total);
  await page.keyboard.press('Escape');
  await navigate(page, 'settings');
  await openSettingsPanel(page, 'security');
  await dialog.getByRole('button', { name: 'End all sessions' }).click();
  await dialog.getByRole('button', { name: 'Confirm sign out' }).click();
  await expect(page.getByRole('button', { name: /^(Sign in|Iniciar sesión)$/ })).toBeVisible();
  await login(page, 'es', 'user-other');
  const other = await read(page, '/transactions?limit=25');
  expect(other.total).toBeLessThan(12_000);
  expect(other.items.every((item: {account_id:string}) => item.account_id !== 'acct-demo-01')).toBe(true);
});

test('household export and deliberate local reset survive reload', async ({ page }) => {
  await login(page);
  const settings = await read(page, '/settings');
  await navigate(page, 'settings');
  await openSettingsPanel(page, 'data');
  const dialog = page.getByRole('dialog');
  const download = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Export household data (JSON)' }).click();
  expect((await download).suggestedFilename()).toBe('argus-household.json');
  await dialog.getByRole('button', { name: 'Reset household data' }).click();
  await expect(dialog.getByRole('button', { name: 'Empty this household' })).toBeDisabled();
  await dialog.getByLabel('Confirm the name', { exact: false }).fill(settings.household.name);
  await dialog.getByLabel('Type RESET THIS HOUSEHOLD to confirm', { exact: true }).fill('RESET THIS HOUSEHOLD');
  await dialog.getByRole('button', { name: 'Empty this household' }).click();
  await expect.poll(async () => (await read(page, '/accounts')).total).toBe(0);
  await page.reload();
  expect((await read(page, '/transactions')).total).toBe(0);
  await page.keyboard.press('Escape');
  await navigate(page, 'overview');
  await expect(page.getByRole('heading', { name: 'Empieza con una cuenta', exact: true })).toBeVisible();
  await screenshot(page, 'es-reset-empty-state');
});


test('320px initial overview derives household currency before any user change', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 });
  const currencies: string[] = [];
  page.on('request', request => {
    const url = new URL(request.url());
    if (url.pathname === '/api/platform/overview') currencies.push(url.searchParams.get('currency') ?? '');
  });
  await login(page, 'es', 'user-demo', 'default');
  await navigate(page, 'overview');
  const session = await read(page, '/session');
  const initialCurrency = session.currency_context.currency;
  expect(initialCurrency).not.toBeNull();
  await expect(page.locator('.p-networth-main')).toContainText(initialCurrency);
  expect(currencies.length).toBeGreaterThan(0);
  expect(currencies.every(currency => currency === initialCurrency)).toBe(true);
  await expect(page.getByText('Espacio local', { exact: true }).first()).toBeVisible();
  await noOverflow(page);
  await page.getByRole('button', { name: /^Avisos/ }).click();
  await expect(page.getByRole('dialog', { name: 'Tus avisos' })).toBeVisible();
  await expect(page.getByRole('dialog')).not.toContainText('Actualizando avisos');
  await expect(page.getByRole('dialog').getByRole('alert')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: /^Avisos/ })).toBeFocused();
  await screenshot(page, 'es-320-default-currency-header');
});
