var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/account/security/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13hu1js._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_075451..js")
R.c("server/chunks/ssr/[root-of-the-server]__0rnk4i0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tz4w46._.js")
R.c("server/chunks/ssr/_02p6a15._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_account_security_page_actions_0f5mn90.js")
R.m(83840)
module.exports=R.m(83840).exports
